// HR-02 resume-corpus and HR-04 interview-scorecards-question-banks: the
// structural screen over the two drafted artifact sets of people-hr cluster 2.
//
// tests/drafted/hr-c1-drafted-screen.test.js is the model and, through it, the
// operations C1 screen: documents are read lazily inside each test, the CORE-04
// roster is generated in-test rather than read off disk, and every allowed
// capitalized string except a two-phrase, two-word furniture list is derived
// from canon or from generated bytes.
//
// Three things are worth stating before the assertions.
//
// First, `validate` cannot help here. Neither C2 set is deterministic, so there
// is no regeneration diff: a one-byte edit to a committed resume, question or
// scorecard is caught by this file or by nothing. Every arm below therefore has
// a failing witness, and none of them is a shape that cannot go wrong.
//
// Second, every closed list this screen applies is read out of
// `specs/artifact-specs.yaml` rather than typed here: the screening status
// vocabulary, `age_route_lexemes`, the protected-characteristic probe list,
// `required_resume_fields`, the scorecard status vocabulary, and the experience
// band. If the shipped bytes and the published rule ever part company, a count
// moves and an assertion says so. The frozen HR-01 register and the six frozen
// HR-03 transcripts are read from committed bytes and are never edited.
//
// Third, what this file deliberately does NOT know: which resume carries the
// graduation year, which resume is missing a required field, which question
// carries a probe phrase, and which scorecard was never submitted. Those are
// per-instance answer keys and answer keys do not live in this repo
// (canon/companies.md ground rules, restated in datagen/README.md). Every
// assertion below is a cardinality or a shape, recomputed at run time, and each
// plant is pinned beside the number the same rule returns with its qualifier
// dropped, so a corpus that quietly loses its distractors fails too.
import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { loadSpecs } from "../../datagen/src/specLoader.js";
import { loadCanonCompanies } from "../../datagen/src/canon.js";
import { generateArtifact } from "../../datagen/src/engine.js";
import { csvTable, fileByPath } from "../helpers/csv-table.js";
import { allowedFrom, unscreenedPhrases, unscreenedWords } from "../helpers/capitalized-screen.js";
import { moneyMatches } from "../helpers/money-shape.js";

const REPO_ROOT = join(import.meta.dirname, "..", "..");
const specs = loadSpecs(join(REPO_ROOT, "specs", "artifact-specs.yaml"));
const canon = loadCanonCompanies(join(REPO_ROOT, "canon", "companies.md"));

const PROTAGONIST = "Atticus Dundee Inc.";
const DRAFTED_IDS = ["HR-02", "HR-04"];
const REQUISITION = "RQN-2026-0105";

/** The formats the two C2 entries declare, pinned so a spec edit has to be deliberate. */
const FORMATS = { "HR-02": "markdown", "HR-04": "json + markdown" };

/** Cluster 1, which this PR reads and never writes. Source counts exclude build/. */
const C1 = {
  "HR-01": { format: "json + markdown", sources: 9 },
  "HR-03": { format: "text", sources: 12 },
  "HR-09": { format: "markdown", sources: 2 },
};

// --------------------------------------------------------------- file access

const artifactDir = (id) => join(REPO_ROOT, "artifacts", id);

function sourceNames(id, predicate) {
  const dir = artifactDir(id);
  assert.ok(existsSync(dir), `${id} is not authored yet: ${dir} does not exist`);
  return readdirSync(dir).filter(predicate).sort();
}

const markdownNames = (id) => sourceNames(id, (n) => n.endsWith(".md"));
const jsonNames = (id) => sourceNames(id, (n) => n.endsWith(".json"));
const readSource = (id, name) => readFileSync(join(artifactDir(id), name), "utf8");
const allMarkdown = (id) => markdownNames(id).map((name) => ({ name, text: readSource(id, name) }));
const allSources = (id) => [...markdownNames(id), ...jsonNames(id)].map((name) => ({ name, text: readSource(id, name) }));

const words = (text) => text.split(/\s+/).filter(Boolean).length;

const register = () => JSON.parse(readSource("HR-01", "role-requisition-register.json"));
const questionBank = () => JSON.parse(readSource("HR-04", "interview-question-bank.json"));
const rubric = () => JSON.parse(readSource("HR-04", "screening-rubric.json"));

// -------------------------------------------------------- the roster, in-test

const roster = () => csvTable(
  fileByPath(generateArtifact(specs.byId.get("CORE-04"), canon), "people-roster.csv").content
).rows;

const fullName = (r) => `${r.first_name} ${r.last_name}`;
const activeRows = () => roster().filter((r) => r.employment_status === "active");
const byId = () => new Map(roster().map((r) => [r.employee_id, r]));
const activeRoleTitles = () => [...new Set(activeRows().map((r) => r.role_title))];
const departments = () => [...new Set(activeRows().map((r) => r.department))];

// ------------------------------------------- the closed lists, read from spec

const featureMatching = (id, pattern) => {
  const found = specs.byId.get(id).planted_features.filter((f) => pattern.test(f));
  assert.equal(found.length, 1, `${id}: expected exactly one planted feature matching ${pattern}`);
  return found[0];
};

const splitList = (text) => text.split(/,\s*/).map((s) => s.trim()).filter(Boolean);

/** The two values the application log's Screening status may take. */
function screeningStatusValues() {
  const feature = featureMatching("HR-02", /^application-log\.md is the recruiter-side record/);
  const list = splitList(feature.match(/Screening status draws from: ([^.]+)\./)[1]);
  assert.equal(list.length, 2, "the spec sentence did not yield a two-value screening vocabulary");
  return list;
}

/** The phrases the corpus is swept against and must return zero hits on. */
function ageRouteLexemes() {
  const feature = featureMatching("HR-02", /^age_route_lexemes is the closed/);
  const list = splitList(feature.match(/word boundaries: ([^.]+)\./)[1]);
  assert.ok(list.length >= 6, "the spec sentence did not yield an age route lexeme list");
  return list;
}

/** The 4 to 12 year band, read off the same sentence rather than restated. */
function experienceBandYears() {
  const feature = featureMatching("HR-02", /^age_route_lexemes is the closed/);
  const m = feature.match(/inside a (\d+) to (\d+) year band/);
  assert.ok(m, "the spec sentence carries no experience band");
  return [Number(m[1]), Number(m[2])];
}

/** The six required resume fields HR-02b is defined against. */
function requiredResumeFields() {
  const feature = featureMatching("HR-04", /^screening-rubric\.json states/);
  const list = splitList(feature.match(/before scoring it: ([^.]+)\./)[1]);
  assert.equal(list.length, 6, `required_resume_fields came out of the spec with ${list.length} entries`);
  return list;
}

/** The protected-characteristic probe list, as {phrase, characteristic}. */
function probePhrases() {
  const feature = featureMatching("HR-04", /^protected_characteristic_probe_list is the closed/);
  const out = [];
  for (const m of feature.matchAll(/\b(age|family_status): ([^.]+)(?:\.|$)/g)) {
    for (const phrase of splitList(m[2])) out.push({ phrase, characteristic: m[1] });
  }
  assert.equal(out.length, 6, `the spec sentence yielded ${out.length} probe phrases, expected 6`);
  return out;
}

/** The two values a scorecard's Status may take. */
function scorecardStatusValues() {
  const feature = featureMatching("HR-04", /^six scorecards, one per frozen interview transcript/);
  const list = splitList(feature.match(/Status draws from: ([^.]+)(?:\.|$)/)[1]);
  assert.equal(list.length, 2, "the spec sentence did not yield a two-value scorecard vocabulary");
  return list;
}

/** HR-01's twelve exclusion phrases, parsed out of the frozen C1 spec sentence. */
function exclusionPhrases() {
  const feature = featureMatching("HR-01", /^exclusion_phrase_list is the closed rule set/);
  const out = [];
  for (const m of feature.matchAll(/\b(age|national_origin|disability|family_status): ([^.]+)(?:\.|$)/g)) {
    for (const phrase of splitList(m[2])) out.push(phrase);
  }
  assert.equal(out.length, 12, `the frozen spec sentence yielded ${out.length} exclusion phrases, expected 12`);
  return out;
}

/** The frozen HR-03 anchor rule's closed technology_vocabulary list. */
function technologyVocabulary() {
  const feature = featureMatching("HR-03", /^technology_vocabulary is the closed list/);
  const list = splitList(feature.match(/HR-01 exclusion list: (.+)$/)[1]);
  assert.equal(list.length, 10, `technology_vocabulary came out of the frozen spec with ${list.length} entries, expected 10`);
  return list;
}

const escapeRegExp = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
/** Word-bounded, adjacent membership: the way validate's own phrase heuristic matches. */
const carries = (text, token) => new RegExp(`\\b${escapeRegExp(token)}\\b`, "i").test(text);
/** The head word of a probe phrase is its last word, which is what the spec says. */
const headWord = (phrase) => phrase.split(" ").pop();

// ------------------------------------------------------------------- parsers

/**
 * `- Key: value` metadata lines of the block above the first section heading,
 * so an experience bullet reading like a label cannot enter the metadata map.
 */
function metadata(text) {
  const out = new Map();
  for (const line of text.split(/\n## /)[0].split("\n")) {
    const m = line.match(/^- ([A-Z][A-Za-z ]*?):(?: (.*))?$/);
    if (!m) continue;
    out.set(m[1], (m[2] ?? "").trim());
  }
  return out;
}

/** `## Heading` sections, as heading -> body. */
function sections(text) {
  const out = new Map();
  for (const chunk of text.split(/^## /m).slice(1)) {
    const nl = chunk.indexOf("\n");
    out.set(chunk.slice(0, nl).trim(), chunk.slice(nl + 1).trim());
  }
  return out;
}

/** The body of a resume: everything from the first section heading onward. */
function body(text) {
  const i = text.indexOf("\n## ");
  return i === -1 ? "" : text.slice(i);
}

/** Every `| a | b | c |` row of a markdown table, separator rows dropped. */
function tableRows(text) {
  return text.split("\n")
    .filter((l) => l.trim().startsWith("|"))
    .filter((l) => !/^\s*\|[\s|:-]+\|\s*$/.test(l))
    .map((l) => l.split("|").slice(1, -1).map((c) => c.trim()));
}

const YEAR_TOKEN = /\b(19|20)\d\d\b/g;
const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

const resumeNames = () => sourceNames("HR-02", (n) => n.startsWith("resume-ca-") && n.endsWith(".md"));
const resumes = () => resumeNames().map((name) => ({ name, text: readSource("HR-02", name) }));
const applicationLog = () => readSource("HR-02", "application-log.md");

const scorecardNames = () => sourceNames("HR-04", (n) => n.startsWith("scorecard-") && n.endsWith(".md"));
const transcriptNames = () => sourceNames("HR-03", (n) => n.startsWith("interview-transcript-") && n.endsWith(".md"));
const pairedTranscript = (scorecard) => scorecard.replace("scorecard-", "interview-transcript-");

// One to twelve, the number words a quantified experience claim may use here.
const CLAIM_NUMBER_WORDS = {
  one: 1, two: 2, three: 3, four: 4, five: 5, six: 6,
  seven: 7, eight: 8, nine: 9, ten: 10, eleven: 11, twelve: 12,
};
const CLAIM_YEAR_PHRASE = new RegExp(
  `\\b(\\d+|${Object.keys(CLAIM_NUMBER_WORDS).join("|")})\\s+years?\\b`, "gi"
);

/**
 * The largest integer any sentence of a frozen HR-03 source (feedback files
 * included: a quantified claim's sentence lives in a feedback file) pairs with a
 * technology_vocabulary token, in years, or 0 if no sentence pairs the two.
 */
function largestQuantifiedClaimYears(text, vocabulary) {
  const sentences = text.split(/(?<=[.!?])\s+/);
  let max = 0;
  for (const sentence of sentences) {
    if (!vocabulary.some((tech) => carries(sentence, tech))) continue;
    for (const m of sentence.matchAll(CLAIM_YEAR_PHRASE)) {
      const raw = m[1].toLowerCase();
      const value = CLAIM_NUMBER_WORDS[raw] ?? Number(raw);
      if (value > max) max = value;
    }
  }
  return max;
}

/** The competency ids a frozen transcript says were assessed, in its own order. */
function assessedCompetencies(text, label) {
  const block = text.split("- Competencies assessed:")[1];
  assert.ok(block, `${label}: the transcript carries no competencies assessed block`);
  const ids = block.split("\n\n")[0].split("\n")
    .map((l) => l.match(/^\s+- (.+) \((CMP-\d{2})\)$/)).filter(Boolean).map((m) => m[2]);
  assert.ok(ids.length >= 2, `${label}: fewer than two competencies assessed`);
  return ids;
}

/** The one active row printed as these bytes; an ambiguous join fails on its own. */
function resolveActive(name, roleTitle, context, rows) {
  const matches = rows.filter((r) => fullName(r) === name && r.role_title === roleTitle);
  assert.equal(
    matches.length, 1,
    `${context}: "${name} (${roleTitle})" resolves to ${matches.length} active roster rows, expected exactly 1`
  );
  return matches[0];
}

/** Every candidate name the corpus prints, off the resume titles themselves. */
const candidateNames = () => resumes().map(({ name, text }) => {
  const m = text.match(/^# (.+)$/m);
  assert.ok(m, `${name}: the resume carries no title line`);
  return m[1].trim();
});

// ------------------------------------------------------------------ furniture

// The one place a typed list is allowed. Each entry is here because a document
// has to print it and the pack ships it nowhere else.
const FURNITURE_PHRASES = [
  "Candidate ID",   // the metadata label every resume, log row and scorecard prints
  "Requisition ID", // the same
  "Scorecard ID",   // the same, on the scorecards
];
const FURNITURE_WORDS = [
  "I",   // the first-person pronoun, in a candidate's own summary
  "ID",  // the second word of all three labels above
];

// ------------------------------------------------------------- the freeze gate

test("the C2 freeze gate is exactly two drafted artifact sets, with cluster 1 untouched", () => {
  for (const id of DRAFTED_IDS) {
    const spec = specs.byId.get(id);
    assert.ok(spec, `${id} is not in the spec catalog`);
    assert.equal(spec.generation, "drafted-frozen", `${id} is not drafted-frozen`);
    assert.equal(spec.format, FORMATS[id], `${id} format drifted from the HR block`);
    assert.equal(spec.columns, undefined, `${id} is prose and carries no columns`);
    assert.ok(spec.period, `${id} states no period, so no window is pinned`);
    assert.ok(spec.planted_features.length > 0, `${id} states no planted features for validate to check`);
    assert.deepEqual(spec.canon_entities, ["co-002"], `${id} names a canon entity other than the protagonist`);
  }
  // Cluster 1 is read by this cluster and written by nobody in it.
  for (const [id, expected] of Object.entries(C1)) {
    const spec = specs.byId.get(id);
    assert.equal(spec.generation, "drafted-frozen", `${id} is no longer drafted-frozen`);
    assert.equal(spec.format, expected.format, `${id}'s frozen format line has been edited`);
    const files = sourceNames(id, (n) => n !== "build");
    assert.equal(
      files.length, expected.sources,
      `${id} ships ${files.length} source files, expected the frozen ${expected.sources}`
    );
  }
});

// ------------------------------------------------------------------- HR-C2-T1

test("HR-C2-T1: eighteen resumes, one log, one id set, and the file names agree", () => {
  const names = resumeNames();
  assert.equal(names.length, 18, `HR-02 ships ${names.length} resumes, expected 18`);
  assert.deepEqual(
    markdownNames("HR-02"), ["application-log.md", ...names].sort(),
    "HR-02 ships a markdown source that is neither a resume nor the application log"
  );

  const ids = [];
  for (const { name, text } of resumes()) {
    const meta = metadata(text);
    assert.deepEqual(
      [...meta.keys()], ["Candidate ID", "Requisition ID", "Application date", "Contact"],
      `${name}: the metadata key set has drifted from the uniform order`
    );
    const id = meta.get("Candidate ID");
    assert.equal(name, `resume-${id}.md`, `${name}: the file name and the candidate id disagree`);
    assert.equal(meta.get("Requisition ID"), REQUISITION, `${name}: the corpus spans more than one requisition`);
    ids.push(id);
  }
  assert.equal(new Set(ids).size, 18, "two resumes print the same candidate id");

  const rows = tableRows(applicationLog());
  const logIds = rows.slice(1).map((r) => r[0]);
  assert.equal(logIds.length, 18, `the application log carries ${logIds.length} rows, expected 18`);
  assert.deepEqual([...logIds].sort(), [...ids].sort(), "the log's id set and the resumes' id set differ");

  // The names in the log are the names on the resumes, resume by resume.
  const titles = new Map(resumes().map(({ text }) => [metadata(text).get("Candidate ID"), text.match(/^# (.+)$/m)[1].trim()]));
  for (const row of rows.slice(1)) {
    assert.equal(row[1], titles.get(row[0]), `the log prints "${row[1]}" for ${row[0]}, which is not that resume's own title`);
  }
});

// ------------------------------------------------------------------- HR-C2-T2

test("HR-C2-T2: no candidate is an employee, a canon person, or a co-002 address", () => {
  const rows = roster();
  const rosterFullNames = new Set(rows.map(fullName));
  const surnames = new Set(rows.map((r) => r.last_name));
  const firstNames = new Set(rows.map((r) => r.first_name));
  const employeeIds = new Set(rows.map((r) => r.employee_id));
  assert.equal(surnames.size, 40, `the roster draws on ${surnames.size} surnames; the rule was written against 40`);

  const canonText = readFileSync(join(REPO_ROOT, "canon", "people.md"), "utf8");
  const canonSeated = new Set(
    canonText.split("\n")
      .filter((l) => l.trim().startsWith("| pe-"))
      .map((l) => l.split("|").slice(1, -1).map((c) => c.trim())[1])
      .filter(Boolean)
  );
  assert.ok(canonSeated.size >= 60, `only ${canonSeated.size} canon people were parsed; the parse has broken`);

  const domains = new Set();
  for (const { name, text } of resumes()) {
    const meta = metadata(text);
    const id = meta.get("Candidate ID");
    assert.ok(!employeeIds.has(id), `${name}: the candidate id ${id} is also an employee id`);

    const person = text.match(/^# (.+)$/m)[1].trim();
    assert.ok(!rosterFullNames.has(person), `${name}: the candidate name "${person}" is a roster row`);
    assert.ok(!canonSeated.has(person), `${name}: the candidate name "${person}" is a seated canon person`);
    const parts = person.split(" ");
    assert.equal(parts.length, 2, `${name}: "${person}" is not a First Last name`);
    assert.ok(!surnames.has(parts[1]), `${name}: the surname "${parts[1]}" is one of the roster's forty`);
    assert.ok(!firstNames.has(parts[0]), `${name}: the first name "${parts[0]}" is one of the roster's own`);

    const contact = meta.get("Contact");
    const at = contact.lastIndexOf("@");
    assert.ok(at > 0, `${name}: the contact line is not an address`);
    domains.add(contact.slice(at + 1));
  }
  assert.equal(domains.size, 1, `the corpus uses ${domains.size} contact domains, expected one reserved domain`);
  const domain = [...domains][0];
  assert.ok(domain.endsWith(".example"), `the contact domain ${domain} is not a reserved example domain`);
  assert.notEqual(domain, "co002.example", "candidate addresses sit at the company's own domain");
  assert.equal(
    rows.filter((r) => r.email.endsWith("@co002.example")).length, rows.length,
    "the roster no longer sits entirely at co002.example, so the domain rule proves nothing"
  );
});

// ------------------------------------------------------------------- HR-C2-T3

test("HR-C2-T3: one graduation year against the qualifier-free eighteen, and no age route", () => {
  const [minYears, maxYears] = experienceBandYears();
  const lexemes = ageRouteLexemes();

  let inBodies = 0;
  let withMetadata = 0;
  let inEducation = 0;
  for (const { name, text } of resumes()) {
    const hits = body(text).match(YEAR_TOKEN) ?? [];
    inBodies += hits.length;
    if ((text.match(YEAR_TOKEN) ?? []).length > 0) withMetadata += 1;
    if (hits.length > 0) {
      const education = sections(text).get("Education") ?? "";
      const inSection = (education.match(YEAR_TOKEN) ?? []).length;
      assert.equal(
        inSection, hits.length,
        `${name}: a body year token sits outside the education section`
      );
      inEducation += 1;
    }
    for (const lexeme of lexemes) {
      assert.ok(!carries(text, lexeme), `${name}: carries the age route lexeme "${lexeme}"`);
    }
  }
  assert.equal(inBodies, 1, `${inBodies} four-digit year tokens sit in resume bodies, expected exactly 1`);
  assert.equal(inEducation, 1, `${inEducation} resumes carry a body year token, expected exactly 1`);
  assert.equal(
    withMetadata, 18,
    `${withMetadata} resumes carry a year token with the metadata exclusion dropped, expected 18`
  );

  // The band that makes "the year is the only route" true rather than aspirational.
  for (const { name, text } of resumes()) {
    const experience = sections(text).get("Experience");
    assert.ok(experience, `${name}: no experience section`);
    const entries = experience.split("\n").filter((l) => l.startsWith("### "));
    assert.ok(entries.length >= 2 && entries.length <= 4, `${name}: ${entries.length} experience entries, outside the 2 to 4 band`);
    let months = 0;
    for (const entry of entries) {
      const m = entry.match(/, (\d+) years? (\d+) months?$/);
      assert.ok(m, `${name}: the entry "${entry}" does not end in a duration written as N years M months`);
      months += Number(m[1]) * 12 + Number(m[2]);
    }
    assert.ok(
      months >= minYears * 12 && months <= maxYears * 12,
      `${name}: summed experience is ${Math.floor(months / 12)} years ${months % 12} months, outside the ${minYears} to ${maxYears} year band`
    );
  }

  // Review finding 4: the band's floor is a stand-in for the real rule, which is
  // that each advanced candidate's summed experience also clears the largest
  // single-technology claim the frozen HR-03 corpus records for that candidate
  // (a quantified claim's sentence lives in a feedback file and need not be
  // echoed in its paired transcript, which is exactly what "unanchored" means).
  // This is recomputed here, against the frozen bytes, rather than merely
  // asserted in the allowlist.
  const vocabulary = technologyVocabulary();
  const byCandidate = new Map();
  for (const sourceName of markdownNames("HR-03")) {
    const sourceText = readSource("HR-03", sourceName);
    const id = metadata(sourceText).get("Candidate ID");
    if (!byCandidate.has(id)) byCandidate.set(id, []);
    byCandidate.get(id).push(sourceText);
  }
  assert.equal(byCandidate.size, 2, `${byCandidate.size} candidates carry frozen HR-03 sources, expected the advanced pair of 2`);

  for (const [id, candidateSources] of byCandidate) {
    const resumeText = readSource("HR-02", `resume-${id}.md`);
    const titleLine = resumeText.match(/^# (.+)$/m);
    assert.ok(titleLine, `${id}: the resume carries no title line`);
    const name = titleLine[1].trim();

    const entries = sections(resumeText).get("Experience").split("\n").filter((l) => l.startsWith("### "));
    let candidateMonths = 0;
    for (const entry of entries) {
      const m = entry.match(/, (\d+) years? (\d+) months?$/);
      assert.ok(m, `${name}: the entry "${entry}" does not end in a duration written as N years M months`);
      candidateMonths += Number(m[1]) * 12 + Number(m[2]);
    }

    const largestClaimYears = Math.max(0, ...candidateSources.map((t) => largestQuantifiedClaimYears(t, vocabulary)));
    assert.ok(
      candidateMonths >= largestClaimYears * 12,
      `${name}: summed experience is shorter than the largest single-technology claim the frozen corpus records for this candidate`
    );
  }
});

// ------------------------------------------------------------------- HR-C2-T4

test("HR-C2-T4: one missing required field against the qualifier-free six", () => {
  const fields = requiredResumeFields();
  const required = new Set(fields);
  for (const f of ["summary", "experience", "education", "candidate_id", "full_name", "contact_email"]) {
    assert.ok(required.has(f), `required_resume_fields no longer names ${f}, so this arm is checking the wrong list`);
  }

  const statuses = new Map(tableRows(applicationLog()).slice(1).map((r) => [r[0], r[3]]));
  const sectionUnion = new Set();
  for (const { text } of resumes()) for (const key of sections(text).keys()) sectionUnion.add(key);

  const missingRequired = [];
  const missingSomeSection = [];
  for (const { name, text } of resumes()) {
    const meta = metadata(text);
    const secs = sections(text);
    const has = {
      candidate_id: /^ca-\d{3}$/.test(meta.get("Candidate ID") ?? ""),
      full_name: /^# .+$/m.test(text),
      contact_email: /@/.test(meta.get("Contact") ?? ""),
      summary: (secs.get("Summary") ?? "").length > 0,
      experience: (secs.get("Experience") ?? "").split("\n").filter((l) => l.startsWith("### ")).length >= 2,
      education: (secs.get("Education") ?? "").split("\n").filter((l) => l.startsWith("### ")).length >= 1,
    };
    const absent = fields.filter((f) => has[f] === false);
    if (absent.length > 0) missingRequired.push({ name, absent });
    if ([...sectionUnion].some((s) => !secs.has(s))) missingSomeSection.push(name);
  }

  assert.equal(
    missingRequired.length, 1,
    `${missingRequired.length} resumes lack a required field, expected exactly 1`
  );
  assert.equal(
    missingRequired[0].absent.length, 1,
    `the selected resume lacks ${missingRequired[0].absent.length} required fields, expected exactly 1`
  );
  assert.equal(
    missingSomeSection.length, 6,
    `${missingSomeSection.length} resumes are missing a section the corpus otherwise carries, expected the stated 6`
  );

  // The missing field feeds a weighted criterion, which is what makes the resume
  // score incomplete rather than merely short.
  const evidenceSources = new Set(rubric().criteria.map((c) => c.evidence_source));
  assert.ok(
    evidenceSources.has(missingRequired[0].absent[0]),
    `the missing field ${missingRequired[0].absent[0]} feeds no weighted criterion, so the resume is merely short`
  );

  // The two selections are different resumes, and both sit in the pending pool.
  const withYear = resumes().filter(({ text }) => (body(text).match(YEAR_TOKEN) ?? []).length > 0);
  assert.equal(withYear.length, 1, "the year selection has moved, so this arm cannot compare the two");
  assert.notEqual(
    withYear[0].name, missingRequired[0].name,
    "the two plants land on the same resume, so one rewrite would close both"
  );
  const [advanced, pending] = screeningStatusValues();
  assert.ok(advanced && pending, "the screening vocabulary did not resolve");
  for (const name of [withYear[0].name, missingRequired[0].name]) {
    const id = metadata(readSource("HR-02", name)).get("Candidate ID");
    assert.equal(statuses.get(id), pending, `${name} does not carry "${pending}", so the showcase would not contain it`);
  }
});

// ------------------------------------------------------------------- HR-C2-T5

test("HR-C2-T5: the funnel, its window, its two-value vocabulary and its advanced pair", () => {
  const spec = specs.byId.get("HR-02");
  const values = screeningStatusValues();
  const [advanced, pending] = values;
  const log = applicationLog();
  const meta = metadata(log);
  assert.deepEqual(
    [...meta.keys()],
    ["Requisition ID", "Requisition title", "Applications received", "Application window",
      "Screening approach", "Shortlist decision due", "Recruiter"],
    "the application log's metadata key set has drifted"
  );

  const reg = register();
  const req = reg.requisitions.find((r) => r.requisition_id === REQUISITION);
  assert.ok(req, "the corpus attaches to a requisition the frozen register does not carry");
  assert.equal(req.status, "open", "the requisition the corpus attaches to is not open");
  assert.equal(meta.get("Requisition title"), req.requisition_title, "the log's title is not the register's own");
  assert.equal(meta.get("Requisition ID"), REQUISITION, "the log names another requisition");
  assert.equal(meta.get("Applications received"), "18", "the log's stated count is not 18");
  assert.equal(meta.get("Shortlist decision due"), spec.period.end, "the decision due date is not the spec period end");
  assert.equal(meta.get("Application window"), `${spec.period.start} to 2026-03-20`, "the stated window is not the spec's own");

  const recruiter = meta.get("Recruiter").match(/^(.+) \(([^()]+)\)$/);
  assert.ok(recruiter, "the recruiter line is not a name and role title");
  const row = resolveActive(recruiter[1], recruiter[2], "the application log recruiter", activeRows());
  assert.equal(row.employee_id, req.recruiter_employee_id, "the log's recruiter is not the requisition's own recruiter");

  const rows = tableRows(log);
  assert.deepEqual(
    rows[0], ["Candidate ID", "Name", "Application date", "Screening status"],
    "the application log carries a column the four-column rule does not allow"
  );

  const byStatus = {};
  let previous = "";
  for (const [id, , date, status] of rows.slice(1)) {
    assert.match(date, ISO_DATE, `${id}: the application date is not an ISO date`);
    assert.ok(date >= spec.period.start, `${id} applied on ${date}, before the window opened`);
    assert.ok(date <= "2026-03-20", `${id} applied on ${date}, after the window closed`);
    assert.ok(date >= req.opened_date, `${id} applied on ${date}, before the requisition was raised on ${req.opened_date}`);
    assert.ok(date >= previous, `${id} breaks the application-date ordering of the table`);
    previous = date;
    assert.ok(values.includes(status), `${id} carries the screening status "${status}", which the vocabulary does not hold`);
    (byStatus[status] ??= []).push(id);
    // Each resume prints the same application date the log does.
    const own = metadata(readSource("HR-02", `resume-${id}.md`)).get("Application date");
    assert.equal(own, date, `${id}: the resume and the log disagree about the application date`);
  }
  for (const value of values) {
    assert.ok(!/shortlist|reject|declin|hire|offer/i.test(value), `the vocabulary carries "${value}", which decides the exercise`);
  }
  assert.equal((byStatus[advanced] ?? []).length, 2, `${(byStatus[advanced] ?? []).length} applications advanced, expected 2`);
  assert.equal((byStatus[pending] ?? []).length, 16, `${(byStatus[pending] ?? []).length} applications are pending, expected 16`);

  const interviewed = [...new Set(transcriptNames().map((n) => metadata(readSource("HR-03", n)).get("Candidate ID")))].sort();
  assert.deepEqual(
    [...byStatus[advanced]].sort(), interviewed,
    "the advanced set is not the candidate set the frozen interview corpus carries"
  );
});

// ------------------------------------------------------------------- HR-C2-T6

test("HR-C2-T6: one probe question against the qualifier-free four, every question mapped", () => {
  const bank = questionBank();
  const probes = probePhrases();
  const heads = probes.map((p) => headWord(p.phrase));
  assert.equal(new Set(heads).size, heads.length, "two probe phrases share a head word, so the distractor rule is ambiguous");

  assert.deepEqual(
    Object.keys(bank),
    ["bank_id", "as_of", "source_artifact", "competency_source", "protected_characteristic_probe_list", "panel_roles", "questions"],
    "the question bank's top-level key order has drifted from the documented one"
  );
  const reg = register();
  assert.equal(bank.as_of, reg.as_of, "the bank's as-of has drifted from the frozen register's own");
  assert.deepEqual(
    bank.protected_characteristic_probe_list.map((p) => `${p.characteristic}/${p.phrase}`).sort(),
    probes.map((p) => `${p.characteristic}/${p.phrase}`).sort(),
    "the shipped probe list and the spec's have parted company"
  );

  // The probe list is a rule set of its own, not a second copy of HR-01's.
  const exclusion = exclusionPhrases().map((p) => p.toLowerCase());
  for (const { phrase } of probes) {
    assert.ok(!exclusion.includes(phrase.toLowerCase()), `the probe list repeats the exclusion phrase "${phrase}"`);
  }

  assert.equal(bank.questions.length, 37, `the bank holds ${bank.questions.length} questions, expected 37`);
  const library = new Set(reg.competency_library.map((c) => c.competency_id));
  const perCompetency = {};
  bank.questions.forEach((q, i) => {
    assert.deepEqual(
      Object.keys(q),
      ["question_id", "competency_id", "question_text", "follow_up", "question_type", "panel_role"],
      "a question's key order has drifted from the documented one"
    );
    assert.equal(q.question_id, `QST-${String(i + 1).padStart(4, "0")}`, "the question ids are not sequential from QST-0001 in file order");
    assert.ok(library.has(q.competency_id), `${q.question_id} names ${q.competency_id}, which the frozen library does not carry`);
    assert.ok(q.question_text.trim() && q.follow_up.trim(), `${q.question_id} carries an empty text or follow up`);
    perCompetency[q.competency_id] = (perCompetency[q.competency_id] ?? 0) + 1;
  });
  for (const id of library) {
    assert.ok(perCompetency[id] >= 1, `${id} is covered by no question at all`);
    assert.ok(perCompetency[id] >= 3, `${id} carries ${perCompetency[id]} questions, below the three every competency gets`);
  }
  const fours = Object.entries(perCompetency).filter(([, n]) => n === 4);
  assert.equal(fours.length, 1, `${fours.length} competencies carry a fourth question, expected exactly 1`);
  assert.equal(
    Object.values(perCompetency).filter((n) => n > 4).length, 0,
    "a competency carries more than four questions, so the fourth is no longer the only extra"
  );

  const withPhrase = [];
  const headWordOnly = [];
  for (const q of bank.questions) {
    const hits = probes.filter((p) => carries(q.question_text, p.phrase));
    if (hits.length > 0) {
      withPhrase.push(q.question_id);
      assert.equal(hits.length, 1, `${q.question_id} carries ${hits.length} listed probe phrases, expected at most 1`);
      continue;
    }
    if (heads.some((h) => carries(q.question_text, h))) headWordOnly.push(q.question_id);
  }
  assert.equal(withPhrase.length, 1, `${withPhrase.length} questions carry a full probe phrase, expected exactly 1`);
  assert.equal(
    headWordOnly.length, 4,
    `${headWordOnly.length} questions carry a probe phrase's head word and no listed phrase, expected the stated 4`
  );

  // The probe is the extra question on the one competency carrying four rather
  // than three, so removing it leaves that competency covered and the approved
  // replacement restores a count.
  const probeQuestion = bank.questions.find((q) => q.question_id === withPhrase[0]);
  assert.equal(
    perCompetency[probeQuestion.competency_id], 4,
    "the probe question does not sit on the competency that carries four questions"
  );
  assert.ok(library.has(probeQuestion.competency_id), "the probe question's competency does not resolve in the library");
});

// ------------------------------------------------------------------- HR-C2-T7

test("HR-C2-T7: the panel-role map reproduces the frozen transcripts' own competency sets", () => {
  const bank = questionBank();
  const ids = new Set(bank.questions.map((q) => q.question_id));
  assert.equal(bank.panel_roles.length, 3, `panel_roles holds ${bank.panel_roles.length} entries, expected 3`);

  const frozen = new Map();
  for (const name of transcriptNames()) {
    const m = name.match(/^interview-transcript-ca-\d{3}-(.+)\.md$/);
    assert.ok(m, `${name}: the transcript file name does not carry a panel role`);
    const set = assessedCompetencies(readSource("HR-03", name), name).join(",");
    if (frozen.has(m[1])) {
      assert.equal(frozen.get(m[1]), set, `${m[1]}: the two frozen transcripts assess different competency sets`);
    }
    frozen.set(m[1], set);
  }
  assert.equal(frozen.size, 3, `the frozen corpus carries ${frozen.size} panel roles, expected 3`);

  const covered = new Set();
  for (const entry of bank.panel_roles) {
    assert.deepEqual(
      Object.keys(entry), ["panel_role", "competency_ids", "question_ids"],
      "a panel role entry's key order has drifted"
    );
    assert.ok(frozen.has(entry.panel_role), `panel_roles names "${entry.panel_role}", which no frozen transcript carries`);
    assert.equal(
      entry.competency_ids.join(","), frozen.get(entry.panel_role),
      `${entry.panel_role}: the published competency set is not the frozen transcript's own`
    );
    for (const id of entry.competency_ids) covered.add(id);

    const derived = bank.questions.filter((q) => q.panel_role === entry.panel_role).map((q) => q.question_id);
    assert.ok(derived.length > 0, `${entry.panel_role} carries no questions at all`);
    assert.deepEqual(
      entry.question_ids, derived,
      `${entry.panel_role}: the declared question list is not the set of questions carrying that role`
    );
    for (const id of entry.question_ids) {
      assert.ok(ids.has(id), `${entry.panel_role} names ${id}, which the bank does not carry`);
      const q = bank.questions.find((x) => x.question_id === id);
      assert.ok(
        entry.competency_ids.includes(q.competency_id),
        `${id} sits on ${q.competency_id}, which ${entry.panel_role} does not assess`
      );
    }
  }
  // A question outside every panel's reach carries an empty panel role, and one
  // inside a panel's reach never does.
  for (const q of bank.questions) {
    if (q.panel_role === "") {
      assert.ok(!covered.has(q.competency_id), `${q.question_id} carries no panel role but sits on ${q.competency_id}, which a panel assesses`);
    } else {
      assert.ok(covered.has(q.competency_id), `${q.question_id} carries a panel role on a competency no panel assesses`);
    }
  }
});

// ------------------------------------------------------------------- HR-C2-T8

test("HR-C2-T8: the rubric's weights, its education criterion and its recomputed maximum", () => {
  const r = rubric();
  assert.deepEqual(
    Object.keys(r),
    ["rubric_id", "as_of", "source_artifact", "requisition_id", "required_resume_fields",
      "scoring_scale", "criteria", "total_possible_score", "shortlist_guidance"],
    "the rubric's top-level key order has drifted from the documented one"
  );
  assert.equal(r.as_of, register().as_of, "the rubric's as-of has drifted from the frozen register's own");
  assert.equal(r.requisition_id, REQUISITION, "the rubric scores a different requisition from the one the corpus applies to");

  assert.deepEqual(
    r.required_resume_fields.map((f) => f.field), requiredResumeFields(),
    "the shipped required-field list and the spec's have parted company"
  );
  assert.equal(r.scoring_scale.min, 0, "the scale does not start at 0");
  assert.equal(r.scoring_scale.max, 4, "the scale does not end at 4");
  assert.equal(
    r.scoring_scale.labels.length, r.scoring_scale.max - r.scoring_scale.min + 1,
    "the scale does not carry a label at every point"
  );

  const competencies = register().requisitions.find((x) => x.requisition_id === REQUISITION).competencies;
  assert.equal(r.criteria.length, 5, `the rubric holds ${r.criteria.length} criteria, expected 5`);
  r.criteria.forEach((c, i) => {
    assert.deepEqual(
      Object.keys(c), ["criterion_id", "name", "definition", "competency_id", "weight", "evidence_source"],
      "a criterion's key order has drifted"
    );
    assert.equal(c.criterion_id, `RUB-0${i + 1}`, "the criterion ids are not sequential from RUB-01 in file order");
    assert.ok(competencies.includes(c.competency_id), `${c.criterion_id} names ${c.competency_id}, which the requisition does not carry`);
    assert.ok(["summary", "experience", "education"].includes(c.evidence_source), `${c.criterion_id} draws on ${c.evidence_source}`);
  });
  assert.equal(
    new Set(r.criteria.map((c) => c.competency_id)).size, competencies.length,
    "the criteria are not one to one with the requisition's competencies"
  );

  const weights = r.criteria.map((c) => c.weight);
  assert.equal(new Set(weights).size, weights.length, "two criteria carry the same weight, so a mis-weighting is undetectable");
  const sum = weights.reduce((a, w) => a + w, 0);
  assert.equal(
    r.total_possible_score, sum * r.scoring_scale.max,
    `total_possible_score is ${r.total_possible_score}, and the weight sum times the scale maximum is ${sum * r.scoring_scale.max}`
  );

  const education = r.criteria.filter((c) => c.evidence_source === "education");
  assert.equal(education.length, 1, `${education.length} criteria draw on education, expected exactly 1`);
  assert.ok(
    education[0].weight > Math.min(...weights) && education[0].weight < Math.max(...weights),
    `the education criterion's weight ${education[0].weight} is not strictly between ${Math.min(...weights)} and ${Math.max(...weights)}`
  );
});

// ------------------------------------------------------------------- HR-C2-T9

test("HR-C2-T9: one unsubmitted scorecard against the qualifier-free four", () => {
  const values = scorecardStatusValues();
  const [submitted, notSubmitted] = values;
  const outstanding = [];
  const withEmptyCell = [];

  for (const name of scorecardNames()) {
    const text = readSource("HR-04", name);
    const meta = metadata(text);
    const status = meta.get("Status");
    assert.ok(values.includes(status), `${name}: the status "${status}" is not in the published vocabulary`);
    const rows = tableRows(sections(text).get("Competency ratings")).slice(1);
    assert.ok(rows.length >= 2, `${name}: fewer than two competency rows`);
    const observations = sections(text).get("Additional observations") ?? "";
    const empty = rows.some((r) => r[1] === "" || r[2] === "") || observations === "";
    if (empty) withEmptyCell.push(name);

    if (status === notSubmitted) {
      outstanding.push(name);
      for (const r of rows) {
        assert.equal(r[1], "", `${name}: an outstanding scorecard carries a rating`);
        assert.equal(r[2], "", `${name}: an outstanding scorecard carries evidence`);
      }
      assert.equal(meta.get("Submitted date"), "", `${name}: an outstanding scorecard carries a submitted date`);
      continue;
    }
    const date = meta.get("Submitted date");
    assert.match(date, ISO_DATE, `${name}: the submitted date is not an ISO date`);
    assert.ok(date >= meta.get("Interview date"), `${name}: submitted on ${date}, before the interview it reports on`);
    for (const r of rows) {
      assert.match(r[1], /^[0-4]$/, `${name}: the rating "${r[1]}" is outside the 0 to 4 scale`);
      assert.ok(r[2].length > 0, `${name}: a rated row carries no evidence`);
    }
  }
  assert.equal(outstanding.length, 1, `${outstanding.length} scorecards are outstanding, expected exactly 1`);
  assert.equal(
    withEmptyCell.length, 4,
    `${withEmptyCell.length} scorecards carry an empty cell somewhere, expected the stated 4`
  );
  assert.ok(submitted, "the scorecard vocabulary did not resolve");
});

// ------------------------------------------------------------------ HR-C2-T10

test("HR-C2-T10: the six scorecards pair with the frozen transcripts and carry the roster join", () => {
  const cards = scorecardNames();
  const transcripts = transcriptNames();
  assert.equal(cards.length, 6, `HR-04 ships ${cards.length} scorecards, expected 6`);
  assert.deepEqual(
    cards.map(pairedTranscript), transcripts,
    "a scorecard has no transcript of the same name, so the pairing is not resolvable from the file names"
  );

  const spec = specs.byId.get("HR-04");
  const active = activeRows();
  const rows = byId();
  const named = new Map(register().competency_library.map((c) => [c.competency_id, c.name]));

  cards.forEach((name, i) => {
    const text = readSource("HR-04", name);
    const meta = metadata(text);
    assert.deepEqual(
      [...meta.keys()],
      ["Scorecard ID", "Candidate ID", "Requisition ID", "Panel role", "Interviewer",
        "Panelist employee ID", "Interview date", "Requested date", "Status", "Submitted date"],
      `${name}: the metadata key set has drifted from the uniform order`
    );
    assert.equal(
      meta.get("Scorecard ID"), `SCD-2026-${String(i + 1).padStart(4, "0")}`,
      `${name}: the scorecard ids are not sequential from SCD-2026-0001 in file order`
    );

    const transcript = readSource("HR-03", pairedTranscript(name));
    const tMeta = metadata(transcript);
    for (const key of ["Candidate ID", "Requisition ID"]) {
      assert.equal(meta.get(key), tMeta.get(key), `${name}: the ${key} line disagrees with its own transcript`);
    }
    assert.equal(meta.get("Requisition ID"), REQUISITION, `${name}: the scorecard names another requisition`);
    assert.equal(meta.get("Interview date"), tMeta.get("Date"), `${name}: the interview date is not the paired transcript's own date`);
    assert.equal(meta.get("Interviewer"), tMeta.get("Interviewer"), `${name}: the interviewer line is not the transcript's own line`);
    assert.ok(
      meta.get("Interview date") >= spec.period.start && meta.get("Interview date") <= spec.period.end,
      `${name}: the interview date sits outside the spec period`
    );
    assert.ok(name.includes(meta.get("Panel role")), `${name}: the panel role and the file name disagree`);
    assert.match(meta.get("Requested date"), ISO_DATE, `${name}: the requested date is not an ISO date`);

    // The join the frozen interview corpus cannot make, because it carries no employee id.
    const printed = meta.get("Interviewer").match(/^(.+) \(([^()]+)\)$/);
    assert.ok(printed, `${name}: the interviewer line is not "Name (Role Title)"`);
    const expected = resolveActive(printed[1], printed[2], `${name} interviewer`, active);
    const row = rows.get(meta.get("Panelist employee ID"));
    assert.ok(row, `${name}: the panelist employee id does not resolve to a roster row`);
    assert.equal(row.employment_status, "active", `${name}: the panelist has left the company`);
    assert.equal(row.employee_id, expected.employee_id, `${name}: the employee id is not the row the interviewer line names`);

    // One row per competency the paired transcript says was assessed, printed
    // under the frozen library's own name for it.
    const table = tableRows(sections(text).get("Competency ratings"));
    assert.deepEqual(table[0], ["Competency", "Rating", "Evidence"], `${name}: the ratings table columns have drifted`);
    const printedIds = table.slice(1).map((r) => (r[0].match(/\((CMP-\d{2})\)$/) ?? [])[1]);
    assert.deepEqual(
      printedIds, assessedCompetencies(transcript, pairedTranscript(name)),
      `${name}: the competency rows are not the set the paired transcript assessed`
    );
    for (const r of table.slice(1)) {
      const m = r[0].match(/^(.+) \((CMP-\d{2})\)$/);
      assert.equal(m[1], named.get(m[2]), `${name}: ${m[2]} is printed under a name the frozen library does not carry`);
    }

    // The panel form records; it does not decide.
    assert.ok(
      !/\b(recommend|recommendation|hire|no hire|advance|reject|overall score|total score)\b/i.test(text),
      `${name}: the scorecard states a verdict, which belongs to whoever assembles the packet`
    );
  });
});

// ------------------------------------------------------------------ HR-C2-T11

test("HR-C2-T11: no HR-01 exclusion phrase appears in either C2 set", () => {
  const phrases = exclusionPhrases();
  let scanned = 0;
  for (const id of DRAFTED_IDS) {
    for (const { name, text } of allSources(id)) {
      scanned += 1;
      const lower = text.toLowerCase();
      for (const phrase of phrases) {
        assert.ok(!lower.includes(phrase.toLowerCase()), `${id}/${name} carries the exclusion phrase "${phrase}"`);
      }
    }
  }
  assert.equal(scanned, 27, `${scanned} C2 source files were swept, expected 19 under HR-02 and 8 under HR-04`);
});

// ------------------------------------------------------------------ HR-C2-T12

test("HR-C2-T12: no em dash, no money, no percentage, and every capitalized string accounted for", () => {
  const sources = [];
  for (const id of DRAFTED_IDS) sources.push(...allSources(id).map(({ name, text }) => [`${id}/${name}`, text]));
  assert.ok(sources.length > 0, "no C2 source was read, so this screen proves nothing");
  for (const [label, text] of sources) {
    assert.ok(!text.includes("—"), `${label} carries an em dash`);
    assert.deepEqual(moneyMatches(text), [], `${label} states a figure, and this cluster carries no money`);
    assert.deepEqual(text.match(/\d+(\.\d+)?\s?%/g) ?? [], [], `${label} states a percentage`);
  }

  // A work location or a date of birth would arrive either as an unaccounted
  // proper noun or as an age route lexeme, and both are screened: the lexemes in
  // T3, the proper nouns here.
  const allowed = allowedFrom({
    derived: [
      PROTAGONIST,
      ...activeRoleTitles(),
      ...departments(),
      ...activeRows().map(fullName),
      ...candidateNames(),
    ],
    furniturePhrases: FURNITURE_PHRASES,
    furnitureWords: FURNITURE_WORDS,
  });
  for (const id of DRAFTED_IDS) {
    for (const { name, text } of allMarkdown(id)) {
      assert.deepEqual(unscreenedPhrases(text, allowed), [], `unscreened capitalized phrase(s) in ${id}/${name}`);
      assert.deepEqual(unscreenedWords(text, allowed), [], `unscreened capitalized word(s) in ${id}/${name}`);
    }
  }
});

test("no departed roster employee and no other canon company is named in either C2 set", () => {
  const rows = roster();
  const live = new Set(rows.filter((r) => r.employment_status === "active").map(fullName));
  const departed = [...new Set(rows.filter((r) => r.employment_status !== "active").map(fullName))]
    .filter((name) => !live.has(name));
  assert.ok(departed.length > 0, "the roster carries no departed employees, so this screen proves nothing");
  for (const id of DRAFTED_IDS) {
    for (const { name, text } of allSources(id)) {
      for (const person of departed) {
        assert.ok(!text.includes(person), `${id}/${name} names ${person}, who has left the company`);
      }
      for (const company of canon.values()) {
        if (company.name === PROTAGONIST) continue;
        assert.ok(!text.includes(company.name), `${id}/${name} names canon company "${company.name}"`);
      }
    }
  }
});

test("HR-02 sits in its word bands and no prior employer or institution is named", () => {
  for (const { name, text } of resumes()) {
    const count = words(text);
    assert.ok(count >= 250 && count <= 400, `${name} runs ${count} words, outside the 250 to 400 band`);
    const order = [...sections(text).keys()];
    assert.equal(order[0], "Summary", `${name}: the first section is ${order[0]}, not the summary`);
    assert.equal(order[1], "Experience", `${name}: the second section is ${order[1]}, not the experience`);
    assert.ok(order.length <= 4, `${name} carries ${order.length} sections, more than the four the form allows`);
    assert.deepEqual(
      order.filter((s) => !["Summary", "Experience", "Education", "Certifications"].includes(s)), [],
      `${name} carries a section the form does not name`
    );
    const summary = words(sections(text).get("Summary"));
    assert.ok(summary >= 40 && summary <= 80, `${name}: the summary runs ${summary} words, outside the 40 to 80 band`);
  }
  // The one company the corpus names is the protagonist, and it names it nowhere,
  // because these are the candidates' own documents. The proper-noun screen in
  // T12 is what makes the absence of employer names mechanical rather than a
  // matter of trust: an employer or an institution would be capitalized.
  const named = resumes().filter(({ text }) => text.includes(PROTAGONIST));
  assert.equal(named.length, 0, "a resume names the hiring company, which a candidate's own document would not");
});
