// HR-01 role-requisition-library, HR-03 interview-transcript-corpus and HR-09
// manager-notes-and-review-draft-pair: the structural screen over the three
// drafted artifact sets of people-hr cluster 1.
//
// The operations C1 screen (tests/drafted/ops-c1-drafted-screen.test.js) is the
// house style, and through it the finance D5 screen: documents are read lazily
// inside each test, the CORE-04 roster is generated in-test rather than read off
// disk, and every allowed capitalized string except a short furniture list is
// derived from canon or from generated bytes. Names are allowed here exactly
// when they resolve to an ACTIVE roster row, so the real-name screen is a
// parse-and-join: every printed (name, role title) pair has to land on a live
// row with a byte-equal `role_title`, comma included.
//
// Two things extend that pattern.
//
// First, this cluster ships a JSON source beside its markdown. `validate` and
// `build-docx` read only `.md`, so the register's structure is asserted here or
// nowhere. The register is therefore parsed and joined to the generated roster
// in the same way the markdown is.
//
// Second, four closed lists live in the spec entries rather than in this file,
// and every plant this screen recomputes is recomputed by reading those lists
// out of `specs/artifact-specs.yaml` and applying them to the committed bytes
// in the test's own code. Nothing here imports a predicate from the documents
// or restates one from the data plan; if the spec sentence and the shipped
// prose ever part company, the count moves and the assertion says so.
//
// What this file deliberately does NOT know: which brief, which claim sentence
// or which review sentence satisfies which rule. Those are per-instance answer
// keys, and answer keys do not live in this repo (canon/companies.md ground
// rules, restated in datagen/README.md). Every assertion below is a shape or a
// cardinality, computed at run time.
import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { loadSpecs } from "../../datagen/src/specLoader.js";
import { loadCanonCompanies } from "../../datagen/src/canon.js";
import { generateArtifact } from "../../datagen/src/engine.js";
import { csvTable, fileByPath } from "../helpers/csv-table.js";
import { allowedFrom, unscreenedPhrases, unscreenedWords } from "../helpers/capitalized-screen.js";
import { moneyMatches } from "../helpers/money-shape.js";

const REPO_ROOT = join(import.meta.dirname, "..", "..");
const specs = loadSpecs(join(REPO_ROOT, "specs", "artifact-specs.yaml"));
const canon = loadCanonCompanies(join(REPO_ROOT, "canon", "companies.md"));

const PROTAGONIST = "Atticus Dundee Inc.";
const DRAFTED_IDS = ["HR-01", "HR-03", "HR-09"];

/** The formats the HR block declares, pinned so a spec edit has to be deliberate. */
const FORMATS = {
  "HR-01": "json + markdown",
  "HR-03": "text",
  "HR-09": "markdown",
};

// --------------------------------------------------------------- file access

const artifactDir = (id) => join(REPO_ROOT, "artifacts", id);

function sourceNames(id, predicate) {
  const dir = artifactDir(id);
  assert.ok(existsSync(dir), `${id} is not authored yet: ${dir} does not exist`);
  return readdirSync(dir).filter(predicate).sort();
}

const markdownNames = (id) => sourceNames(id, (n) => n.endsWith(".md"));
const readSource = (id, name) => readFileSync(join(artifactDir(id), name), "utf8");
const allMarkdown = (id) => markdownNames(id).map((name) => ({ name, text: readSource(id, name) }));

const register = () => JSON.parse(readSource("HR-01", "role-requisition-register.json"));

const words = (text) => text.split(/\s+/).filter(Boolean).length;

// -------------------------------------------------------- the roster, in-test

/** The CORE-04 roster, generated rather than read off disk. */
const roster = () => csvTable(
  fileByPath(generateArtifact(specs.byId.get("CORE-04"), canon), "people-roster.csv").content
).rows;

const fullName = (r) => `${r.first_name} ${r.last_name}`;
const activeRows = () => roster().filter((r) => r.employment_status === "active");
const byId = () => new Map(roster().map((r) => [r.employee_id, r]));
const activeRoleTitles = () => [...new Set(activeRows().map((r) => r.role_title))];
const departments = () => [...new Set(activeRows().map((r) => r.department))];

/**
 * The one active row printed as these bytes. An ambiguous join is a failure of
 * its own: a document naming a person two live rows answer to has identified
 * nobody.
 */
function resolveActive(name, roleTitle, context, rows) {
  const matches = rows.filter((r) => fullName(r) === name && r.role_title === roleTitle);
  assert.equal(
    matches.length, 1,
    `${context}: "${name} (${roleTitle})" resolves to ${matches.length} active roster rows, expected exactly 1`
  );
  return matches[0];
}

// ------------------------------------------- the closed lists, read from spec

const featureMatching = (id, pattern) => {
  const found = specs.byId.get(id).planted_features.filter((f) => pattern.test(f));
  assert.equal(found.length, 1, `${id}: expected exactly one planted feature matching ${pattern}`);
  return found[0];
};

const splitList = (text) => text.split(/,\s*/).map((s) => s.trim()).filter(Boolean);

/** HR-01's exclusion phrases, as {phrase, class}, parsed out of the spec sentence. */
function exclusionPhrases() {
  const feature = featureMatching("HR-01", /^exclusion_phrase_list is the closed rule set/);
  const out = [];
  for (const m of feature.matchAll(/\b(age|national_origin|disability|family_status): ([^.]+)(?:\.|$)/g)) {
    for (const phrase of splitList(m[2])) out.push({ phrase, class: m[1] });
  }
  assert.ok(out.length >= 8, "the spec sentence did not yield an exclusion phrase list");
  return out;
}

/** HR-03's closed technology vocabulary, parsed out of the spec sentence. */
function technologyVocabulary() {
  const feature = featureMatching("HR-03", /^technology_vocabulary is the closed list/);
  const list = splitList(feature.slice(feature.lastIndexOf(": ") + 2));
  assert.ok(list.length >= 6, "the spec sentence did not yield a technology vocabulary");
  return list;
}

/** HR-09's four closed lists, parsed out of the one spec sentence that carries them. */
function hr09Lists() {
  const feature = featureMatching("HR-09", /^the four closed lists the draft is read against/);
  const named = (name) => {
    const m = feature.match(new RegExp(`${name} is (?:the twelve named pieces of work the log discusses: )?([^.]+)`));
    assert.ok(m, `the spec sentence carries no ${name} list`);
    return splitList(m[1]);
  };
  const lists = {
    frequencyAdverbs: named("frequency_adverbs"),
    deadlineLexemes: named("deadline_lexemes"),
    characterPhrases: named("character_claim_phrases"),
    logDeliverables: named("log_deliverables"),
  };
  for (const [name, list] of Object.entries(lists)) {
    assert.ok(list.length >= 5, `${name} came out of the spec with only ${list.length} entries`);
  }
  return lists;
}

const escapeRegExp = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
/** Word-bounded membership, so "late" is not confirmed by "escalate" or "related". */
const carries = (text, token) => new RegExp(`\\b${escapeRegExp(token)}\\b`, "i").test(text);
const tokensIn = (text, list) => list.filter((t) => carries(text, t));

// -------------------------------------------------------------- HR-01 parsers

/** `- Key: value` metadata lines, in order, value possibly empty. */
function metadata(text) {
  const out = new Map();
  for (const line of text.split("\n")) {
    const m = line.match(/^- ([A-Z][A-Za-z ]*?):(?: (.*))?$/);
    if (!m) continue;
    out.set(m[1], (m[2] ?? "").trim());
  }
  return out;
}

/** `## Heading` sections of a markdown source, as heading -> body. */
function sections(text) {
  const out = new Map();
  for (const chunk of text.split(/^## /m).slice(1)) {
    const nl = chunk.indexOf("\n");
    out.set(chunk.slice(0, nl).trim(), chunk.slice(nl + 1).trim());
  }
  return out;
}

const briefNames = () => sourceNames("HR-01", (n) => n.startsWith("intake-brief-") && n.endsWith(".md"));

/** Every brief, keyed by the requisition id its own metadata prints. */
function briefs() {
  const out = new Map();
  for (const name of briefNames()) {
    const text = readSource("HR-01", name);
    const meta = metadata(text);
    const id = meta.get("Requisition ID");
    assert.ok(id, `${name}: the metadata block carries no requisition id`);
    assert.ok(!out.has(id), `${name}: two briefs print the same requisition id`);
    out.set(id, { name, text, meta, sections: sections(text) });
  }
  return out;
}

// -------------------------------------------------------------- HR-03 parsers

/** `[HH:MM:SS] First Last (Role Title): utterance`, the one grammar the corpus uses. */
const CUE = /^\[(\d{2}):(\d{2}):(\d{2})\] (.+?) \(([^()]+)\): (.+)$/;
const NAME_SHAPE = /^[A-Z][A-Za-z'-]+ [A-Z][A-Za-z'-]+$/;
/** Any printed "First Last (Role)" pair, wherever it appears: cue, metadata or prose. */
const PRINTED_PAIR = /\b([A-Z][A-Za-z'-]+ [A-Z][A-Za-z'-]+) \(([^()]+)\)/g;

/**
 * Every cue in a transcript, full-parsed. A line that opens with "[" and does
 * not parse is reported rather than skipped: a cue the parser cannot see is a
 * turn no downstream join can see either.
 */
function cues(text, label) {
  const out = [];
  for (const [i, line] of text.split("\n").entries()) {
    if (!line.startsWith("[")) continue;
    const m = line.match(CUE);
    assert.ok(m, `${label} line ${i + 1} opens a cue but does not parse under the grammar: ${line}`);
    const [, hh, mm, ss, name, role, utterance] = m;
    out.push({
      line: i + 1,
      seconds: Number(hh) * 3600 + Number(mm) * 60 + Number(ss),
      stamp: `${hh}:${mm}:${ss}`,
      name,
      role,
      utterance,
    });
  }
  return out;
}

const transcriptNames = () => sourceNames("HR-03", (n) => n.startsWith("interview-transcript-") && n.endsWith(".md"));
const feedbackNames = () => sourceNames("HR-03", (n) => n.startsWith("draft-feedback-") && n.endsWith(".md"));
const pairedTranscript = (feedbackName) => feedbackName.replace("draft-feedback-", "interview-transcript-");

// Every draft feedback file follows the same metadata order every time: the
// candidate, the requisition, the date, the interviewer and the source
// transcript. Pinned as a key set so a file that grows or drops a line fails
// here rather than shipping unseen.
const FEEDBACK_METADATA_KEYS = ["Candidate ID", "Candidate name", "Requisition ID", "Date", "Interviewer", "Source transcript"];

/** The numbered claim sentences of a feedback file's evidence section. */
function claimSentences(text, label) {
  const evidence = sections(text).get("Evidence");
  assert.ok(evidence, `${label}: no evidence section`);
  const out = [];
  for (const line of evidence.split("\n")) {
    const m = line.match(/^(\d+)\.\s+(.+)$/);
    if (m) out.push({ index: Number(m[1]), sentence: m[2].trim() });
  }
  return out;
}

// The number words a quantified experience claim may use, in the screen's own
// code rather than imported from anywhere. A claim may write the integer either
// way, and the anchor test accepts either form on the transcript side, so
// "four years" is anchored by a candidate who said "About four" or "About 4".
const NUMBER_WORDS = {
  one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7, eight: 8,
  nine: 9, ten: 10, eleven: 11, twelve: 12, fifteen: 15, twenty: 20,
};
const YEAR_PHRASE = new RegExp(
  `\\b(\\d+|${Object.keys(NUMBER_WORDS).join("|")})\\s+(?:year|years)\\b`, "gi"
);

/** Every (integer, technology) pair a sentence asserts as an experience claim. */
function quantifiedClaims(sentence, vocabulary) {
  const lower = sentence.toLowerCase();
  const out = [];
  for (const m of sentence.matchAll(YEAR_PHRASE)) {
    const raw = m[1].toLowerCase();
    const value = NUMBER_WORDS[raw] ?? Number(raw);
    for (const tech of vocabulary) if (lower.includes(tech)) out.push({ value, tech });
  }
  return out;
}

/** Does the paired transcript body carry both halves of the claim? */
function claimIsAnchored(claim, transcriptBody) {
  const lower = transcriptBody.toLowerCase();
  const forms = [
    String(claim.value),
    ...Object.entries(NUMBER_WORDS).filter(([, v]) => v === claim.value).map(([w]) => w),
  ];
  return forms.some((f) => carries(lower, f)) && lower.includes(claim.tech);
}

// -------------------------------------------------------------- HR-09 parsers

/** `### YYYY-MM-DD` entries of the one to one log, in file order. */
function logEntries(text) {
  return text.split(/^### /m).slice(1).map((chunk) => {
    const nl = chunk.indexOf("\n");
    return { date: chunk.slice(0, nl).trim(), body: chunk.slice(nl + 1).trim() };
  });
}

/** Every sentence of the review draft's four sections, in file order. */
function reviewSentences(text) {
  const out = [];
  for (const body of sections(text).values()) {
    for (const sentence of body.split(/(?<=[.?!])\s+/)) {
      const trimmed = sentence.trim();
      if (trimmed) out.push(trimmed);
    }
  }
  return out;
}

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];
const ISO_DATE = /\b\d{4}-\d{2}-\d{2}\b/;
const LONG_DATE = new RegExp(`\\b\\d{1,2} (?:${MONTHS.join("|")}) \\d{4}\\b`);
const isDated = (s) => ISO_DATE.test(s) || LONG_DATE.test(s);

const logFile = () => readSource("HR-09", "one-to-one-log.md");
const reviewFile = () => readSource("HR-09", "performance-review-draft.md");

// ------------------------------------------------------------------ furniture

// The one place a typed list is allowed. Each entry is here because a document
// has to say it and the pack ships it nowhere. Everything else on the allowed
// side is derived below from canon, from the generated roster, or from the
// register's own candidate names.
const FURNITURE_PHRASES = [
  "Requisition ID",  // the metadata label every brief and every transcript prints
  "Candidate ID",    // the same, on the interview corpus
];
const FURNITURE_WORDS = [
  "I",        // the first-person pronoun, in a transcript and in a manager's notes
  "ID",       // the second word of both labels above
  "IC",       // the CORE-04 `level` value, printed on a brief's metadata line
  "English",  // carried by one of the spec's exclusion phrases
  ...MONTHS,  // long-form dates in running prose, which the house style requires
];

// ------------------------------------------------------------- the freeze gate

test("the C1 freeze gate is exactly three drafted artifact sets, each with a spec that says so", () => {
  for (const id of DRAFTED_IDS) {
    const spec = specs.byId.get(id);
    assert.ok(spec, `${id} is not in the spec catalog`);
    assert.equal(spec.generation, "drafted-frozen", `${id} is not drafted-frozen`);
    assert.equal(spec.format, FORMATS[id], `${id} format drifted from the HR block`);
    assert.equal(spec.columns, undefined, `${id} is prose and carries no columns`);
    assert.ok(spec.period, `${id} states no period, so no window is pinned`);
    assert.ok(spec.planted_features.length > 0, `${id} states no planted features for validate to check`);
    assert.deepEqual(spec.canon_entities, ["co-002"], `${id} names a canon entity other than the protagonist`);
  }
});

// ------------------------------------------------------------------ HR-01

test("HR-01: the register's key order, its closed lists and its eight requisitions", () => {
  const reg = register();
  assert.deepEqual(
    Object.keys(reg),
    ["library_id", "as_of", "source_artifact", "exclusion_phrase_list", "competency_library", "requisitions"],
    "the register's top-level key order has drifted from the documented one"
  );
  assert.match(reg.as_of, ISO_DATE, "as_of is not an ISO date");
  assert.equal(reg.as_of, "2026-04-03", "as_of has drifted from the frozen register date");

  const spec = specs.byId.get("HR-01");
  assert.ok(reg.as_of <= spec.period.end && reg.as_of >= spec.period.start, "as_of sits outside the spec period");

  // The exclusion list on disk is the list the spec publishes, phrase for phrase.
  const fromSpec = exclusionPhrases();
  assert.deepEqual(
    reg.exclusion_phrase_list.map((e) => `${e.class}/${e.phrase}`).sort(),
    fromSpec.map((e) => `${e.class}/${e.phrase}`).sort(),
    "the register's exclusion phrase list and the spec's have parted company"
  );
  const classes = ["age", "national_origin", "disability", "family_status"];
  for (const cls of classes) {
    const inClass = reg.exclusion_phrase_list.filter((e) => e.class === cls);
    assert.ok(inClass.length >= 2, `class ${cls} carries ${inClass.length} phrases, expected at least 2`);
  }
  assert.deepEqual(
    [...new Set(reg.exclusion_phrase_list.map((e) => e.class))].sort(),
    [...classes].sort(),
    "the exclusion list uses a class the four published ones do not cover"
  );
  for (const [phrase, cls] of [["recent graduate", "age"], ["native English speaker", "national_origin"]]) {
    const entry = reg.exclusion_phrase_list.find((e) => e.phrase === phrase);
    assert.ok(entry, `the exclusion list has dropped the phrase the frozen spec already named: ${phrase}`);
    assert.equal(entry.class, cls, `${phrase} is classed ${entry.class}, expected ${cls}`);
  }

  // The competency library, CMP-01 upward with no gaps.
  const lib = reg.competency_library;
  assert.ok(lib.length >= 10 && lib.length <= 14, `the competency library holds ${lib.length}, outside the 10 to 14 band`);
  lib.forEach((c, i) => {
    assert.deepEqual(Object.keys(c), ["competency_id", "name", "definition"], "a competency's key order has drifted");
    assert.equal(c.competency_id, `CMP-${String(i + 1).padStart(2, "0")}`, "the competency ids are not sequential from CMP-01");
    assert.ok(c.name.trim() && c.definition.trim(), `${c.competency_id} carries an empty name or definition`);
  });

  // The requisitions, RQN-2026-0101 upward in file order.
  const reqs = reg.requisitions;
  assert.equal(reqs.length, 8, `the register holds ${reqs.length} requisitions, expected 8`);
  reqs.forEach((r, i) => {
    assert.deepEqual(
      Object.keys(r),
      ["requisition_id", "requisition_title", "department", "level", "status", "openings",
        "opened_date", "target_start_date", "owner_employee_id", "hiring_manager_employee_id",
        "recruiter_employee_id", "employment_type", "competencies", "brief_file"],
      "a requisition's key order has drifted from the documented one"
    );
    assert.equal(r.requisition_id, `RQN-2026-${String(101 + i).padStart(4, "0")}`, "requisition ids are not sequential in file order");
  });
  const statuses = {};
  for (const r of reqs) statuses[r.status] = (statuses[r.status] ?? 0) + 1;
  assert.deepEqual(statuses, { open: 6, on_hold: 1, filled: 1 }, "the status mix has moved");

  const opened = reqs.map((r) => r.opened_date);
  assert.equal(new Set(opened).size, opened.length, "two requisitions were raised on the same day");
  for (const date of opened) {
    assert.ok(
      date >= spec.period.start && date <= "2026-03-20",
      `a requisition was raised on ${date}, outside the raising window`
    );
  }
  const ids = new Set(lib.map((c) => c.competency_id));
  for (const r of reqs) {
    assert.ok(
      r.competencies.length >= 4 && r.competencies.length <= 6,
      `${r.requisition_id} names ${r.competencies.length} competencies, outside the 4 to 6 band`
    );
    for (const c of r.competencies) assert.ok(ids.has(c), `${r.requisition_id} names ${c}, which the library does not carry`);
    assert.equal(new Set(r.competencies).size, r.competencies.length, `${r.requisition_id} repeats a competency`);
    assert.ok(Number.isInteger(r.openings) && r.openings >= 1, `${r.requisition_id} carries a bad openings count`);
  }
});

test("HR-01: every register employee id resolves, and each field rule holds", () => {
  const rows = byId();
  const active = activeRows();
  for (const r of register().requisitions) {
    const owner = rows.get(r.owner_employee_id);
    assert.ok(owner, `${r.requisition_id}: the owner does not resolve to a roster row`);
    assert.equal(owner.department, "People", `${r.requisition_id}: the owner is not a People-department row`);
    assert.ok(
      ["Recruiter", "HR Business Partner"].includes(owner.role_title),
      `${r.requisition_id}: the owner holds ${owner.role_title}, which cannot own a requisition`
    );

    const manager = rows.get(r.hiring_manager_employee_id);
    assert.ok(manager, `${r.requisition_id}: the hiring manager does not resolve to a roster row`);
    assert.equal(manager.employment_status, "active", `${r.requisition_id}: the hiring manager has left the company`);
    assert.equal(manager.department, r.department, `${r.requisition_id}: the hiring manager sits in another department`);
    assert.ok(
      ["Manager", "Director", "VP", "Executive"].includes(manager.level),
      `${r.requisition_id}: the hiring manager is at level ${manager.level}, below Manager`
    );
    assert.notEqual(manager.employee_id, owner.employee_id, `${r.requisition_id}: the hiring manager is also the owner`);

    const recruiter = rows.get(r.recruiter_employee_id);
    assert.ok(recruiter, `${r.requisition_id}: the recruiter does not resolve to a roster row`);
    assert.equal(recruiter.employment_status, "active", `${r.requisition_id}: the recruiter has left the company`);
    assert.equal(recruiter.department, "People", `${r.requisition_id}: the recruiter is not a People-department row`);
    assert.equal(recruiter.role_title, "Recruiter", `${r.requisition_id}: the recruiter holds ${recruiter.role_title}`);

    assert.ok(
      active.some((row) => row.department === r.department && row.level === r.level),
      `${r.requisition_id}: no active roster row carries department ${r.department} at level ${r.level}`
    );
  }
});

test("HR-01: the eight briefs print the register, in six sections, inside the word band", () => {
  const reg = register();
  const map = briefs();
  assert.equal(map.size, 8, `HR-01 ships ${map.size} intake briefs, expected 8`);
  const rows = byId();
  const active = activeRows();

  for (const r of reg.requisitions) {
    const brief = map.get(r.requisition_id);
    assert.ok(brief, `${r.requisition_id} has no intake brief`);
    assert.equal(brief.name, r.brief_file, `${r.requisition_id}: brief_file does not name the sibling that carries it`);

    const count = words(brief.text);
    assert.ok(count >= 350 && count <= 550, `${brief.name} runs ${count} words, outside the 350 to 550 band`);
    assert.deepEqual(
      [...brief.sections.keys()],
      ["Why this role exists", "Requirements", "Nice to have", "Competencies", "Interview loop"],
      `${brief.name}: the section order has drifted`
    );
    const requirements = words(brief.sections.get("Requirements"));
    assert.ok(requirements >= 120 && requirements <= 200, `${brief.name}: requirements run ${requirements} words`);

    // Every metadata line is the register's own value, printed.
    assert.equal(brief.meta.get("Requisition title"), r.requisition_title, `${brief.name}: title differs from the register`);
    assert.equal(brief.meta.get("Department"), r.department, `${brief.name}: department differs from the register`);
    assert.equal(brief.meta.get("Level"), r.level, `${brief.name}: level differs from the register`);
    assert.equal(brief.meta.get("Status"), r.status, `${brief.name}: status differs from the register`);
    assert.equal(brief.meta.get("Openings"), String(r.openings), `${brief.name}: openings differ from the register`);
    assert.equal(brief.meta.get("Date raised"), r.opened_date, `${brief.name}: date raised differs from the register`);
    assert.equal(brief.meta.get("Target start date"), r.target_start_date, `${brief.name}: target start date differs from the register`);

    const manager = rows.get(r.hiring_manager_employee_id);
    assert.equal(
      brief.meta.get("Hiring manager"), `${fullName(manager)} (${manager.role_title})`,
      `${brief.name}: the printed hiring manager is not the register's own row`
    );
    const recruiter = rows.get(r.recruiter_employee_id);
    assert.equal(
      brief.meta.get("Recruiter"), `${fullName(recruiter)} (${recruiter.role_title})`,
      `${brief.name}: the printed recruiter is not the register's own row`
    );
    assert.equal(brief.meta.has("Owner"), false, `${brief.name}: the brief prints an owner, which the metadata list does not carry`);

    // The competency bullets are the register's own ids, in order.
    const bullets = brief.sections.get("Competencies").split("\n")
      .map((l) => l.match(/^- (.+) \((CMP-\d{2})\)$/)).filter(Boolean);
    assert.deepEqual(
      bullets.map((m) => m[2]), r.competencies,
      `${brief.name}: the competency bullets are not the register's own list`
    );
    const named = new Map(reg.competency_library.map((c) => [c.competency_id, c.name]));
    for (const m of bullets) {
      assert.equal(m[1], named.get(m[2]), `${brief.name}: ${m[2]} is printed under a name the library does not carry`);
    }

    // The interview loop names roles and never a person.
    const loop = brief.sections.get("Interview loop");
    const titles = activeRoleTitles();
    const bulletRoles = loop.split("\n").map((l) => l.match(/^- (.+?), [a-z]/)).filter(Boolean).map((m) => m[1]);
    assert.ok(bulletRoles.length >= 3, `${brief.name}: the interview loop lists fewer than three panel members`);
    for (const role of bulletRoles) {
      assert.ok(titles.includes(role), `${brief.name}: the interview loop names "${role}", which no active row holds`);
    }
    for (const row of active) {
      assert.ok(!loop.includes(fullName(row)), `${brief.name}: the interview loop names a person rather than a role`);
    }
  }
});

test("HR-C1-T7: the three HR-01 selections each resolve to 1, on three distinct requisitions", () => {
  const reg = register();
  const map = briefs();
  const rows = byId();
  const list = exclusionPhrases();

  // Arm one. A brief carries an exclusion phrase when its requirements text
  // contains one, lowercased on both sides, and nothing else counts.
  const withPhrases = [];
  const withBothClasses = [];
  for (const r of reg.requisitions) {
    const text = map.get(r.requisition_id).sections.get("Requirements").toLowerCase();
    const hits = list.filter((e) => text.includes(e.phrase.toLowerCase()));
    if (hits.length > 0) withPhrases.push(r.requisition_id);
    const byClass = new Set(hits.map((h) => h.class));
    if (byClass.has("age") && byClass.has("national_origin")) withBothClasses.push(r.requisition_id);
  }
  assert.equal(
    withBothClasses.length, 1,
    `${withBothClasses.length} briefs carry both an age phrase and a national_origin phrase, expected 1`
  );
  assert.equal(
    withPhrases.length, 1,
    `${withPhrases.length} briefs carry any listed phrase at all, expected 1 with the class qualifier dropped`
  );

  // Arm two. The qualifier that does real work: with `open`, one; without it, two.
  const staleOwner = reg.requisitions.filter((r) => rows.get(r.owner_employee_id).employment_status !== "active");
  const openStaleOwner = staleOwner.filter((r) => r.status === "open");
  assert.equal(openStaleOwner.length, 1, `${openStaleOwner.length} open requisitions carry a non-active owner, expected 1`);
  assert.equal(staleOwner.length, 2, `${staleOwner.length} requisitions carry a non-active owner at all, expected 2`);

  // Arm three. An absent required field, in the register and in the brief alike.
  const absentField = [];
  for (const r of reg.requisitions) {
    const printed = map.get(r.requisition_id).meta.get("Target start date");
    if (r.target_start_date === "") {
      assert.equal(printed, "", `${r.requisition_id}: the register is empty and the brief prints a value`);
      absentField.push(r.requisition_id);
      continue;
    }
    assert.match(r.target_start_date, ISO_DATE, `${r.requisition_id}: target start date is neither empty nor an ISO date`);
    assert.ok(r.target_start_date > r.opened_date, `${r.requisition_id}: the target start date precedes the date it was raised`);
  }
  assert.equal(absentField.length, 1, `${absentField.length} requisitions carry an empty target start date, expected 1`);

  const selected = [withBothClasses[0], openStaleOwner[0].requisition_id, absentField[0]];
  assert.equal(new Set(selected).size, 3, "two of the three selections land on the same requisition");
});

// ------------------------------------------------------------------ HR-03

test("HR-03: six transcripts and six paired feedback files on two candidates and one requisition", () => {
  const transcripts = transcriptNames();
  const feedback = feedbackNames();
  assert.equal(transcripts.length, 6, `HR-03 ships ${transcripts.length} transcripts, expected 6`);
  assert.equal(feedback.length, 6, `HR-03 ships ${feedback.length} feedback files, expected 6`);
  assert.deepEqual(
    feedback.map(pairedTranscript), transcripts,
    "a feedback file has no transcript of the same name, so the pairing is not resolvable from the file names"
  );

  const spec = specs.byId.get("HR-03");
  const candidates = new Set();
  const requisitions = new Set();
  for (const name of transcripts) {
    const meta = metadata(readSource("HR-03", name));
    candidates.add(meta.get("Candidate ID"));
    requisitions.add(meta.get("Requisition ID"));
    const date = meta.get("Date");
    assert.ok(
      date >= spec.period.start && date <= spec.period.end,
      `${name} is dated ${date}, outside the interview window`
    );
    assert.match(name, new RegExp(`^interview-transcript-${meta.get("Candidate ID")}-`), `${name}: the file name and the candidate id disagree`);
  }
  assert.deepEqual([...candidates].sort(), ["ca-001", "ca-002"], "the corpus does not carry exactly ca-001 and ca-002");
  assert.equal(requisitions.size, 1, "the corpus spans more than one requisition");

  // The requisition interviewed is an open one, and it carries no HR-01 plant.
  const reg = register();
  const interviewed = reg.requisitions.find((r) => r.requisition_id === [...requisitions][0]);
  assert.ok(interviewed, "the interviewed requisition does not resolve in the HR-01 register");
  assert.equal(interviewed.status, "open", "the interviewed requisition is not open");
  const rows = byId();
  const list = exclusionPhrases();
  const map = briefs();
  const text = map.get(interviewed.requisition_id).sections.get("Requirements").toLowerCase();
  assert.equal(list.filter((e) => text.includes(e.phrase.toLowerCase())).length, 0, "the interviewed requisition also carries the phrase selection");
  assert.equal(rows.get(interviewed.owner_employee_id).employment_status, "active", "the interviewed requisition also carries the owner selection");
  assert.notEqual(interviewed.target_start_date, "", "the interviewed requisition also carries the absent-field selection");

  // Three conversations per candidate, one per panel role, the same roles both times.
  const perCandidate = {};
  for (const name of transcripts) {
    const m = name.match(/^interview-transcript-(ca-\d{3})-(.+)\.md$/);
    assert.ok(m, `${name}: the file name does not follow the candidate and panel-role convention`);
    (perCandidate[m[1]] ??= []).push(m[2]);
  }
  for (const [candidate, panels] of Object.entries(perCandidate)) {
    assert.equal(panels.length, 3, `${candidate} has ${panels.length} panel conversations, expected 3`);
    assert.equal(new Set(panels).size, 3, `${candidate} carries the same panel role twice`);
  }
});

test("HR-03: every cue parses, timestamps never run backwards, and the bands hold", () => {
  const spec = specs.byId.get("HR-03");
  const active = activeRows();
  const candidateNames = new Set();
  let recruiterSeen = false;

  for (const name of transcriptNames()) {
    const text = readSource("HR-03", name);
    const meta = metadata(text);
    const parsed = cues(text, name);
    assert.ok(parsed.length >= 35 && parsed.length <= 55, `${name} carries ${parsed.length} cues, outside the 35 to 55 band`);
    const count = words(text);
    assert.ok(count >= 900 && count <= 1400, `${name} runs ${count} words, outside the 900 to 1,400 band`);
    for (let i = 1; i < parsed.length; i += 1) {
      assert.ok(
        parsed[i].seconds >= parsed[i - 1].seconds,
        `${name} line ${parsed[i].line}: timestamp ${parsed[i].stamp} runs backwards from ${parsed[i - 1].stamp}`
      );
    }
    const candidateName = meta.get("Candidate name");
    candidateNames.add(candidateName);
    const interviewer = meta.get("Interviewer").match(/^(.+) \(([^()]+)\)$/);
    assert.ok(interviewer, `${name}: the interviewer line is not "Name (Role Title)"`);
    const row = resolveActive(interviewer[1], interviewer[2], `${name} interviewer`, active);
    if (row.department === "People" && row.role_title === "Recruiter") recruiterSeen = true;
    assert.equal(meta.get("Organization"), PROTAGONIST, `${name}: the organization line is not the protagonist`);

    const speakers = new Set(parsed.map((c) => `${c.name} (${c.role})`));
    assert.equal(speakers.size, 2, `${name} carries ${speakers.size} distinct speakers, expected the interviewer and the candidate`);
    for (const cue of parsed) {
      assert.match(cue.name, NAME_SHAPE, `${name} line ${cue.line}: "${cue.name}" is not a First Last name`);
      if (cue.name === candidateName) {
        assert.equal(cue.role, "Candidate", `${name} line ${cue.line}: the candidate speaks under another role`);
        continue;
      }
      resolveActive(cue.name, cue.role, `${name} line ${cue.line}`, active);
    }

    // The competencies assessed are HR-01's own, printed under the library's names.
    const reg = register();
    const named = new Map(reg.competency_library.map((c) => [c.competency_id, c.name]));
    const assessed = text.split("- Competencies assessed:")[1].split("\n\n")[0]
      .split("\n").map((l) => l.match(/^\s+- (.+) \((CMP-\d{2})\)$/)).filter(Boolean);
    assert.ok(assessed.length >= 2, `${name}: fewer than two competencies assessed`);
    for (const m of assessed) {
      assert.equal(m[1], named.get(m[2]), `${name}: ${m[2]} is printed under a name the library does not carry`);
      assert.ok(
        reg.requisitions.find((r) => r.requisition_id === meta.get("Requisition ID")).competencies.includes(m[2]),
        `${name}: ${m[2]} is not on the requisition being interviewed`
      );
    }
    assert.ok(spec.planted_features.length > 0);
  }

  assert.ok(recruiterSeen, "no interviewer in the corpus is a People-department Recruiter");
  // The candidate names are the only names the pack does not already carry.
  const rosterNames = new Set(roster().map(fullName));
  const canonText = readFileSync(join(REPO_ROOT, "canon", "people.md"), "utf8");
  for (const name of candidateNames) {
    assert.ok(!rosterNames.has(name), `the candidate name "${name}" collides with a roster row`);
    for (const part of name.split(" ")) {
      assert.ok(
        !roster().some((r) => r.first_name === part || r.last_name === part),
        `the candidate name "${name}" reuses the roster name part "${part}"`
      );
      assert.ok(!canonText.includes(part), `the candidate name "${name}" reuses the canon name part "${part}"`);
    }
  }
});

test("HR-03: each feedback file sits in its band and carries four to seven numbered claims", () => {
  for (const name of feedbackNames()) {
    const text = readSource("HR-03", name);
    const count = words(text);
    assert.ok(count >= 250 && count <= 400, `${name} runs ${count} words, outside the 250 to 400 band`);
    assert.deepEqual(
      [...sections(text).keys()], ["Recommendation", "Evidence"],
      `${name}: the section order has drifted`
    );
    const claims = claimSentences(text, name);
    assert.ok(claims.length >= 4 && claims.length <= 7, `${name} carries ${claims.length} claim sentences, outside the 4 to 7 band`);
    assert.deepEqual(
      claims.map((c) => c.index), claims.map((_, i) => i + 1),
      `${name}: the claim sentences are not numbered from 1 in order`
    );
    const meta = metadata(text);
    assert.deepEqual([...meta.keys()], FEEDBACK_METADATA_KEYS, `${name}: the metadata key set has drifted from the uniform order`);
    assert.equal(meta.get("Source transcript"), pairedTranscript(name), `${name}: the source transcript line does not name its own pair`);
    const transcriptMeta = metadata(readSource("HR-03", pairedTranscript(name)));
    for (const key of ["Candidate ID", "Candidate name", "Requisition ID", "Date", "Interviewer"]) {
      assert.equal(meta.get(key), transcriptMeta.get(key), `${name}: the ${key} line disagrees with its own transcript`);
    }
    // Every experience claim in the file is a numbered claim sentence, so the
    // population below cannot be understated by a claim hidden in the prose.
    const outside = text.split("## Evidence")[0];
    assert.equal((outside.match(/\byears?\b/gi) ?? []).length, 0, `${name}: an experience claim sits outside the evidence section`);
  }
});

test("HR-C1-T8: exactly one quantified experience claim is unanchored, against the stated population", () => {
  const vocabulary = technologyVocabulary();
  let population = 0;
  let unanchored = 0;
  for (const name of feedbackNames()) {
    const text = readSource("HR-03", name);
    const body = cues(readSource("HR-03", pairedTranscript(name)), pairedTranscript(name))
      .map((c) => c.utterance).join("\n");
    for (const claim of claimSentences(text, name)) {
      for (const pair of quantifiedClaims(claim.sentence, vocabulary)) {
        population += 1;
        if (!claimIsAnchored(pair, body)) unanchored += 1;
      }
    }
  }
  assert.equal(population, 7, `the corpus carries ${population} quantified experience claims, expected the stated population of 7`);
  assert.equal(unanchored, 1, `${unanchored} quantified experience claims are unanchored, expected exactly 1`);
});

// ------------------------------------------------------------------ HR-09

test("HR-09: the pair is a member of the qualifying set, and the log sits in its bands", () => {
  const spec = specs.byId.get("HR-09");
  const rows = roster();
  const active = rows.filter((r) => r.employment_status === "active");
  const log = logFile();
  const review = reviewFile();

  for (const [label, text] of [["log", log], ["review draft", review]]) {
    const meta = metadata(text);
    assert.equal(meta.get("Period"), `${spec.period.start} to ${spec.period.end}`, `the ${label} states another period`);
    const manager = meta.get("Manager").match(/^(.+) \(([^()]+)\)$/);
    const report = meta.get("Report").match(/^(.+) \(([^()]+)\)$/);
    assert.ok(manager && report, `the ${label} metadata is not "Name (Role Title)"`);
    const managerRow = resolveActive(manager[1], manager[2], `the ${label} manager`, active);
    const reportRow = resolveActive(report[1], report[2], `the ${label} report`, active);

    // Membership of the qualifying set, re-derived. The identity inside the set
    // is the drafter's, and this screen never asks which member it is.
    assert.equal(managerRow.department, "People", `the ${label} manager is not a People-department row`);
    assert.equal(managerRow.role_title, "People Manager", `the ${label} manager does not hold People Manager`);
    assert.equal(reportRow.department, "People", `the ${label} report is not a People-department row`);
    assert.equal(reportRow.manager_employee_id, managerRow.employee_id, `the ${label} report does not report to the named manager`);
    assert.ok(reportRow.start_date <= spec.period.start, `the ${label} report started after the review period opened`);
    for (const row of [managerRow, reportRow]) {
      assert.ok(!["EMP-0001", "EMP-0002"].includes(row.employee_id), `the ${label} pair reaches the top of the org tree`);
    }
    const qualifying = active.filter((r) => (
      r.department === "People"
      && r.manager_employee_id === managerRow.employee_id
      && r.start_date <= spec.period.start
      && !["EMP-0001", "EMP-0002"].includes(r.employee_id)
    ));
    assert.ok(qualifying.length > 0, "the qualifying set of reports is empty, so the rule selects nothing");
    assert.ok(
      qualifying.some((r) => r.employee_id === reportRow.employee_id),
      `the ${label} report is not a member of the set the rule selects`
    );
  }

  const entries = logEntries(log);
  assert.equal(entries.length, 12, `the log carries ${entries.length} entries, expected 12`);
  entries.forEach((e, i) => {
    assert.match(e.date, ISO_DATE, `log entry ${i + 1} is not headed by an ISO date`);
    assert.ok(e.date >= spec.period.start && e.date <= spec.period.end, `log entry ${i + 1} is dated outside the period`);
    if (i > 0) assert.ok(e.date > entries[i - 1].date, `log entry ${i + 1} is dated before the entry above it`);
    const count = words(e.body);
    assert.ok(count >= 80 && count <= 150, `log entry ${i + 1} runs ${count} words, outside the 80 to 150 band`);
  });

  const sentences = reviewSentences(review);
  assert.ok(sentences.length >= 14 && sentences.length <= 18, `the review draft carries ${sentences.length} sentences, outside the 14 to 18 band`);
  assert.deepEqual(
    [...sections(review).keys()],
    ["Summary", "What went well", "Where to improve", "Goals for the next period"],
    "the review draft's section order has drifted"
  );

  // Every deliverable the spec publishes is a deliverable the log actually names.
  const { logDeliverables } = hr09Lists();
  const lower = log.toLowerCase();
  for (const name of logDeliverables) {
    assert.ok(lower.includes(name), `the log never names the published deliverable "${name}"`);
  }
});

test("HR-C1-T9: the two review selections each resolve to 1, on two different sentences", () => {
  const { frequencyAdverbs, deadlineLexemes, characterPhrases, logDeliverables } = hr09Lists();
  const log = logFile();
  const entries = logEntries(log);

  // The absence half of the frequency selection: no entry anywhere carries a
  // deadline lexeme, which is what leaves the draft sentence unsupported.
  const entriesWithLexeme = entries.filter((e) => tokensIn(e.body, deadlineLexemes).length > 0);
  assert.equal(entriesWithLexeme.length, 0, `${entriesWithLexeme.length} log entries carry a deadline lexeme, expected 0`);

  const sentences = reviewSentences(reviewFile());
  const frequencySelected = [];
  const characterSelected = [];
  const deadlinePopulation = [];
  const characterPopulation = [];
  sentences.forEach((sentence, index) => {
    const adverbs = tokensIn(sentence, frequencyAdverbs);
    const lexemes = tokensIn(sentence, deadlineLexemes);
    const character = tokensIn(sentence, characterPhrases);
    const named = logDeliverables.filter((d) => sentence.toLowerCase().includes(d));
    if (lexemes.length > 0) deadlinePopulation.push(index);
    if (character.length > 0) characterPopulation.push(index);
    if (adverbs.length > 0 && lexemes.length > 0) frequencySelected.push(index);
    if (character.length > 0 && !isDated(sentence) && named.length === 0) characterSelected.push(index);
  });

  assert.equal(
    frequencySelected.length, 1,
    `${frequencySelected.length} draft sentences pair a frequency adverb with a deadline lexeme, expected 1`
  );
  assert.equal(deadlinePopulation.length, 3, `${deadlinePopulation.length} draft sentences carry a deadline lexeme at all, expected the stated population of 3`);
  assert.equal(
    characterSelected.length, 1,
    `${characterSelected.length} draft sentences carry an unsupported character phrase, expected 1`
  );
  assert.equal(characterPopulation.length, 2, `${characterPopulation.length} draft sentences carry a character phrase at all, expected the stated population of 2`);
  assert.notEqual(
    frequencySelected[0], characterSelected[0],
    "the two selections land on the same sentence, so one revision would close both"
  );

  // The rest of the deadline population is supported: each names a deliverable
  // and a date that resolve to a log entry, and carries no frequency adverb.
  const headings = new Set(entries.map((e) => e.date));
  const MONTH_INDEX = new Map(MONTHS.map((m, i) => [m, String(i + 1).padStart(2, "0")]));
  for (const index of deadlinePopulation) {
    if (index === frequencySelected[0]) continue;
    const sentence = sentences[index];
    assert.equal(tokensIn(sentence, frequencyAdverbs).length, 0, "a supported deadline sentence also carries a frequency adverb");
    const named = logDeliverables.filter((d) => sentence.toLowerCase().includes(d));
    assert.ok(named.length > 0, "a supported deadline sentence names no deliverable the log carries");
    const long = sentence.match(LONG_DATE);
    assert.ok(long, "a supported deadline sentence carries no long-form date");
    const [day, month, year] = long[0].split(" ");
    const iso = `${year}-${MONTH_INDEX.get(month)}-${day.padStart(2, "0")}`;
    assert.ok(headings.has(iso), `a supported deadline sentence cites ${iso}, which heads no log entry`);
    const entry = entries.find((e) => e.date === iso);
    assert.ok(
      named.some((d) => entry.body.toLowerCase().includes(d)),
      "a supported deadline sentence cites a date whose log entry does not discuss the deliverable it names"
    );
  }
});

// ------------------------------------------------------- HR-C1-T10 and screens

test("HR-C1-T10: every printed name and role title lands on an active roster row", () => {
  const active = activeRows();
  const candidateNames = new Set(
    transcriptNames().map((n) => metadata(readSource("HR-03", n)).get("Candidate name"))
  );
  let pairs = 0;
  for (const id of DRAFTED_IDS) {
    for (const { name, text } of allMarkdown(id)) {
      for (const match of text.matchAll(PRINTED_PAIR)) {
        const [, person, role] = match;
        pairs += 1;
        if (candidateNames.has(person)) {
          assert.equal(role, "Candidate", `${id}/${name}: a candidate is printed under the role "${role}"`);
          continue;
        }
        resolveActive(person, role, `${id}/${name}`, active);
      }
    }
  }
  assert.ok(pairs > 0, "no printed name and role pair was found at all, so this screen proves nothing");
});

test("no departed roster employee is named anywhere in the three sets", () => {
  const rows = roster();
  const live = new Set(rows.filter((r) => r.employment_status === "active").map(fullName));
  const departed = [...new Set(rows.filter((r) => r.employment_status !== "active").map(fullName))]
    .filter((name) => !live.has(name));
  assert.ok(departed.length > 0, "the roster carries no departed employees, so this screen proves nothing");
  for (const id of DRAFTED_IDS) {
    for (const { name, text } of allMarkdown(id)) {
      for (const person of departed) {
        assert.ok(!text.includes(person), `${id}/${name} names ${person}, who has left the company`);
      }
    }
  }
});

test("every capitalized phrase and word is accounted for by the roster, the protagonist or the furniture", () => {
  const candidateNames = [...new Set(
    transcriptNames().map((n) => metadata(readSource("HR-03", n)).get("Candidate name"))
  )];
  const allowed = allowedFrom({
    derived: [
      PROTAGONIST,
      ...activeRoleTitles(),
      ...departments(),
      ...activeRows().map(fullName),
      ...candidateNames,
    ],
    furniturePhrases: FURNITURE_PHRASES,
    furnitureWords: FURNITURE_WORDS,
  });
  for (const id of DRAFTED_IDS) {
    for (const { name, text } of allMarkdown(id)) {
      assert.deepEqual(unscreenedPhrases(text, allowed), [], `unscreened capitalized phrase(s) in ${id}/${name}`);
      assert.deepEqual(unscreenedWords(text, allowed), [], `unscreened capitalized word(s) in ${id}/${name}`);
    }
  }
});

test("no canon company other than the protagonist is named", () => {
  for (const id of DRAFTED_IDS) {
    for (const { name, text } of allMarkdown(id)) {
      for (const company of canon.values()) {
        if (company.name === PROTAGONIST) continue;
        assert.ok(!text.includes(company.name), `${id}/${name} names canon company "${company.name}"`);
      }
    }
  }
});

test("none of the three sets carries an em dash, a money amount or a percentage", () => {
  const sources = [];
  for (const id of DRAFTED_IDS) {
    sources.push(...allMarkdown(id).map(({ name, text }) => [`${id}/${name}`, text]));
  }
  sources.push(["HR-01/role-requisition-register.json", readSource("HR-01", "role-requisition-register.json")]);
  for (const [label, text] of sources) {
    assert.ok(!text.includes("\u2014"), `${label} carries an em dash`);
    assert.deepEqual(moneyMatches(text), [], `${label} states a figure, and this cluster carries no money`);
    assert.deepEqual(text.match(/\d+(\.\d+)?\s?%/g) ?? [], [], `${label} states a percentage`);
  }
});
