// OPS-01 meeting-transcript-with-commitments, OPS-02
// retro-transcript-with-recurring-finding and OPS-03B follow-up-email-thread:
// the structural screen over the three drafted documents of operations
// cluster 1, the path's capture spine.
//
// The finance D5 screen (tests/drafted/fin-d5-drafted-screen.test.js) is the
// house style this file follows: documents are read lazily inside each test,
// the CORE-04 roster is generated in-test rather than read off disk, and every
// allowed capitalized string except the short furniture list is derived from
// canon or from generated bytes.
//
// One thing inverts. The D5 documents satisfied the real-name screen by naming
// nobody; a transcript cannot. So names are allowed here exactly when they
// resolve to an ACTIVE CORE-04 row, and the screen becomes a parse-and-join:
// every cue's (name, role title) pair, every read-back owner, and every email
// header has to land on a live roster row, with the role title byte-equal to
// the roster's own `role_title` (comma included, "VP, Operations").
//
// What this file deliberately does NOT know: which turn is a commitment, which
// turn is the attribution trap, which of the thread's shared topics carries the
// conflicting attribution. Those are per-instance answer keys, and answer keys
// do not live in this repo (canon/companies.md ground rules, restated in
// datagen/README.md). They are certified by the freeze review and re-derived at
// stage A from the private label set. The one plant this file does recompute is
// OPS-02's recurrence, because its selection rule is mechanical: a read-back
// row equals a prior-summary row under lowercase-and-strip-punctuation, and
// anyone applying that rule to the committed bytes gets the same pair, exactly
// as with a dataset plant.
import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { loadSpecs } from "../../datagen/src/specLoader.js";
import { loadCanonCompanies } from "../../datagen/src/canon.js";
import { generateArtifact } from "../../datagen/src/engine.js";
import { csvTable, fileByPath } from "../helpers/csv-table.js";
import { allowedFrom, unscreenedPhrases, unscreenedWords } from "../helpers/capitalized-screen.js";
import { moneyMatches } from "../helpers/money-shape.js";

const REPO_ROOT = join(import.meta.dirname, "..", "..");
const specs = loadSpecs(join(REPO_ROOT, "specs", "artifact-specs.yaml"));
const canon = loadCanonCompanies(join(REPO_ROOT, "canon", "companies.md"));

const PROTAGONIST = "Atticus Dundee Inc.";
const DRAFTED_IDS = ["OPS-01", "OPS-02", "OPS-03B"];

/** The formats the OPS block declares, pinned so a spec edit has to be deliberate. */
const FORMATS = {
  "OPS-01": "text (VTT-style, consent banner header)",
  "OPS-02": "text",
  "OPS-03B": "eml/markdown",
};

/**
 * The normative consent banner, byte-pinned.
 *
 * OPS-01 is where this paragraph is defined for the whole universe (cluster 1
 * data plan, section 2.1). Cluster F's OPS-16 invite template has to carry it
 * byte-identically, and the cross-artifact identity test lands there; here the
 * job is to stop OPS-01's own copy from drifting a comma, because every later
 * match is taken against these bytes.
 */
const CONSENT_BANNER =
  "Consent notice: This meeting is recorded. Recording, transcription, and biometric "
  + "identification are three separate acts; this meeting uses recording and transcription "
  + "only, and biometric identification is disabled. An AI notetaker produces the transcript "
  + "and a summary for attendees. If you do not consent, say so now and the recording stops; "
  + "you may also ask afterward for any remark to be struck from the record.";

function document(id) {
  const spec = specs.byId.get(id);
  const path = join(REPO_ROOT, "artifacts", id, `${spec.name}.md`);
  assert.ok(existsSync(path), `${id} is not authored yet: ${path} does not exist`);
  return readFileSync(path, "utf8");
}

/** The CORE-04 roster, generated rather than read off disk. */
const roster = () => csvTable(
  fileByPath(generateArtifact(specs.byId.get("CORE-04"), canon), "people-roster.csv").content
).rows;

const activeRows = () => roster().filter((r) => r.employment_status === "active");
const fullName = (r) => `${r.first_name} ${r.last_name}`;

/** Every role title an active CORE-04 employee holds. */
const activeRoleTitles = () => [...new Set(activeRows().map((r) => r.role_title))];

/**
 * The one active row whose printed name and role title are these bytes. An
 * ambiguous join is a failure of its own: a transcript that names a person two
 * live rows answer to has not identified anybody.
 */
function resolveActive(name, roleTitle, context) {
  const matches = activeRows().filter((r) => fullName(r) === name && r.role_title === roleTitle);
  assert.equal(
    matches.length, 1,
    `${context}: "${name} (${roleTitle})" resolves to ${matches.length} active roster rows, expected exactly 1`
  );
  return matches[0];
}

// --------------------------------------------------------------- cue grammar

/** `[HH:MM:SS] First Last (Role Title): utterance`, the one grammar both transcripts use. */
const CUE = /^\[(\d{2}):(\d{2}):(\d{2})\] (.+?) \(([^()]+)\): (.+)$/;
const NAME_SHAPE = /^[A-Z][A-Za-z'-]+ [A-Z][A-Za-z'-]+$/;

/**
 * Every cue in a transcript, full-parsed. A line that opens with "[" and does
 * not parse is reported rather than skipped: a cue the parser cannot see is a
 * turn no downstream join can see either.
 */
function cues(text, id) {
  const out = [];
  for (const [i, line] of text.split("\n").entries()) {
    if (!line.startsWith("[")) continue;
    const m = line.match(CUE);
    assert.ok(m, `${id} line ${i + 1} opens a cue but does not parse under the grammar: ${line}`);
    const [, hh, mm, ss, name, role, utterance] = m;
    out.push({
      line: i + 1,
      seconds: Number(hh) * 3600 + Number(mm) * 60 + Number(ss),
      stamp: `${hh}:${mm}:${ss}`,
      name,
      role,
      utterance,
    });
  }
  return out;
}

// ------------------------------------------------------------- OPS-02 blocks

const between = (text, start, end) => {
  const after = text.split(start);
  assert.equal(after.length, 2, `expected exactly one "${start}" heading`);
  return end ? after[1].split(end)[0] : after[1];
};

/** The embedded prior-retro summary's `finding text | status` rows. */
function priorFindings(text) {
  const block = between(text, "## Prior retro summary", "## Session notes");
  const rows = [];
  for (const line of block.split("\n")) {
    if (!line.trim().startsWith("|")) continue;
    const cells = line.split("|").slice(1, -1).map((c) => c.trim());
    if (cells.length !== 2) continue;
    if (cells[0] === "finding text" || /^-+$/.test(cells[0])) continue;
    rows.push({ finding: cells[0], status: cells[1] });
  }
  return { block, rows };
}

/** The facilitator read-back: a numbered finding then its own `owner:` line. */
function readBackFindings(text) {
  const block = between(text, "## Read-back", "## Close");
  const lines = block.split("\n");
  const rows = [];
  for (const [i, line] of lines.entries()) {
    const m = line.match(/^(\d+)\.\s+(.+)$/);
    if (!m) continue;
    const owner = (lines[i + 1] ?? "").match(/^\s+owner:\s?(.*)$/);
    assert.ok(owner, `read-back item ${m[1]} carries no owner: line`);
    rows.push({ index: Number(m[1]), finding: m[2].trim(), owner: owner[1].trim() });
  }
  return rows;
}

/** Lowercase, drop punctuation, collapse whitespace. The C2-P2 rule, and nothing more. */
const normalizeFinding = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();

/** The OPS-02 metadata block: the `- Facilitator: First Last (Role Title)` line and the `- Attendees:` list beneath it. */
function retroMetadata(text) {
  // Scoped to the header block, the way the retro-date arm is: the prior-retro
  // summary carries its own - Facilitator: line, and an unanchored match could
  // silently drift to validating that one instead (re-review N1).
  const head = text.split("## Prior retro summary")[0];
  const facilitator = head.match(/^- Facilitator: (.+?) \(([^()]+)\)$/m);
  assert.ok(facilitator, "OPS-02 metadata carries no - Facilitator: line");
  const attendeesBlock = between(text, "- Attendees:", "\n\n");
  const attendees = [];
  for (const line of attendeesBlock.split("\n")) {
    const m = line.match(/^\s+- (.+?) \(([^()]+)\)$/);
    if (!m) continue;
    attendees.push({ name: m[1], role: m[2] });
  }
  return { facilitator: { name: facilitator[1], role: facilitator[2] }, attendees };
}

// ------------------------------------------------------------ OPS-03B blocks

const ADDRESS = /^(.+?) <([^<>]+)>$/;

/** `Name <email>` pairs out of a From or To header. */
function addresses(headerValue, id) {
  return headerValue.split(/>\s*,\s*/).map((raw, i, all) => {
    const text = i === all.length - 1 ? raw.trim() : `${raw.trim()}>`;
    const m = text.match(ADDRESS);
    assert.ok(m, `${id}: address "${text}" is not "Name <email>"`);
    return { name: m[1].trim(), email: m[2].trim() };
  });
}

function emailMessages(text) {
  return text.split(/^## Message /m).slice(1).map((block) => {
    const lines = block.split("\n");
    const number = Number(lines[0].trim());
    const headers = {};
    let i = 1;
    for (; i < lines.length; i += 1) {
      const m = lines[i].match(/^([A-Za-z-]+):\s(.*)$/);
      if (!m) break;
      headers[m[1]] = m[2];
    }
    return { number, headers, body: lines.slice(i).join("\n") };
  });
}

// ------------------------------------------------------------------ furniture

// The one place a typed list is allowed. Each entry is here because a document
// has to say it and the pack ships it nowhere: the first-person pronoun, the
// two words of the consent banner's "An AI notetaker", and the only month name
// the three documents use. Every other allowed capital is derived below from
// canon or from the generated roster.
const FURNITURE_WORDS = ["I", "An", "AI", "March"];
const FURNITURE_PHRASES = [];

// ------------------------------------------------------------- the freeze gate

test("the C1 freeze gate is exactly three drafted documents, each with a spec that says so", () => {
  for (const id of DRAFTED_IDS) {
    const spec = specs.byId.get(id);
    assert.ok(spec, `${id} is not in the spec catalog`);
    assert.equal(spec.generation, "drafted-frozen", `${id} is not drafted-frozen`);
    assert.equal(spec.format, FORMATS[id], `${id} format drifted from the OPS block`);
    assert.equal(spec.columns, undefined, `${id} is prose and carries no columns`);
    assert.ok(spec.planted_features.length > 0, `${id} states no planted features for validate to check`);
    assert.deepEqual(spec.canon_entities, ["co-002"], `${id} names a canon entity other than the protagonist`);
  }
});

// ----------------------------------------------------------------- OPS-01

test("OPS-01: the consent banner is byte-equal to the pinned paragraph and sits before the first cue", () => {
  const text = document("OPS-01");
  const paragraphs = text.split("\n\n").map((p) => p.trim());
  const banners = paragraphs.filter((p) => p.startsWith("Consent notice:"));
  assert.equal(banners.length, 1, "OPS-01 carries more than one consent notice paragraph");
  assert.equal(
    banners[0], CONSENT_BANNER,
    "OPS-01's consent banner has drifted from the normative bytes cluster F must later match"
  );
  const bannerAt = text.indexOf(CONSENT_BANNER);
  const firstCueAt = text.search(/^\[\d{2}:\d{2}:\d{2}\]/m);
  assert.ok(bannerAt >= 0 && firstCueAt >= 0);
  assert.ok(bannerAt < firstCueAt, "the consent banner does not sit before the first cue");
});

test("OPS-01: every cue parses, timestamps are monotonic, and the meeting is dated 2026-03-10", () => {
  const text = document("OPS-01");
  const parsed = cues(text, "OPS-01");
  assert.ok(
    parsed.length >= 60 && parsed.length <= 90,
    `OPS-01 carries ${parsed.length} cues, outside the 60 to 90 band`
  );
  for (const cue of parsed) {
    assert.match(cue.name, NAME_SHAPE, `OPS-01 line ${cue.line}: "${cue.name}" is not a First Last name`);
  }
  for (let i = 1; i < parsed.length; i += 1) {
    assert.ok(
      parsed[i].seconds >= parsed[i - 1].seconds,
      `OPS-01 line ${parsed[i].line}: timestamp ${parsed[i].stamp} runs backwards from ${parsed[i - 1].stamp}`
    );
  }
  const span = parsed[parsed.length - 1].seconds - parsed[0].seconds;
  assert.ok(span > 30 * 60 && span < 60 * 60, `OPS-01 spans ${span} seconds, not a meeting-length window`);
  assert.match(text, /^- Date: 2026-03-10$/m, "OPS-01 metadata does not carry Date: 2026-03-10");
});

test("OPS-01: exactly seven active speakers, five Operations, one Product, one Engineering", () => {
  const parsed = cues(document("OPS-01"), "OPS-01");
  const speakers = new Map();
  for (const cue of parsed) {
    const key = `${cue.name} (${cue.role})`;
    if (speakers.has(key)) {
      assert.equal(
        speakers.get(key).role, cue.role,
        `OPS-01 line ${cue.line}: ${cue.name} speaks under two role titles`
      );
      continue;
    }
    const row = resolveActive(cue.name, cue.role, `OPS-01 line ${cue.line}`);
    speakers.set(key, { name: cue.name, role: cue.role, department: row.department });
  }
  const byName = new Set([...speakers.values()].map((s) => s.name));
  assert.equal(byName.size, speakers.size, "OPS-01 prints one speaker under two names");
  assert.equal(speakers.size, 7, `OPS-01 has ${speakers.size} distinct speakers, expected 7`);
  const departments = {};
  for (const s of speakers.values()) departments[s.department] = (departments[s.department] ?? 0) + 1;
  assert.deepEqual(departments, { Operations: 5, Product: 1, Engineering: 1 });
});

// ----------------------------------------------------------------- OPS-02

test("OPS-02: the prior summary and the read-back parse to their stated cardinalities", () => {
  const text = document("OPS-02");
  const { block, rows } = priorFindings(text);
  assert.ok(rows.length >= 4 && rows.length <= 5, `the prior summary carries ${rows.length} findings, expected 4 or 5`);
  for (const row of rows) {
    assert.ok(["resolved", "unresolved"].includes(row.status), `prior summary status "${row.status}" is not a status`);
  }
  const unresolved = rows.filter((r) => r.status === "unresolved");
  assert.equal(unresolved.length, 1, `the prior summary carries ${unresolved.length} unresolved findings, expected 1`);

  const readBack = readBackFindings(text);
  assert.equal(readBack.length, 6, `the read-back carries ${readBack.length} findings, expected 6`);
  assert.deepEqual(readBack.map((r) => r.index), [1, 2, 3, 4, 5, 6], "the read-back is not numbered 1 to 6 in order");
  const blank = readBack.filter((r) => r.owner === "");
  assert.equal(blank.length, 1, `the read-back carries ${blank.length} findings with no owner, expected exactly 1`);

  const priorDate = block.match(/^- Date: (\d{4}-\d{2}-\d{2})$/m);
  assert.ok(priorDate, "the prior summary block carries no Date");
  const head = text.split("## Prior retro summary")[0];
  const retroDate = head.match(/^- Date: (\d{4}-\d{2}-\d{2})$/m);
  assert.ok(retroDate, "the retro metadata carries no Date");
  assert.equal(priorDate[1], "2026-03-13");
  assert.equal(retroDate[1], "2026-03-27");
  assert.ok(priorDate[1] < retroDate[1], "the prior retro does not precede the retro");
  for (const d of [priorDate[1], retroDate[1]]) {
    assert.ok(d.startsWith("2026-03-"), `${d} is outside the operations anchor month`);
  }
});

test("OPS-02: every named owner and every speaker resolves to an active roster row", () => {
  const text = document("OPS-02");
  for (const cue of cues(text, "OPS-02")) {
    assert.match(cue.name, NAME_SHAPE, `OPS-02 line ${cue.line}: "${cue.name}" is not a First Last name`);
    resolveActive(cue.name, cue.role, `OPS-02 line ${cue.line}`);
  }
  const names = new Set(activeRows().map(fullName));
  for (const row of readBackFindings(text)) {
    if (row.owner === "") continue;
    assert.ok(names.has(row.owner), `read-back item ${row.index} names "${row.owner}", not an active roster row`);
  }
  const parsed = cues(text, "OPS-02");
  assert.ok(parsed.length >= 40 && parsed.length <= 60, `OPS-02 carries ${parsed.length} cues, outside the 40 to 60 band`);
  for (let i = 1; i < parsed.length; i += 1) {
    assert.ok(parsed[i].seconds >= parsed[i - 1].seconds, `OPS-02 line ${parsed[i].line}: timestamp runs backwards`);
  }
});

test("OPS-02: the metadata attendee list carries 5 to 6 entries, each an active roster row", () => {
  const { attendees } = retroMetadata(document("OPS-02"));
  assert.ok(
    attendees.length >= 5 && attendees.length <= 6,
    `OPS-02 metadata lists ${attendees.length} attendees, outside the 5 to 6 band`
  );
  for (const attendee of attendees) {
    resolveActive(attendee.name, attendee.role, "OPS-02 metadata attendee list");
  }
});

test("OPS-02: the metadata facilitator resolves to an active roster row holding Operations Manager or Program Manager", () => {
  const { facilitator } = retroMetadata(document("OPS-02"));
  resolveActive(facilitator.name, facilitator.role, "OPS-02 metadata facilitator");
  assert.ok(
    ["Operations Manager", "Program Manager"].includes(facilitator.role),
    `OPS-02 facilitator "${facilitator.name}" holds "${facilitator.role}", expected Operations Manager or Program Manager`
  );
});

test("OPS-02: exactly one read-back finding recurs from the prior summary's unresolved row", () => {
  // The C2-P2 rule, recomputed rather than asserted: normalize both sides the
  // same way and see what collides. Nothing in the file marks the pair, and
  // this test names neither row.
  const text = document("OPS-02");
  const prior = priorFindings(text).rows;
  const readBack = readBackFindings(text);
  const pairs = [];
  for (const back of readBack) {
    for (const before of prior) {
      if (normalizeFinding(back.finding) === normalizeFinding(before.finding)) pairs.push({ back, before });
    }
  }
  assert.equal(pairs.length, 1, `${pairs.length} read-back findings match a prior finding under the normalization, expected 1`);
  assert.equal(pairs[0].before.status, "unresolved", "the recurring finding matches a prior row that was already resolved");
  assert.notEqual(pairs[0].back.owner, "", "the recurring finding is also the finding with no owner");
});

// ----------------------------------------------------------------- OPS-03B

test("OPS-03B: six messages, four active participants, headers that join the roster byte-exactly", () => {
  const text = document("OPS-03B");
  const messages = emailMessages(text);
  assert.equal(messages.length, 6, `the thread carries ${messages.length} messages, expected 6`);
  assert.deepEqual(messages.map((m) => m.number), [1, 2, 3, 4, 5, 6], "the messages are not numbered 1 to 6 in order");

  const byName = new Map(activeRows().map((r) => [fullName(r), r]));
  const participants = new Set();
  for (const message of messages) {
    for (const header of ["From", "To", "Date", "Subject"]) {
      assert.ok(message.headers[header], `message ${message.number} carries no ${header} header`);
    }
    const people = [
      ...addresses(message.headers.From, `message ${message.number} From`),
      ...addresses(message.headers.To, `message ${message.number} To`),
    ];
    for (const person of people) {
      const row = byName.get(person.name);
      assert.ok(row, `message ${message.number} names "${person.name}", not an active roster row`);
      assert.equal(
        person.email, row.email,
        `message ${message.number}: ${person.name} writes from "${person.email}", the roster says "${row.email}"`
      );
      participants.add(person.name);
    }
    assert.equal(
      addresses(message.headers.From, "From").length, 1,
      `message ${message.number} has more than one sender`
    );
  }
  assert.equal(participants.size, 4, `the thread has ${participants.size} participants, expected 4`);
});

test("OPS-03B: dates sit inside the follow-up window and never run backwards", () => {
  const messages = emailMessages(document("OPS-03B"));
  const dates = messages.map((m) => m.headers.Date);
  for (const [i, date] of dates.entries()) {
    assert.match(date, /^\d{4}-\d{2}-\d{2}$/, `message ${i + 1} Date is not an ISO date`);
    assert.ok(date >= "2026-03-11" && date <= "2026-03-13", `message ${i + 1} is dated ${date}, outside the thread window`);
    if (i > 0) assert.ok(date >= dates[i - 1], `message ${i + 1} is dated before message ${i}`);
  }
});

test("OPS-03B: the subject is byte-stable and carries the meeting date", () => {
  const text = document("OPS-03B");
  const messages = emailMessages(text);
  const base = messages[0].headers.Subject;
  assert.ok(!base.startsWith("Re: "), "the opening message already carries a Re: prefix");
  for (const message of messages.slice(1)) {
    assert.equal(
      message.headers.Subject, `Re: ${base}`,
      `message ${message.number} retypes the subject instead of replying to it`
    );
  }
  assert.ok(text.includes("2026-03-10"), "the thread never names the meeting it follows up");
});

// ------------------------------------------------------------------ cross-file

test("cross-file: at least three thread participants spoke at the sync, and only OPS-01 carries the banner", () => {
  const speakers = new Set(cues(document("OPS-01"), "OPS-01").map((c) => c.name));
  const participants = new Set();
  for (const message of emailMessages(document("OPS-03B"))) {
    for (const person of [
      ...addresses(message.headers.From, "From"),
      ...addresses(message.headers.To, "To"),
    ]) participants.add(person.name);
  }
  const shared = [...participants].filter((name) => speakers.has(name));
  assert.ok(shared.length >= 3, `only ${shared.length} thread participants spoke at the sync, expected at least 3`);
  for (const id of ["OPS-02", "OPS-03B"]) {
    assert.ok(
      !document(id).includes(CONSENT_BANNER),
      `${id} carries the consent banner, which is single-sourced in OPS-01 until cluster F`
    );
  }
});

// ---------------------------------------------------------------- name screens

test("no departed CORE-04 employee speaks, sends, receives or is named", () => {
  const rows = roster();
  const live = new Set(rows.filter((r) => r.employment_status === "active").map(fullName));
  const departed = [...new Set(
    rows.filter((r) => r.employment_status === "departed").map(fullName)
  )].filter((name) => !live.has(name));
  assert.ok(departed.length > 0, "the roster carries no departed employees, so this screen proves nothing");
  for (const id of DRAFTED_IDS) {
    const text = document(id);
    for (const name of departed) {
      assert.ok(!text.includes(name), `${id} names ${name}, who has left the company`);
    }
  }
});

test("every capitalized phrase and word is accounted for by the roster, the protagonist or the furniture", () => {
  const allowed = allowedFrom({
    derived: [PROTAGONIST, ...activeRoleTitles(), ...activeRows().map(fullName)],
    furniturePhrases: FURNITURE_PHRASES,
    furnitureWords: FURNITURE_WORDS,
  });
  for (const id of DRAFTED_IDS) {
    const text = document(id);
    assert.deepEqual(unscreenedPhrases(text, allowed), [], `unscreened capitalized phrase(s) in ${id}`);
    assert.deepEqual(unscreenedWords(text, allowed), [], `unscreened capitalized word(s) in ${id}`);
  }
});

test("no canon company other than the protagonist is named", () => {
  for (const id of DRAFTED_IDS) {
    const text = document(id);
    for (const company of canon.values()) {
      if (company.name === PROTAGONIST) continue;
      assert.ok(!text.includes(company.name), `${id} names canon company "${company.name}"`);
    }
  }
});

test("none of the three carries an em dash or a money amount", () => {
  for (const id of DRAFTED_IDS) {
    const text = document(id);
    assert.ok(!text.includes("\u2014"), `${id} carries an em dash`);
    assert.deepEqual(moneyMatches(text), [], `${id} states a figure, and these three carry no money`);
  }
});
