// OPS-10 sop-with-unnamed-approver and OPS-14 program-knowledge-corpus: the
// structural screen over the two drafted artifacts of operations cluster 5, the
// path's governance corpus.
//
// The cluster 1 screen (tests/drafted/ops-c1-drafted-screen.test.js) is the
// house style this file follows, and through it the finance D5 screen:
// documents are read lazily inside each test, the CORE-04 roster is generated
// in-test rather than read off disk, and every allowed capitalized string
// except a short furniture list is derived from canon or from generated bytes.
//
// Cluster 5 adds one thing neither earlier screen needed: a citation contract.
// OPS-14 is a bundle whose sources cannot carry their own metadata, because
// three of them are byte-identical copies of documents frozen in other artifact
// directories. So the metadata lives in the index's register, and the synthesis
// page cites into it. That makes three mechanical questions this file can ask
// and answer from committed bytes alone: does every claim carry exactly one
// citation, does every id in a citation exist in the register, and does every
// locator actually resolve against the bytes of the file its register row
// names. A corpus whose citations do not resolve is worse than one with no
// citations at all, because it looks trustworthy.
//
// What this file deliberately does NOT know: which sign-off step carries the
// unnamed approver, which note carries the auto-approve instruction, which
// record entry carries the answer-without-citations instruction, and which cues
// of the two transcripts a citation may not land on. Those are per-instance
// answer keys and label sets, and answer keys do not live in this repo
// (canon/companies.md ground rules, restated in datagen/README.md). They are
// certified by the freeze review and re-derived at stage A. This file holds the
// shape around them: the census, the grammar, the joins and the absences.
import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { loadSpecs } from "../../datagen/src/specLoader.js";
import { loadCanonCompanies } from "../../datagen/src/canon.js";
import { generateArtifact } from "../../datagen/src/engine.js";
import { csvTable, fileByPath } from "../helpers/csv-table.js";
import { allowedFrom, unscreenedPhrases, unscreenedWords } from "../helpers/capitalized-screen.js";
import { moneyMatches } from "../helpers/money-shape.js";

const REPO_ROOT = join(import.meta.dirname, "..", "..");
const specs = loadSpecs(join(REPO_ROOT, "specs", "artifact-specs.yaml"));
const canon = loadCanonCompanies(join(REPO_ROOT, "canon", "companies.md"));

const PROTAGONIST = "Atticus Dundee Inc.";
const DRAFTED_IDS = ["OPS-10", "OPS-14"];

/** The formats the OPS block declares, pinned so a spec edit has to be deliberate. */
const FORMATS = {
  "OPS-10": "markdown",
  "OPS-14": "mixed bundle (OPS-01 + OPS-02 + OPS-10 + narrative history docs)",
};

/** The OPS-14 census, by name. Three copies keep their source basenames; the rest take the spec-name prefix. */
const INDEX_FILE = "program-knowledge-corpus.md";
const COPIES = {
  "meeting-transcript-with-commitments.md": "OPS-01",
  "retro-transcript-with-recurring-finding.md": "OPS-02",
  "sop-with-unnamed-approver.md": "OPS-10",
};
const RECORDS = {
  "program-knowledge-corpus-history-2025-q3.md": { from: "2025-07-01", to: "2025-09-30" },
  "program-knowledge-corpus-history-2025-q4.md": { from: "2025-10-01", to: "2025-12-31" },
  "program-knowledge-corpus-history-2026-q1.md": { from: "2026-01-01", to: "2026-03-31" },
};
const OVERVIEW_FILE = "program-knowledge-corpus-overview.md";
const CORPUS_FILES = [INDEX_FILE, ...Object.keys(COPIES), ...Object.keys(RECORDS), OVERVIEW_FILE];

/** The five files this cluster authors. The three copies are checked for identity, never screened. */
const NEW_CORPUS_FILES = [INDEX_FILE, ...Object.keys(RECORDS), OVERVIEW_FILE];

/** The register's own pins: the three dates that are somebody else's bytes, not a drafter's choice. */
const REGISTER_DATES = { "KB-01": "2026-03-10", "KB-02": "2026-03-27", "KB-03": "2026-03-20" };

/** The C1 date the SOP takes effect, and the one date in the SOP the plan pins rather than leaves to the drafter. */
const EFFECTIVE_DATE = "2026-03-20";

/** The bare role phrase that stands in for a person on exactly one sign-off step. */
const ROLE_PHRASE = "requires manager sign-off";

/**
 * The one person the whole cluster may not name. OPS-01's reported commitment
 * runs through this roster row, so an SOP corroborating or contradicting the
 * support-handoff facts around it would put a C1 attribution surface inside a
 * corpus that is supposed to leave it alone (cluster 5 data plan, section 2.0).
 */
const BARRED_NAME = "Cassian Thistlewood";

/** OPS-01 defines this paragraph for the universe. Nothing cluster 5 authors is a recorded meeting. */
const CONSENT_MARKER = "Consent notice: This meeting is recorded.";

/** The sections the SOP carries, in order. Locators cite these headings by name. */
const SOP_SECTIONS = [
  "1. Purpose",
  "2. Scope",
  "3. Definitions",
  "4. Sign-off steps",
  "5. Escalation path",
  "6. Notes",
];

const STEP_COUNT = 6;
const CLAIM_BAND = { min: 24, max: 36 };
const ENTRY_BAND = { min: 6, max: 10 };

function artifactFile(id, name) {
  const path = join(REPO_ROOT, "artifacts", id, name);
  assert.ok(existsSync(path), `${id}/${name} is not authored yet: ${path} does not exist`);
  return readFileSync(path, "utf8");
}

const sopName = () => `${specs.byId.get("OPS-10").name}.md`;
const sop = () => artifactFile("OPS-10", sopName());
const corpus = (name) => artifactFile("OPS-14", name);

/** The CORE-04 roster, generated rather than read off disk. */
const roster = () => csvTable(
  fileByPath(generateArtifact(specs.byId.get("CORE-04"), canon), "people-roster.csv").content
).rows;

const activeRows = () => roster().filter((r) => r.employment_status === "active");
const fullName = (r) => `${r.first_name} ${r.last_name}`;
const activeRoleTitles = () => [...new Set(activeRows().map((r) => r.role_title))];

// ----------------------------------------------------------------- SOP parsing

/** Every `| key | value |` row of the document-control table, before section 1. */
function documentControl(text) {
  const block = text.split("## 1. Purpose")[0];
  const rows = new Map();
  for (const line of block.split("\n")) {
    if (!line.trim().startsWith("|")) continue;
    const cells = line.split("|").slice(1, -1).map((c) => c.trim());
    if (cells.length !== 2) continue;
    if (cells[0] === "Field" || /^-+$/.test(cells[0])) continue;
    rows.set(cells[0], cells[1]);
  }
  return rows;
}

/** `First Last, Role Title`, split at the FIRST comma so "Director, Operations" survives. */
function personAndRole(value, context) {
  const at = value.indexOf(", ");
  assert.ok(at > 0, `${context}: "${value}" is not "First Last, Role Title"`);
  return { name: value.slice(0, at), role: value.slice(at + 2) };
}

/** The one active row whose printed name and role title are these bytes. */
function resolveActive(name, roleTitle, context) {
  const matches = activeRows().filter((r) => fullName(r) === name && r.role_title === roleTitle);
  assert.equal(
    matches.length, 1,
    `${context}: "${name} (${roleTitle})" resolves to ${matches.length} active roster rows, expected exactly 1`
  );
  return matches[0];
}

/** Every `### Step N: title` block of the SOP, with the lines that belong to it. */
function steps(text) {
  const parts = text.split(/^### Step /m).slice(1);
  return parts.map((part) => {
    const m = part.match(/^(\d+): (.+)$/m);
    assert.ok(m, `a step block does not open "### Step N: title": ${part.slice(0, 60)}`);
    const body = part.slice(part.indexOf("\n"));
    return {
      number: Number(m[1]),
      title: m[2].trim(),
      heading: `Step ${m[1]}: ${m[2].trim()}`,
      approvers: [...body.matchAll(/^Approver:[ \t]*(.*)$/gm)].map((a) => a[1].trim()),
      evidence: [...body.matchAll(/^Evidence:[ \t]*(.*)$/gm)].map((e) => e[1].trim()),
    };
  });
}

/** Every heading in the SOP as a locator would cite it: the text after the hashes. */
function sopHeadings(text) {
  return new Set([...text.matchAll(/^#{2,3} (.+)$/gm)].map((m) => m[1].trim()));
}

// -------------------------------------------------------------- OPS-14 parsing

/** The index's source register, as rows. */
function register(text) {
  const block = text.split("## Source register")[1] ?? "";
  const rows = [];
  for (const line of block.split("\n")) {
    if (!line.trim().startsWith("|")) {
      if (rows.length > 0 && line.trim() === "") break;
      continue;
    }
    const cells = line.split("|").slice(1, -1).map((c) => c.trim());
    if (cells.length !== 5) continue;
    if (cells[0] === "source_id" || /^-+$/.test(cells[0])) continue;
    rows.push({ id: cells[0], title: cells[1], file: cells[2], date: cells[3], scheme: cells[4] });
  }
  return rows;
}

/** Every `## YYYY-MM-DD: heading` entry of a record. */
function entries(text) {
  return [...text.matchAll(/^## (\d{4}-\d{2}-\d{2}): (.+)$/gm)].map((m) => ({
    date: m[1],
    heading: m[2].trim(),
  }));
}

/** Any `## ...` heading of a record that is not a dated entry: a record carries none. */
function undatedRecordHeadings(text) {
  return [...text.matchAll(/^## (.+)$/gm)]
    .map((m) => m[1].trim())
    .filter((h) => !/^\d{4}-\d{2}-\d{2}: /.test(h));
}

const CITATION = /\[(KB-\d{2}), ([^\]]+)\]/g;
const citations = (text) => [...text.matchAll(CITATION)].map((m) => ({ id: m[1], locator: m[2] }));

/** Every list bullet of the overview, with the citations it carries. */
function claims(text) {
  return text.split("\n")
    .filter((line) => line.startsWith("- "))
    .map((line) => ({ line, cites: citations(line) }));
}

// ------------------------------------------------------------------ furniture

// The one place a typed list is allowed. Each entry is here because a document
// has to say it and the pack ships it nowhere else: the document-control field
// labels the CORE-05 control block established, the document's own type word,
// the word a step heading opens with (quoted inside an overview locator, where
// it does not begin a line), and the three month names the corpus writes out.
// The KB ids are NOT here: they are derived below from the register's own bytes,
// which another arm pins to KB-01..KB-07.
const FURNITURE_WORDS = [
  "SOP", "Document", "ID", "Effective", "Date", "Step", "January", "February", "March",
];
const FURNITURE_PHRASES = [];

// ------------------------------------------------------------- the freeze gate

test("the C5 freeze gate is two drafted artifacts, each with a spec that says so", () => {
  for (const id of DRAFTED_IDS) {
    const spec = specs.byId.get(id);
    assert.ok(spec, `${id} is not in the spec catalog`);
    assert.equal(spec.generation, "drafted-frozen", `${id} is not drafted-frozen`);
    assert.equal(spec.format, FORMATS[id], `${id} format drifted from the OPS block`);
    assert.equal(spec.columns, undefined, `${id} is prose and carries no columns`);
    assert.ok(spec.planted_features.length > 0, `${id} states no planted features for validate to check`);
    assert.deepEqual(spec.canon_entities, ["co-002"], `${id} names a canon entity other than the protagonist`);
  }
});

// ----------------------------------------------------------------- OPS-10

test("OPS-10: the document control block parses, is effective 2026-03-20, and joins the roster", () => {
  const control = documentControl(sop());
  for (const field of ["Document ID", "Version", "Status", "Owner", "Approver", "Effective Date"]) {
    assert.ok(control.has(field), `the document control block carries no ${field} row`);
  }
  assert.match(control.get("Document ID"), /^ADI-[A-Z]{3}-\d{3}$/, "the document id is not in the ADI-AREA-NNN form");
  assert.equal(control.get("Status"), "Active", "the SOP is not Active");
  assert.equal(control.get("Effective Date"), EFFECTIVE_DATE, "the SOP does not take effect on the pinned date");
  for (const field of ["Owner", "Approver"]) {
    const { name, role } = personAndRole(control.get(field), `document control ${field}`);
    resolveActive(name, role, `document control ${field}`);
  }
  const reviewed = control.get("Last reviewed");
  const due = control.get("Next review due");
  assert.ok(reviewed && due, "the document control block carries no review dates");
  assert.ok(reviewed <= EFFECTIVE_DATE, `the SOP was last reviewed ${reviewed}, after it took effect`);
  assert.ok(due > EFFECTIVE_DATE, `the next review is due ${due}, on or before the effective date`);
});

test("OPS-10: exactly six sign-off steps, each with one approver line and one non-empty evidence line", () => {
  const parsed = steps(sop());
  assert.equal(parsed.length, STEP_COUNT, `the SOP carries ${parsed.length} sign-off steps, expected ${STEP_COUNT}`);
  assert.deepEqual(
    parsed.map((s) => s.number), [1, 2, 3, 4, 5, 6],
    "the sign-off steps are not numbered 1 to 6 in order"
  );
  for (const step of parsed) {
    assert.equal(step.approvers.length, 1, `step ${step.number} carries ${step.approvers.length} Approver lines, expected 1`);
    assert.equal(step.evidence.length, 1, `step ${step.number} carries ${step.evidence.length} Evidence lines, expected 1`);
    assert.ok(step.approvers[0].length > 0, `step ${step.number} carries an empty Approver line`);
    assert.ok(
      step.evidence[0].length >= 20,
      `step ${step.number}'s Evidence line is not a concrete record: "${step.evidence[0]}"`
    );
    assert.ok(step.title.length > 0, `step ${step.number} carries no title`);
  }
});

test("OPS-10: exactly one approval is the bare role phrase, and every other names an active roster row", () => {
  // The cardinality is recomputed, the instance is not named: this arm counts
  // how many approver lines carry no person, and joins the ones that do.
  const parsed = steps(sop());
  const unnamed = parsed.filter((s) => s.approvers[0] === ROLE_PHRASE);
  assert.equal(
    unnamed.length, 1,
    `${unnamed.length} sign-off steps read "${ROLE_PHRASE}", expected exactly 1`
  );
  const byId = new Map(activeRows().map((r) => [r.employee_id, r]));
  const named = parsed.filter((s) => s.approvers[0] !== ROLE_PHRASE);
  assert.equal(named.length, STEP_COUNT - 1, `${named.length} steps name an approver, expected ${STEP_COUNT - 1}`);
  for (const step of named) {
    const m = step.approvers[0].match(/^(.+) \((EMP-\d{4})\)$/);
    assert.ok(m, `step ${step.number} approver "${step.approvers[0]}" is neither a role phrase nor "First Last (EMP-nnnn)"`);
    const row = byId.get(m[2]);
    assert.ok(row, `step ${step.number} names ${m[2]}, not an active roster row`);
    assert.equal(
      fullName(row), m[1],
      `step ${step.number} names "${m[1]}" against ${m[2]}, and the roster carries "${fullName(row)}" there`
    );
    assert.ok(!step.approvers[0].includes(ROLE_PHRASE), `step ${step.number} both names an approver and carries the role phrase`);
  }
});

test("OPS-10: the six numbered sections are present in order, and the escalation path names seats", () => {
  const text = sop();
  const sections = [...text.matchAll(/^## (\d\. .+)$/gm)].map((m) => m[1].trim());
  assert.deepEqual(sections, SOP_SECTIONS, "the SOP's numbered sections drifted from the section order");
  const escalation = text.split("## 5. Escalation path")[1].split("## 6. Notes")[0];
  const seats = [...escalation.matchAll(/\((EMP-\d{4})\)/g)].map((m) => m[1]);
  assert.ok(seats.length >= 2, `the escalation path names ${seats.length} seats, expected at least 2`);
  const byId = new Map(activeRows().map((r) => [r.employee_id, r]));
  for (const id of seats) assert.ok(byId.get(id), `the escalation path names ${id}, not an active roster row`);
  assert.ok(
    /stuck partway through onboarding/.test(escalation),
    "the escalation path does not say what it is a path for"
  );
});

test("OPS-10 and every OPS-14 file leave the barred roster row unnamed", () => {
  assert.ok(!sop().includes(BARRED_NAME), `the SOP names ${BARRED_NAME}`);
  for (const name of CORPUS_FILES) {
    if (COPIES[name] === "OPS-01") continue; // the frozen transcript is quoted, never edited
    assert.ok(!corpus(name).includes(BARRED_NAME), `OPS-14/${name} names ${BARRED_NAME}`);
  }
});

// ----------------------------------------------------------------- OPS-14

test("OPS-14: the corpus is exactly eight markdown files and no subdirectory but build", () => {
  const dir = join(REPO_ROOT, "artifacts", "OPS-14");
  assert.ok(existsSync(dir), "artifacts/OPS-14 does not exist yet");
  const entriesOnDisk = readdirSync(dir, { withFileTypes: true });
  const files = entriesOnDisk.filter((e) => e.isFile()).map((e) => e.name).sort();
  const dirs = entriesOnDisk.filter((e) => e.isDirectory()).map((e) => e.name).sort();
  assert.deepEqual(files, [...CORPUS_FILES].sort(), "the OPS-14 file census drifted from the eight-file bundle");
  assert.ok(files.every((f) => f.endsWith(".md")), "OPS-14 carries a source file that is not markdown");
  assert.deepEqual(dirs.filter((d) => d !== "build"), [], "OPS-14 carries a subdirectory other than build/");
});

test("OPS-14: the register carries seven rows, KB-01 to KB-07, bijective onto the seven non-index files", () => {
  const rows = register(corpus(INDEX_FILE));
  assert.equal(rows.length, 7, `the source register carries ${rows.length} rows, expected 7`);
  assert.deepEqual(
    rows.map((r) => r.id),
    ["KB-01", "KB-02", "KB-03", "KB-04", "KB-05", "KB-06", "KB-07"],
    "the register ids are not KB-01 to KB-07 in order"
  );
  const expectedFiles = CORPUS_FILES.filter((f) => f !== INDEX_FILE);
  assert.deepEqual(
    rows.map((r) => r.file).sort(), [...expectedFiles].sort(),
    "the register's file column is not a bijection onto the seven non-index files"
  );
  for (const row of rows) {
    assert.match(row.date, /^\d{4}-\d{2}-\d{2}$/, `register row ${row.id} carries "${row.date}", not an ISO date`);
    assert.ok(row.title.length > 0, `register row ${row.id} carries no title`);
    assert.ok(row.scheme.length > 0, `register row ${row.id} carries no locator scheme`);
    if (REGISTER_DATES[row.id]) {
      assert.equal(row.date, REGISTER_DATES[row.id], `register row ${row.id} is dated ${row.date}, not its source's own date`);
    }
  }
  assert.match(corpus(INDEX_FILE), /^As of: 2026-03-31$/m, "the index does not state the date the corpus is assembled as of");
});

test("OPS-14: the three embedded copies are byte-identical to the artifacts they copy", () => {
  for (const [name, id] of Object.entries(COPIES)) {
    const source = id === "OPS-10" ? sop() : artifactFile(id, name);
    assert.equal(
      corpus(name), source,
      `OPS-14/${name} has drifted from artifacts/${id}/${name}; a bundled copy may never differ from its source`
    );
  }
});

test("OPS-14: each record carries 6 to 10 dated entries, every date inside that record's own quarter", () => {
  for (const [name, window] of Object.entries(RECORDS)) {
    const text = corpus(name);
    const rows = entries(text);
    assert.ok(
      rows.length >= ENTRY_BAND.min && rows.length <= ENTRY_BAND.max,
      `${name} carries ${rows.length} entries, outside the ${ENTRY_BAND.min} to ${ENTRY_BAND.max} band`
    );
    assert.deepEqual(undatedRecordHeadings(text), [], `${name} carries a section heading that is not a dated entry`);
    const dates = rows.map((r) => r.date);
    assert.equal(new Set(dates).size, dates.length, `${name} carries two entries on the same date`);
    for (const row of rows) {
      assert.ok(
        row.date >= window.from && row.date <= window.to,
        `${name} carries an entry dated ${row.date}, outside ${window.from} to ${window.to}`
      );
      assert.ok(row.heading.length > 0, `${name} carries an entry with no heading text`);
    }
    for (let i = 1; i < dates.length; i += 1) {
      assert.ok(dates[i] > dates[i - 1], `${name} runs backwards at ${dates[i]}`);
    }
  }
});

test("OPS-14: every overview bullet is a claim carrying exactly one citation at its end", () => {
  const text = corpus(OVERVIEW_FILE);
  const rows = claims(text);
  assert.ok(
    rows.length >= CLAIM_BAND.min && rows.length <= CLAIM_BAND.max,
    `the overview carries ${rows.length} claims, outside the ${CLAIM_BAND.min} to ${CLAIM_BAND.max} band`
  );
  for (const row of rows) {
    assert.equal(row.cites.length, 1, `an overview bullet carries ${row.cites.length} citations, expected 1: ${row.line}`);
    assert.ok(
      row.line.endsWith(`[${row.cites[0].id}, ${row.cites[0].locator}]`),
      `an overview bullet does not end in its citation: ${row.line}`
    );
    assert.ok(
      row.line.slice(2).indexOf("[") > 20,
      `an overview bullet states no claim ahead of its citation: ${row.line}`
    );
  }
  const ids = new Set(rows.map((r) => r.cites[0].id));
  for (const id of ids) {
    assert.ok(
      ["KB-01", "KB-02", "KB-03", "KB-04", "KB-05", "KB-06"].includes(id),
      `the overview cites ${id}; the overview cites KB-01 to KB-06 and never itself`
    );
  }
  for (const id of ["KB-01", "KB-02", "KB-03", "KB-04", "KB-05", "KB-06"]) {
    assert.ok(ids.has(id), `no overview claim cites ${id}, so a registered source carries nothing`);
  }
  assert.equal(
    citations(text).length, rows.length,
    "the overview carries a citation outside a claim bullet"
  );
});

test("OPS-14: nothing but the overview carries a citation token", () => {
  for (const name of [INDEX_FILE, ...Object.keys(RECORDS)]) {
    assert.deepEqual(
      citations(corpus(name)), [],
      `OPS-14/${name} carries a citation token; only the synthesis cites`
    );
  }
  assert.deepEqual(citations(sop()), [], "the SOP carries a citation token");
});

test("OPS-14: every overview locator resolves against the bytes of the file its register row names", () => {
  const byId = new Map(register(corpus(INDEX_FILE)).map((r) => [r.id, r]));
  const headings = sopHeadings(corpus("sop-with-unnamed-approver.md"));
  const recordDates = Object.fromEntries(
    Object.keys(RECORDS).map((name) => [name, new Set(entries(corpus(name)).map((e) => e.date))])
  );
  for (const { id, locator } of claims(corpus(OVERVIEW_FILE)).map((c) => c.cites[0])) {
    const row = byId.get(id);
    assert.ok(row, `the overview cites ${id}, which the register does not carry`);
    if (id === "KB-01" || id === "KB-02") {
      assert.match(locator, /^\d{2}:\d{2}:\d{2}$/, `${id} locator "${locator}" is not a cue timestamp`);
      assert.ok(
        corpus(row.file).includes(`[${locator}]`),
        `${id} locator "${locator}" names no cue in ${row.file}`
      );
    } else if (id === "KB-03") {
      assert.ok(
        headings.has(locator),
        `${id} locator "${locator}" names no section or step heading in ${row.file}`
      );
    } else {
      assert.match(locator, /^\d{4}-\d{2}-\d{2}$/, `${id} locator "${locator}" is not an entry date`);
      assert.ok(
        recordDates[row.file]?.has(locator),
        `${id} locator "${locator}" names no entry in ${row.file}`
      );
    }
  }
});

// ---------------------------------------------------------------- name screens

test("no roster full name appears in the index, the records or the overview", () => {
  // The corpus speaks in programs, teams and role phrases. A person-level answer
  // can only come from the embedded transcripts and the SOP, which is the whole
  // mechanical guarantee that the narrative history touches no attribution
  // surface of the two frozen transcripts.
  const names = [...new Set(roster().map(fullName))];
  assert.ok(names.length > 500, "the roster came back too small for this screen to prove anything");
  for (const name of NEW_CORPUS_FILES) {
    const text = corpus(name);
    for (const person of names) {
      assert.ok(!text.includes(person), `OPS-14/${name} names ${person}, and the narrative history names nobody`);
    }
  }
});

test("no departed CORE-04 employee is named in the SOP or in any file this cluster authors", () => {
  const rows = roster();
  const live = new Set(rows.filter((r) => r.employment_status === "active").map(fullName));
  const departed = [...new Set(
    rows.filter((r) => r.employment_status === "departed").map(fullName)
  )].filter((name) => !live.has(name));
  assert.ok(departed.length > 0, "the roster carries no departed employees, so this screen proves nothing");
  const texts = [sop(), ...NEW_CORPUS_FILES.map(corpus)];
  for (const text of texts) {
    for (const name of departed) {
      assert.ok(!text.includes(name), `a cluster 5 file names ${name}, who has left the company`);
    }
  }
});

test("every capitalized phrase and word is accounted for by the roster, the protagonist or the furniture", () => {
  const registerIds = register(corpus(INDEX_FILE)).map((r) => r.id);
  // The document-control block prints a person and a title as one run, the
  // CORE-05 form, so the joined string has to be derivable too: "Merritt
  // Nightshade, Director, Operations" is one phrase to the screen, and neither
  // half on its own accounts for it.
  const namedSeats = activeRows().map((r) => `${fullName(r)}, ${r.role_title}`);
  const allowed = allowedFrom({
    derived: [
      PROTAGONIST,
      ...activeRoleTitles(),
      ...activeRows().map(fullName),
      ...namedSeats,
      ...registerIds,
    ],
    furniturePhrases: FURNITURE_PHRASES,
    furnitureWords: FURNITURE_WORDS,
  });
  const documents = [["OPS-10", sop()], ...NEW_CORPUS_FILES.map((n) => [`OPS-14/${n}`, corpus(n)])];
  for (const [label, text] of documents) {
    assert.deepEqual(unscreenedPhrases(text, allowed), [], `unscreened capitalized phrase(s) in ${label}`);
    assert.deepEqual(unscreenedWords(text, allowed), [], `unscreened capitalized word(s) in ${label}`);
  }
});

test("no canon company other than the protagonist is named, and no consent banner travels with the corpus", () => {
  const documents = [["OPS-10", sop()], ...NEW_CORPUS_FILES.map((n) => [`OPS-14/${n}`, corpus(n)])];
  for (const [label, text] of documents) {
    for (const company of canon.values()) {
      if (company.name === PROTAGONIST) continue;
      assert.ok(!text.includes(company.name), `${label} names canon company "${company.name}"`);
    }
    assert.ok(!text.includes(CONSENT_MARKER), `${label} carries the consent banner, which belongs to a recorded meeting`);
  }
});

test("nothing this cluster authors carries an em dash or a money amount", () => {
  const documents = [["OPS-10", sop()], ...NEW_CORPUS_FILES.map((n) => [`OPS-14/${n}`, corpus(n)])];
  for (const [label, text] of documents) {
    assert.ok(!text.includes("—"), `${label} carries an em dash`);
    assert.deepEqual(moneyMatches(text), [], `${label} states a figure, and cluster 5 carries no money`);
  }
});
