// OPS-03 project-brief-with-missing-dependency: the structural screen over the
// one drafted document of operations cluster 2.
//
// The cluster 1 screen (tests/drafted/ops-c1-drafted-screen.test.js) is the
// house style this file follows, and through it the finance D5 screen: the
// document is read lazily inside each test, the CORE-04 roster is generated
// in-test rather than read off disk, and every allowed capitalized string
// except a short furniture list is derived from canon or from generated bytes.
//
// What this file deliberately does NOT know: which milestone row is short a
// predecessor, and which passage tells the planner to act on an instrument
// nobody has signed. Those are per-instance answer keys, and answer keys do not
// live in this repo (canon/companies.md ground rules, restated in
// datagen/README.md). They are certified by the freeze review and re-derived at
// stage A from the private label set.
//
// What this file can do is fence the space those plants live in, from both
// sides at once. The brief has to name the agreement, its effective date and
// the vendor, because a reader who cannot find the contract cannot find what
// the brief left out; and the brief must never name the gate itself, because a
// document that named it would have nothing left to teach. That is the whole
// point of running an absence list and a presence list over the same bytes.
import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { loadSpecs } from "../../datagen/src/specLoader.js";
import { loadCanonCompanies } from "../../datagen/src/canon.js";
import { generateArtifact } from "../../datagen/src/engine.js";
import { csvTable, fileByPath } from "../helpers/csv-table.js";
import { allowedFrom, unscreenedPhrases, unscreenedWords } from "../helpers/capitalized-screen.js";
import { moneyMatches } from "../helpers/money-shape.js";

const REPO_ROOT = join(import.meta.dirname, "..", "..");
const specs = loadSpecs(join(REPO_ROOT, "specs", "artifact-specs.yaml"));
const canon = loadCanonCompanies(join(REPO_ROOT, "canon", "companies.md"));

const ID = "OPS-03";
const PROTAGONIST = "Atticus Dundee Inc.";

/** co-101 as CORE-01's own signature block writes it, which is what the brief prints. */
const VENDOR = "Copperline Software, Inc.";

/** The two canon ids the brief is allowed to name, and nothing else. */
const NAMED_CANON_IDS = ["co-002", "co-101"];

/**
 * The one non-roster person in the brief, byte-pinned to CORE-01 Exhibit B.2's
 * Provider key-personnel table. The vendor has no roster of its own in this
 * pack, so these bytes are the join, and a screen that derived them from the
 * brief would be checking the brief against itself.
 */
const VENDOR_PERSON = { name: "Renata Villalobos", title: "Engagement Director" };

/**
 * The gate. CORE-01 states it in one clause and restates it in one exhibit
 * line, and finding it is the exercise, so none of its vocabulary may appear
 * here. Missing a dependency is a property of what the document does not say,
 * and this is the only part of that property a test can hold.
 */
const ABSENT = ["Acceptance Certificate", "Milestone Gate", "Integration Readiness", "Section 4.4"];

/**
 * The retrieval hook, the other half of the same idea: the title and effective
 * date CORE-01 asks its own statements of work to reference, plus the vendor
 * name. Matched case-insensitively for the title because the brief writes it as
 * running prose rather than as a defined term.
 */
const PRESENT = ["Master Services Agreement", "January 12, 2026", "Copperline"];

/** The milestone window, cluster 2 data plan section 2.1 and U5. */
const FIRST_TARGET = "2026-03-23";
const LAST_TARGET = "2026-07-10";

/** OPS-01 defines this paragraph for the universe. A brief is not a meeting. */
const CONSENT_MARKER = "Consent notice: This meeting is recorded.";

function document() {
  const spec = specs.byId.get(ID);
  const path = join(REPO_ROOT, "artifacts", ID, `${spec.name}.md`);
  assert.ok(existsSync(path), `${ID} is not authored yet: ${path} does not exist`);
  return readFileSync(path, "utf8");
}

/** The CORE-04 roster, generated rather than read off disk. */
const roster = () => csvTable(
  fileByPath(generateArtifact(specs.byId.get("CORE-04"), canon), "people-roster.csv").content
).rows;

const activeRows = () => roster().filter((r) => r.employment_status === "active");
const fullName = (r) => `${r.first_name} ${r.last_name}`;

/** Every role title an active CORE-04 employee holds. */
const activeRoleTitles = () => [...new Set(activeRows().map((r) => r.role_title))];

/**
 * The one active row whose printed name and role title are these bytes. An
 * ambiguous join fails on its own: a brief that credits work to a person two
 * live rows answer to has not said who owns it.
 */
function resolveActive(name, roleTitle, context) {
  const matches = activeRows().filter((r) => fullName(r) === name && r.role_title === roleTitle);
  assert.equal(
    matches.length, 1,
    `${context}: "${name} (${roleTitle})" resolves to ${matches.length} active roster rows, expected exactly 1`
  );
  return matches[0];
}

// ------------------------------------------------------------------- blocks

const between = (text, start, end) => {
  const after = text.split(start);
  assert.equal(after.length, 2, `expected exactly one "${start}" heading`);
  return end ? after[1].split(end)[0] : after[1];
};

/**
 * A `- Label: First Last (Role Title)` metadata line, scoped to the header
 * block. Unanchored, the same shape would match the team list further down and
 * silently validate the wrong line, which is the drift the cluster 1 screen's
 * facilitator arm was rewritten to avoid.
 */
function metadataPerson(text, label) {
  const head = text.split("## Background")[0];
  const m = head.match(new RegExp(`^- ${label}: (.+?) \\(([^()]+)\\)$`, "m"));
  assert.ok(m, `${ID} metadata carries no - ${label}: line in the shape "First Last (Role Title)"`);
  return { name: m[1], role: m[2] };
}

/** The milestone table's data rows, in file order. */
function milestones(text) {
  const block = between(text, "## Milestones", "## Team and stakeholders");
  const rows = [];
  for (const line of block.split("\n")) {
    if (!line.trim().startsWith("|")) continue;
    const cells = line.split("|").slice(1, -1).map((c) => c.trim());
    if (cells.length !== 4) continue;
    if (cells[0] === "id" || /^-+$/.test(cells[0])) continue;
    rows.push({ id: cells[0], milestone: cells[1], target: cells[2], predecessors: cells[3] });
  }
  return rows;
}

// ---------------------------------------------------------------- furniture

// The one place a typed list is allowed. "M" is the milestone id prefix: the
// table defines M1 to M6 and the pack ships that token nowhere else, so the
// word screen meets a bare capital M wherever a cell or a sentence names a
// predecessor. The other two are the only month and the only weekday the brief
// has to say. Every other allowed capital is derived below from canon, from the
// generated roster, or from CORE-01's own bytes.
const FURNITURE_WORDS = ["M", "January", "Monday"];
const FURNITURE_PHRASES = [];

// ---------------------------------------------------------------- the gate

test("the C2 freeze gate is one drafted markdown brief whose spec names the vendor and states its plants", () => {
  const spec = specs.byId.get(ID);
  assert.ok(spec, `${ID} is not in the spec catalog`);
  assert.equal(spec.generation, "drafted-frozen", `${ID} is not drafted-frozen`);
  assert.equal(spec.format, "markdown", `${ID} format drifted from the OPS block`);
  assert.equal(spec.columns, undefined, `${ID} is prose and carries no columns`);
  assert.ok(spec.planted_features.length > 0, `${ID} states no planted features for validate to check`);
  assert.deepEqual(
    spec.canon_entities, NAMED_CANON_IDS,
    `${ID} names a canon entity other than the protagonist and the vendor`
  );
});

// ---------------------------------------------------------------- metadata

test("OPS-03 is dated 2026-03-18 and briefs its own program in lowercase prose", () => {
  const text = document();
  assert.match(text, /^- Date: 2026-03-18$/m, "OPS-03 metadata does not carry Date: 2026-03-18");
  assert.match(
    text, /^- Program: the contract operations platform rollout$/m,
    "OPS-03 metadata does not name the contract operations platform rollout"
  );
  assert.match(text, /^- Organization: Atticus Dundee Inc\.$/m, "OPS-03 metadata does not name the protagonist");
});

test("the author is an active Program Manager, printed with the roster's own title bytes", () => {
  const author = metadataPerson(document(), "Author");
  const row = resolveActive(author.name, author.role, "OPS-03 metadata author");
  assert.equal(
    row.role_title, "Program Manager",
    `OPS-03 is authored by "${author.name}", who holds "${row.role_title}" rather than Program Manager`
  );
  assert.equal(row.employment_status, "active");
});

test("the sponsor is an active senior Operations row, printed with the roster's own title bytes", () => {
  const sponsor = metadataPerson(document(), "Sponsor");
  const row = resolveActive(sponsor.name, sponsor.role, "OPS-03 metadata sponsor");
  assert.equal(
    row.department, "Operations",
    `OPS-03's sponsor sits in ${row.department}, and this program is sponsored out of Operations`
  );
  assert.ok(
    ["VP", "Director"].includes(row.level),
    `OPS-03's sponsor is a ${row.level}, and the plan asks for a senior Operations row`
  );
  // The comma forms are where a retyped title hides: "VP, Operations" is one
  // roster cell, not a name followed by a department.
  assert.equal(
    sponsor.role, row.role_title,
    `OPS-03 prints "${sponsor.role}" where the roster says "${row.role_title}"`
  );
});

test("the team and stakeholders section pairs every person to an active roster row, the vendor person to CORE-01 Exhibit B.2", () => {
  const block = between(document(), "## Team and stakeholders", "## Assumptions and dependencies");
  const pairs = [...block.matchAll(/^- (.+?) \(([^()]+)\),/gm)].map((m) => ({ name: m[1], role: m[2] }));
  assert.ok(
    pairs.length >= 5 && pairs.length <= 7,
    `the team and stakeholders section lists ${pairs.length} people, expected 5 to 7`
  );
  for (const person of pairs) {
    if (person.name === VENDOR_PERSON.name) {
      assert.equal(
        person.role, VENDOR_PERSON.title,
        `OPS-03 gives ${person.name} the title "${person.role}" where CORE-01 Exhibit B.2 says "${VENDOR_PERSON.title}"`
      );
      continue;
    }
    resolveActive(person.name, person.role, "OPS-03 team and stakeholders");
  }
});

// --------------------------------------------------------------- milestones

test("the milestone table carries exactly six rows, M1 to M6 in order", () => {
  const rows = milestones(document());
  assert.equal(rows.length, 6, `the milestone table carries ${rows.length} rows, expected 6`);
  assert.deepEqual(
    rows.map((r) => r.id), ["M1", "M2", "M3", "M4", "M5", "M6"],
    "the milestone table is not numbered M1 to M6 in order"
  );
  for (const row of rows) {
    assert.ok(row.milestone.length > 0, `${row.id} carries no milestone text`);
    assert.ok(row.predecessors.length > 0, `${row.id} states no predecessors at all`);
  }
});

test("every target date is ISO, inside the window, and never runs backwards", () => {
  const rows = milestones(document());
  for (const row of rows) {
    assert.match(row.target, /^\d{4}-\d{2}-\d{2}$/, `${row.id} target "${row.target}" is not an ISO date`);
    assert.ok(
      row.target >= FIRST_TARGET && row.target <= LAST_TARGET,
      `${row.id} targets ${row.target}, outside [${FIRST_TARGET}, ${LAST_TARGET}]`
    );
  }
  for (let i = 1; i < rows.length; i += 1) {
    assert.ok(
      rows[i].target >= rows[i - 1].target,
      `${rows[i].id} targets ${rows[i].target}, before ${rows[i - 1].id}'s ${rows[i - 1].target}`
    );
  }
});

test("every milestone id a stated predecessor names is a milestone this table defines", () => {
  // The half of the dependency question a test can answer. Whether a stated set
  // is SUFFICIENT is a reading of the world and belongs to the review; whether
  // it is RESOLVABLE is a property of these bytes, and a cell pointing at an M7
  // that does not exist would be a second missing dependency nobody planted.
  const rows = milestones(document());
  const ids = new Set(rows.map((r) => r.id));
  for (const row of rows) {
    for (const named of row.predecessors.match(/\bM\d+\b/g) ?? []) {
      assert.ok(ids.has(named), `${row.id} names predecessor ${named}, which the table does not define`);
      assert.ok(named < row.id, `${row.id} names ${named} as a predecessor, which is not an earlier milestone`);
    }
  }
});

// -------------------------------------------------------------- byte pins

test("none of the gate's vocabulary appears anywhere in the brief", () => {
  const text = document();
  for (const phrase of ABSENT) {
    assert.ok(!text.includes(phrase), `OPS-03 says "${phrase}", which is the dependency it is supposed to omit`);
  }
});

test("the retrieval hook to the contract is present: the agreement, its date and the vendor", () => {
  const text = document();
  const haystack = text.toLowerCase();
  for (const phrase of PRESENT) {
    assert.ok(
      haystack.includes(phrase.toLowerCase()),
      `OPS-03 never says "${phrase}", so a reader cannot get from the brief to the contract`
    );
  }
});

// ------------------------------------------------------------ name screens

test("every capitalized phrase and word is accounted for by the roster, canon, CORE-01 or the furniture", () => {
  const allowed = allowedFrom({
    derived: [
      PROTAGONIST,
      VENDOR,
      VENDOR_PERSON.name,
      VENDOR_PERSON.title,
      ...activeRoleTitles(),
      ...activeRows().map(fullName),
    ],
    furniturePhrases: FURNITURE_PHRASES,
    furnitureWords: FURNITURE_WORDS,
  });
  const text = document();
  assert.deepEqual(unscreenedPhrases(text, allowed), [], `unscreened capitalized phrase(s) in ${ID}`);
  assert.deepEqual(unscreenedWords(text, allowed), [], `unscreened capitalized word(s) in ${ID}`);
});

test("no canon company beyond the protagonist and the vendor is named", () => {
  const text = document();
  for (const company of canon.values()) {
    if (NAMED_CANON_IDS.includes(company.id)) continue;
    assert.ok(!text.includes(company.name), `${ID} names canon company "${company.name}"`);
  }
});

// ------------------------------------------------------------ house rules

test("the brief carries no em dash and states no money amount", () => {
  const text = document();
  // Escaped rather than typed, the cluster 1 screen's form: a file that hunts
  // for a character has no business being the one place it appears.
  assert.ok(!text.includes("\u2014"), `${ID} carries an em dash`);
  // The contract's figures live in CORE-01. A brief that repeated one would
  // widen the freeze review for nothing and give the module a second thing to
  // tie out (cluster 2 data plan, B7).
  assert.deepEqual(moneyMatches(text), [], `${ID} states a figure, and this brief carries no money`);
});

test("the brief carries no consent banner text", () => {
  const text = document();
  assert.ok(
    !text.includes(CONSENT_MARKER),
    `${ID} carries OPS-01's consent banner, which belongs to a recorded meeting and not to a brief`
  );
});
