// REV-06 product-security-fact-sheet: the structural screen over the two
// drafted documents of revenue cluster 2, the path's claims baseline.
//
// tests/drafted/ops-c1-drafted-screen.test.js is the house style this file
// follows: documents are read lazily inside each test, the CORE-04 roster is
// generated in-test rather than read off disk, and the screens derive their
// expectations from canon or from generated bytes instead of retyping them.
//
// What this file deliberately does NOT know: which snippet carries the
// unregistered certification, or which certification that is. Those are the
// per-instance answer key, and answer keys do not live in this repo
// (canon/people.md ground rules, restated in datagen/README.md). What it does
// recompute is the cardinality, because the selection rule is mechanical:
// extract certification assertions by membership in the pinned vocabulary
// (tests/helpers/rev-c2-cert-vocabulary.js), resolve each one against the
// register's own certification rows, and count. Anyone applying that rule to
// the committed bytes gets the same answer, exactly as with a dataset plant.
//
// Two mechanical rules are stated once here and used throughout.
//
//   Certification resolution. A snippet asserts certification C when the exact
//   vocabulary string C appears in the snippet. It resolves when C also appears
//   in a `certification` row of the claims register. Nothing else counts as
//   holding a certification; in particular a `security-control` row that
//   mentions an audit does not.
//
//   Register-claim resolution, for the non-certification half of REV-C2-T5. A
//   snippet asserts a register claim when the snippet and some register row
//   share a run of five or more consecutive words, compared after lowercasing,
//   replacing every non-alphanumeric run with a space, and collapsing
//   whitespace. That is the OPS-02 normalize-and-collide rule widened from a
//   whole finding to an n-gram, and it is deliberately dumb: an assistant that
//   is repeating the maintained baseline reuses its wording, and an assistant
//   that is inventing does not. It is a floor, not a semantic check, and it is
//   the only claim-resolution rule this file applies.
import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { loadSpecs } from "../../datagen/src/specLoader.js";
import { loadCanonCompanies } from "../../datagen/src/canon.js";
import { generateArtifact } from "../../datagen/src/engine.js";
import { csvTable, fileByPath } from "../helpers/csv-table.js";
import { moneyMatches } from "../helpers/money-shape.js";
import { REV_C2_CERT_VOCABULARY, certificationsIn } from "../helpers/rev-c2-cert-vocabulary.js";

const REPO_ROOT = join(import.meta.dirname, "..", "..");
const specs = loadSpecs(join(REPO_ROOT, "specs", "artifact-specs.yaml"));
const canon = loadCanonCompanies(join(REPO_ROOT, "canon", "companies.md"));

const PROTAGONIST = "Atticus Dundee Inc.";
const ARTIFACT = "REV-06";
const FACT_SHEET = "product-security-fact-sheet.md";
const SNIPPETS = "claim-snippets.md";
const DOCUMENTS = [FACT_SHEET, SNIPPETS];

/** The five register categories, and nothing else. */
const CATEGORIES = ["certification", "security-control", "availability", "data-protection", "company"];

/** The universe clock ceiling for this artifact: nothing dates past the first week of April. */
const LATEST_DATE = "2026-04-07";

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

function document(name) {
  const path = join(REPO_ROOT, "artifacts", ARTIFACT, name);
  assert.ok(existsSync(path), `${ARTIFACT}/${name} is not authored yet: ${path} does not exist`);
  return readFileSync(path, "utf8");
}

// ------------------------------------------------------------- the register

/**
 * The one markdown table whose header is `claim_id | category | claim`, parsed
 * to rows. A second such table, or none, is a failure of its own: the register
 * is single-sourced and everything below resolves against it.
 */
function register() {
  const text = document(FACT_SHEET);
  const lines = text.split("\n");
  const cells = (line) => line.split("|").slice(1, -1).map((c) => c.trim());
  const heads = lines
    .map((line, i) => ({ line, i }))
    .filter(({ line }) => line.trim().startsWith("|"))
    .filter(({ line }) => {
      const c = cells(line);
      return c.length === 3 && c[0] === "claim_id" && c[1] === "category" && c[2] === "claim";
    });
  assert.equal(heads.length, 1, `the fact sheet carries ${heads.length} claims-register tables, expected exactly 1`);
  const rows = [];
  for (let i = heads[0].i + 1; i < lines.length; i += 1) {
    if (!lines[i].trim().startsWith("|")) break;
    const c = cells(lines[i]);
    if (c.every((cell) => /^:?-+:?$/.test(cell))) continue;
    assert.equal(c.length, 3, `register row ${lines[i]} does not carry three cells`);
    rows.push({ claim_id: c[0], category: c[1], claim: c[2], line: i + 1 });
  }
  return rows;
}

const certificationRows = () => register().filter((r) => r.category === "certification");

/** Every vocabulary entry a `certification` register row names: what co-002 holds. */
function heldCertifications() {
  const held = new Set();
  for (const row of certificationRows()) for (const name of certificationsIn(row.claim)) held.add(name);
  return held;
}

// ------------------------------------------------------------- the snippets

const SNIPPET_HEAD = /^## (SNP-\d{2})$/;

/** `## SNP-NN` heading, then everything up to the next heading of any level. */
function snippets() {
  const lines = document(SNIPPETS).split("\n");
  const out = [];
  for (const [i, line] of lines.entries()) {
    const m = line.match(SNIPPET_HEAD);
    if (!m) continue;
    const body = [];
    for (let j = i + 1; j < lines.length && !lines[j].startsWith("#"); j += 1) body.push(lines[j]);
    out.push({ id: m[1], body: body.join("\n").trim(), line: i + 1 });
  }
  return out;
}

// ------------------------------------------------- the two resolution rules

const NGRAM = 5;
const normalize = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();

function ngrams(text, n = NGRAM) {
  const words = normalize(text).split(" ").filter(Boolean);
  const out = new Set();
  for (let i = 0; i + n <= words.length; i += 1) out.add(words.slice(i, i + n).join(" "));
  return out;
}

/** The register rows a snippet repeats a five-word run of. */
function registerClaimsAsserted(snippetBody) {
  const runs = ngrams(snippetBody);
  return register().filter((row) => [...ngrams(row.claim)].some((run) => runs.has(run)));
}

// ------------------------------------------------------ canon name screens

/**
 * Every person canon/people.md seats, records as an erratum alias, reserves, or
 * flags in the real-person collision screen.
 *
 * The mechanism, stated because a denylist that silently empties proves nothing:
 * a `| pe-NNN |` row carries the person in cell 2 (every one of the four seating
 * tables puts the name there); any other table row carries a candidate in cell 1
 * (the retired, frozen, reserved and flagged-name tables all lead with it). A
 * candidate is kept when, after shedding an `Hon. ` prefix and a `, M.D.` /
 * `, EnCE` / ` (Ret.)` suffix, it is two to four tokens, each an initial or a
 * capitalized word, with no digit. Header cells, separator rows, tier letters
 * and role phrases fail that shape. The count is asserted below, so a canon
 * reshuffle that breaks the parse fails by name instead of quietly passing.
 */
function canonPeople() {
  const text = readFileSync(join(REPO_ROOT, "canon", "people.md"), "utf8");
  const shape = /^[A-Z][\p{L}'’-]+(?: (?:[A-Z]\.|[A-Z][\p{L}'’-]+)){1,3}$/u;
  const names = new Set();
  for (const line of text.split("\n")) {
    if (!line.trim().startsWith("|")) continue;
    const cells = line.split("|").slice(1, -1).map((c) => c.trim());
    if (cells.length < 2) continue;
    const candidate = /^pe-\d{3}$/.test(cells[0]) ? cells[1] : cells[0];
    const bare = candidate
      .replace(/^Hon\.\s+/, "")
      .replace(/,\s*(?:M\.D\.|EnCE)$/, "")
      .replace(/\s*\(Ret\.\)$/, "")
      .trim();
    if (!bare || /\d/.test(bare)) continue;
    if (shape.test(bare)) names.add(bare);
  }
  return names;
}

/** Every role title canon/people.md gives a seated person, first clause only. */
function canonRoleTitles() {
  const text = readFileSync(join(REPO_ROOT, "canon", "people.md"), "utf8");
  const titles = new Set();
  for (const line of text.split("\n")) {
    if (!line.trim().startsWith("| pe-")) continue;
    const cells = line.split("|").slice(1, -1).map((c) => c.trim());
    if (cells.length < 3) continue;
    const title = cells[2].split(";")[0].trim();
    if (title) titles.add(title);
  }
  return titles;
}

/** The CORE-04 roster, generated rather than read off disk (the ops precedent). */
const roster = () => csvTable(
  fileByPath(generateArtifact(specs.byId.get("CORE-04"), canon), "people-roster.csv").content
).rows;

// ------------------------------------------------------------------- dates

const ISO_DATE = /\b(\d{4})-(\d{2})-(\d{2})\b/g;
const LONG_DATE = new RegExp(`\\b(${MONTHS.join("|")}) (\\d{1,2}), (\\d{4})\\b`, "g");
const pad = (n) => String(n).padStart(2, "0");

/** Every date either document writes, ISO or long form, as ISO strings. */
function datesIn(text) {
  const out = [];
  for (const m of text.matchAll(ISO_DATE)) out.push({ written: m[0], iso: m[0] });
  for (const m of text.matchAll(LONG_DATE)) {
    out.push({ written: m[0], iso: `${m[3]}-${pad(MONTHS.indexOf(m[1]) + 1)}-${pad(Number(m[2]))}` });
  }
  return out;
}

// ------------------------------------------------------------ the freeze gate

test("REV-06 is a drafted-frozen document spec whose two markdown files are on disk", () => {
  const spec = specs.byId.get(ARTIFACT);
  assert.ok(spec, "REV-06 is not in the spec catalog");
  assert.equal(spec.generation, "drafted-frozen", "REV-06 is not drafted-frozen");
  assert.equal(spec.name, "product-security-fact-sheet", "REV-06's spec name drifted from the REV block");
  assert.equal(spec.columns, undefined, "REV-06 is prose and carries no columns");
  assert.ok(spec.planted_features.length > 0, "REV-06 states no planted features for validate to check");
  assert.deepEqual(spec.canon_entities, ["co-002"], "REV-06 names a canon entity other than the protagonist");
  for (const name of DOCUMENTS) assert.ok(document(name).length > 0, `${name} is empty`);
});

// ---------------------------------------------------------------- structure

test("REV-C2: the claims register parses with sequential FS-NN ids and only the five categories", () => {
  const rows = register();
  assert.ok(rows.length >= 15 && rows.length <= 20, `the register carries ${rows.length} rows, outside the 15 to 20 band`);
  assert.deepEqual(
    rows.map((r) => r.claim_id),
    rows.map((_, i) => `FS-${pad(i + 1)}`),
    "the register ids are not FS-01 upward in order with no gap"
  );
  for (const row of rows) {
    assert.ok(
      CATEGORIES.includes(row.category),
      `register line ${row.line}: "${row.category}" is not one of the five categories`
    );
    assert.ok(row.claim.length >= 40, `${row.claim_id} states a claim of ${row.claim.length} characters, too short to be one`);
  }
  const certs = rows.filter((r) => r.category === "certification");
  assert.ok(certs.length >= 3, `the register carries ${certs.length} certification rows, expected at least 3`);
  const used = new Set(rows.map((r) => r.category));
  assert.deepEqual([...used].sort(), [...CATEGORIES].sort(), "the register does not use all five categories, or uses another");
});

test("REV-C2: the snippets are headed SNP-01 upward in order, four of them, each a paragraph", () => {
  const found = snippets();
  assert.equal(found.length, 4, `claim-snippets.md carries ${found.length} snippets, expected 4`);
  assert.deepEqual(
    found.map((s) => s.id),
    found.map((_, i) => `SNP-${pad(i + 1)}`),
    "the snippet ids are not SNP-01 upward in order with no gap"
  );
  for (const snippet of found) {
    assert.ok(snippet.body.length >= 200, `${snippet.id} is ${snippet.body.length} characters, too short to be an outbound paragraph`);
    assert.ok(snippet.body.length <= 1600, `${snippet.id} is ${snippet.body.length} characters, longer than a short outbound paragraph`);
  }
});

test("REV-C2: the certification vocabulary is substring-clean and a strict superset of the register", () => {
  for (const a of REV_C2_CERT_VOCABULARY) {
    for (const b of REV_C2_CERT_VOCABULARY) {
      if (a === b) continue;
      assert.ok(
        !b.includes(a),
        `vocabulary entry "${a}" is a substring of "${b}", so substring extraction would report one assertion as two`
      );
    }
  }
  for (const row of certificationRows()) {
    assert.ok(
      certificationsIn(row.claim).length > 0,
      `${row.claim_id} is a certification row naming no vocabulary entry, so the vocabulary has gone stale against the register`
    );
  }
  const both = DOCUMENTS.map(document).join("\n\n");
  const spare = REV_C2_CERT_VOCABULARY.filter((entry) => !both.includes(entry));
  assert.ok(
    spare.length >= 2,
    `only ${spare.length} vocabulary entries appear in neither REV-06 file, expected at least 2 so membership marks nothing`
  );
});

// ------------------------------------------------------------- REV-C2-T5

test("REV-C2-T5: exactly one snippet asserts an unregistered certification, every other assertion resolves, and every snippet asserts a register claim", () => {
  const held = heldCertifications();
  assert.ok(held.size >= 3, `the register's certification rows name ${held.size} vocabulary entries, expected at least 3`);

  const read = snippets().map((snippet) => {
    const asserted = certificationsIn(snippet.body);
    return {
      id: snippet.id,
      asserted,
      unresolved: asserted.filter((name) => !held.has(name)),
      claims: registerClaimsAsserted(snippet.body),
    };
  });

  const fabricating = read.filter((s) => s.unresolved.length > 0);
  assert.equal(
    fabricating.length, 1,
    `${fabricating.length} snippets assert a certification with no register row, expected exactly 1`
    + ` (${read.map((s) => `${s.id}: [${s.unresolved.join(", ")}]`).join("; ")})`
  );

  const unregistered = new Set(read.flatMap((s) => s.unresolved));
  assert.equal(
    unregistered.size, 1,
    `${unregistered.size} distinct unregistered certifications are asserted across the snippets, expected exactly 1`
  );

  for (const snippet of read) {
    if (snippet === fabricating[0]) continue;
    assert.deepEqual(
      snippet.unresolved, [],
      `${snippet.id} asserts a certification with no register row, and it is not the one snippet that may`
    );
  }

  for (const snippet of read) {
    assert.ok(
      snippet.claims.length > 0,
      `${snippet.id} repeats no five-word run of any register row, so it asserts no register claim to hide among`
    );
  }
});

// -------------------------------------------------------------- name screen

test("REV-C2: the maintained-by line names a role, and neither document names a canon person", () => {
  const factSheet = document(FACT_SHEET);
  const maintainer = factSheet.match(/^\*\*Maintained by:\*\* (.+)$/m);
  assert.ok(maintainer, "the fact sheet carries no **Maintained by:** line");
  const role = maintainer[1].trim();
  const rows = roster();
  const roles = new Set([...canonRoleTitles(), ...rows.map((r) => r.role_title)]);
  assert.ok(roles.size >= 40, `only ${roles.size} role titles were derived from canon and the roster; the parse has broken`);
  assert.ok(
    roles.has(role),
    `the fact sheet is maintained by "${role}", which is not a role title canon or the CORE-04 roster carries`
  );

  const people = canonPeople();
  assert.ok(people.size >= 60, `only ${people.size} canon people were parsed out of canon/people.md; the parse has broken`);
  assert.ok(people.has("Kestrel Ashgrove"), "the canon-people parse missed a seated person; the table shape has moved");
  assert.ok(people.has("Jonathan K. Sterling"), "the canon-people parse missed a retired real-collision name");
  const forbidden = new Set([...people, ...rows.map((r) => `${r.first_name} ${r.last_name}`)]);
  for (const name of DOCUMENTS) {
    const text = document(name);
    for (const person of forbidden) {
      assert.ok(!text.includes(person), `${name} names ${person}; these two documents name roles only`);
    }
  }
});

// -------------------------------------------------------------- date screens

test("REV-C2: the fact sheet carries a last-reviewed date inside March 2026", () => {
  const line = document(FACT_SHEET).match(/^\*\*Last reviewed:\*\* (.+)$/m);
  assert.ok(line, "the fact sheet carries no **Last reviewed:** line");
  const found = datesIn(line[1]);
  assert.equal(found.length, 1, `the last-reviewed line carries ${found.length} dates, expected exactly 1`);
  assert.ok(
    found[0].iso.startsWith("2026-03-"),
    `the fact sheet was last reviewed ${found[0].written}, outside March 2026`
  );
});

test("REV-C2: no date in either document runs past the first week of April 2026", () => {
  for (const name of DOCUMENTS) {
    const found = datesIn(document(name));
    assert.ok(found.length > 0, `${name} carries no date at all`);
    for (const date of found) {
      assert.ok(
        date.iso <= LATEST_DATE,
        `${name} carries the date ${date.written}, past the ${LATEST_DATE} ceiling of the universe clock`
      );
    }
  }
});

// ------------------------------------------------------------- house screens

test("REV-C2: the fact sheet states no money amount and no share-of-revenue figure", () => {
  const text = document(FACT_SHEET);
  assert.deepEqual(moneyMatches(text), [], "the fact sheet states a figure, and the claims baseline carries no money");
  assert.equal(text.includes("$"), false, "the fact sheet carries a currency symbol");
  assert.equal(
    /\b(?:\d+(?:\.\d+)?\s*(?:percent|%)\s*of\s+(?:total\s+)?(?:revenue|sales|bookings)|of\s+(?:annual\s+)?revenue)\b/i.test(text),
    false,
    "the fact sheet states a share-of-revenue figure"
  );
});

test("REV-C2: neither document carries an em dash, and neither names a canon company but the protagonist", () => {
  for (const name of DOCUMENTS) {
    const text = document(name);
    assert.ok(!text.includes("\u2014"), `${name} carries an em dash (U+2014)`);
    for (const company of canon.values()) {
      if (company.name === PROTAGONIST) continue;
      assert.ok(!text.includes(company.name), `${name} names canon company "${company.name}"`);
    }
  }
});
