// FIN-16 collections-contact-log: the outreach behind co-002's aged receivable,
// plus the collections-policy.json that carries the inputs no contact log can
// derive (the dunning ladder, the credit limits, the hold and dispute rules and
// the FIN-39 rows that authorize a write off).
//
// Every planted feature is re-derived here from the generated bytes plus the
// frozen FIN-04 aging, by the rule the spec states and never by naming the
// customer that carries it: the credit-hold breach is recomputed by comparing
// each customer's aged open balance against the policy's own limit, the broken
// promise by looking for a later payment that covers it, and the live dispute by
// looking for a later row on the same document. Each asserts a cardinality of
// one, so a reroll that produces none or two fails here.
import { test } from "node:test";
import assert from "node:assert/strict";
import { join } from "node:path";
import { loadSpecs } from "../../datagen/src/specLoader.js";
import { loadCanonCompanies } from "../../datagen/src/canon.js";
import { generateArtifact } from "../../datagen/src/engine.js";
import { csvTable, fileByPath } from "../helpers/csv-table.js";
import { buildArAging } from "../../datagen/src/generators/fin-04-ar-aging.js";
import { buildDecisionAuthorityMatrix } from "../../datagen/src/generators/fin-39-decision-authority-matrix.js";
import { financeRoster } from "../../datagen/src/generators/finance-roles.js";
import { generate as generateCrmSeed } from "../../datagen/src/generators/core-03-crm-seed.js";
import { createRng } from "../../datagen/src/seed.js";

import {
  CONTACT_AS_OF, CONTACT_PERIOD, CHANNELS, DIRECTIONS, OUTCOMES,
  LOG_CUSTOMER_COUNT, SEGMENT_CREDIT_LIMITS, TARGET_CONTACTS,
} from "../../datagen/src/generators/fin-15-collections.js";

const REPO_ROOT = join(import.meta.dirname, "..", "..");
const specs = loadSpecs(join(REPO_ROOT, "specs", "artifact-specs.yaml"));
const canon = loadCanonCompanies(join(REPO_ROOT, "canon", "companies.md"));
const spec = specs.byId.get("FIN-16");
const creditNoteSpec = specs.byId.get("FIN-15");
const LOG_FILE = "collections-contact-log.csv";
const POLICY_FILE = "collections-policy.json";

const roster = financeRoster();
const employee = (employeeId) => roster.find((r) => r.employee_id === employeeId);
const cents = (money) => Math.round(Number(money) * 100);

const { aging } = buildArAging();
const agingByNumber = new Map(aging.map((r) => [r.document_number, r]));
const authority = buildDecisionAuthorityMatrix();

/** Per-customer open balance and oldest days past due, straight off the aging. */
const customers = (() => {
  const out = new Map();
  for (const row of aging) {
    const seen = out.get(row.customer_canon_id) ?? {
      customer_canon_id: row.customer_canon_id, name: row.customer_name, openCents: 0, oldestDaysPastDue: 0,
    };
    seen.openCents += cents(row.open_balance);
    seen.oldestDaysPastDue = Math.max(seen.oldestDaysPastDue, Number(row.days_past_due));
    out.set(row.customer_canon_id, seen);
  }
  return out;
})();

const crmSegments = (() => {
  const crm = JSON.parse(
    generateCrmSeed({ rng: (stream) => createRng("CORE-03", stream) })
      .find((f) => f.path === "crm-seed.json").content
  );
  return new Map(crm.accounts.map((a) => [a.account_id, a.segment]));
})();

function outputs() {
  assert.ok(spec, "FIN-16 not found in specs/artifact-specs.yaml");
  const files = generateArtifact(spec, canon);
  const table = csvTable(fileByPath(files, LOG_FILE).content);
  assert.deepEqual(table.cols, spec.columns, "FIN-16: header does not match spec.columns");
  return { rows: table.rows, policy: JSON.parse(fileByPath(files, POLICY_FILE).content) };
}

/** The ladder stage the policy itself assigns to a days-past-due figure. */
function stageFor(ladder, daysPastDue) {
  const reached = ladder.filter((s) => daysPastDue >= s.days_past_due_min);
  assert.ok(reached.length > 0, `no dunning stage opens at ${daysPastDue} days past due`);
  return String(reached[reached.length - 1].stage);
}

// ------------------------------------------------------------------ the shape

test("FIN-16: sixty-four contacts across twelve customers, uniquely numbered and inside the contact period", () => {
  const { rows } = outputs();
  assert.equal(rows.length, TARGET_CONTACTS, `the log carries ${rows.length} contacts, expected ${TARGET_CONTACTS}`);
  assert.equal(new Set(rows.map((r) => r.contact_id)).size, rows.length, "contact_id repeats");
  assert.equal(
    new Set(rows.map((r) => r.customer_canon_id)).size, LOG_CUSTOMER_COUNT,
    "the log does not cover the twelve accounts collections is working"
  );
  for (const row of rows) {
    assert.ok(CHANNELS.includes(row.channel), `${row.contact_id} used channel "${row.channel}"`);
    assert.ok(DIRECTIONS.includes(row.direction), `${row.contact_id} has direction "${row.direction}"`);
    assert.ok(OUTCOMES.includes(row.outcome), `${row.contact_id} has outcome "${row.outcome}"`);
    assert.ok(
      row.contact_date >= CONTACT_PERIOD.start && row.contact_date <= CONTACT_PERIOD.end,
      `${row.contact_id} is dated ${row.contact_date}, outside the contact period`
    );
    assert.ok(row.next_action_date > row.contact_date, `${row.contact_id} schedules its follow up on or before itself`);
  }
  for (const outcome of OUTCOMES) {
    assert.ok(rows.some((r) => r.outcome === outcome), `no contact ends in "${outcome}", so a rule keyed to it finds nothing`);
  }
  assert.equal(CONTACT_AS_OF, CONTACT_PERIOD.end, "the as-of is not the last day the log covers");
});

test("FIN-16: the twelve accounts worked are the twelve largest open balances in the aging, with no tie at the cut", () => {
  const { rows } = outputs();
  const ranked = [...customers.values()].sort((a, b) => b.openCents - a.openCents);
  const expected = new Set(ranked.slice(0, LOG_CUSTOMER_COUNT).map((c) => c.customer_canon_id));
  assert.notEqual(
    ranked[LOG_CUSTOMER_COUNT - 1].openCents, ranked[LOG_CUSTOMER_COUNT].openCents,
    "two accounts tie at the cut, so which twelve are worked is not decided by the aging"
  );
  assert.deepEqual(
    new Set(rows.map((r) => r.customer_canon_id)), expected,
    "the log works accounts the aging does not rank in its twelve largest"
  );
  for (const row of rows) {
    assert.equal(
      row.customer_name, customers.get(row.customer_canon_id).name,
      `${row.contact_id} calls ${row.customer_canon_id} something the aging does not`
    );
  }
});

test("FIN-16: there is no free-text note column, because a note is where an answer key hides", () => {
  const noteish = /(^|_)(notes?|comments?|remarks?|details?|summary|description|free_text)$/i;
  for (const column of creditNoteSpec.columns) {
    assert.doesNotMatch(column, noteish, `FIN-15 column "${column}" invites free text`);
  }
  for (const column of spec.columns) {
    assert.doesNotMatch(column, noteish, `FIN-16 column "${column}" invites free text`);
  }
});

// ----------------------------------------------------------------- the policy

test("FIN-16: collections-policy.json carries a four-stage ladder, a limit for every aged customer and the rules no CSV can derive", () => {
  const { policy } = outputs();
  assert.equal(policy.generated_from_spec, "FIN-16");
  assert.equal(policy.currency, "USD");
  assert.equal(policy.as_of, CONTACT_AS_OF);

  assert.equal(policy.dunning_ladder.length, 4, "the ladder is not four stages");
  let previousMin = 0;
  for (const [index, stage] of policy.dunning_ladder.entries()) {
    assert.equal(stage.stage, index + 1, "the ladder is not numbered from one upward in order");
    assert.ok(stage.days_past_due_min > previousMin, "a later stage opens no later than the one before it");
    previousMin = stage.days_past_due_min;
    assert.ok(CHANNELS.includes(stage.channel), `stage ${stage.stage} names channel "${stage.channel}"`);
    assert.ok(
      roster.some((r) => r.role_title === stage.owner_role && r.employment_status === "active" && r.department === "Finance"),
      `stage ${stage.stage} is owned by "${stage.owner_role}", which no active Finance employee holds`
    );
    assert.ok(stage.action.length > 0, `stage ${stage.stage} states no action`);
  }

  assert.equal(
    policy.credit_limits.length, customers.size,
    "the policy does not carry one credit limit per customer in the aging"
  );
  for (const limit of policy.credit_limits) {
    const customer = customers.get(limit.customer_canon_id);
    assert.ok(customer, `the policy sets a limit for ${limit.customer_canon_id}, which is not in the aging`);
    assert.equal(limit.customer_name, customer.name, `${limit.customer_canon_id} is named differently in the policy`);
    const segment = crmSegments.get(limit.customer_canon_id);
    assert.equal(
      cents(limit.credit_limit), SEGMENT_CREDIT_LIMITS[segment],
      `${limit.customer_canon_id} does not carry the standard limit for a ${segment} account`
    );
  }

  assert.equal(policy.credit_hold_rule.combine, "all", "a hold that needs only one condition puts most of the book on hold");
  assert.equal(policy.credit_hold_rule.open_balance_exceeds_credit_limit, true);
  assert.equal(typeof policy.credit_hold_rule.oldest_days_past_due_over, "number");
  assert.equal(policy.dispute_rule.hold_outreach, true, "outreach continues while a document is disputed");
  assert.equal(
    policy.dispute_rule.escalate_to_role, "Controller",
    "a dispute escalates to a role the finance ladder does not carry"
  );
});

test("FIN-16: write_off_authority names FIN-39 rows that actually decide a receivable write off", () => {
  const { policy } = outputs();
  assert.equal(policy.write_off_authority.length, 2, "the write-off authority is not the two-row band the matrix carries");
  const rows = policy.write_off_authority.map((controlId) => {
    const row = authority.find((r) => r.control_id === controlId);
    assert.ok(row, `${controlId} is not a control_id in the shipped FIN-39 matrix`);
    return row;
  });
  assert.equal(new Set(rows.map((r) => r.decision)).size, 1, "the two authority rows decide different things");
  assert.match(rows[0].decision, /receivable write off/i, "the cited rows do not decide a receivable write off");
  assert.equal(rows[0].amount_min_usd, "0", "the lower write-off band does not open at zero");
  assert.equal(rows[1].amount_max_usd, "", "the upper write-off band is capped, so large receivables have no approver");
  assert.equal(rows[0].amount_max_usd !== "" && Number(rows[0].amount_max_usd) + 1 === Number(rows[1].amount_min_usd), true,
    "the two write-off bands leave a gap or overlap");
  for (const row of rows) {
    assert.equal(row.ai_autonomy_level, "approval_before_action", `${row.control_id} lets a write off happen without approval`);
  }
});

// ------------------------------------------------------------- the ladder tie

test("FIN-16: every dunning_stage recomputes from the ladder given that customer's oldest days past due in FIN-04", () => {
  const { rows, policy } = outputs();
  for (const row of rows) {
    const customer = customers.get(row.customer_canon_id);
    assert.equal(
      row.dunning_stage, stageFor(policy.dunning_ladder, customer.oldestDaysPastDue),
      `${row.contact_id} is at stage ${row.dunning_stage}, which the ladder does not give ${customer.oldestDaysPastDue} days past due`
    );
    const stage = policy.dunning_ladder[Number(row.dunning_stage) - 1];
    // The ladder prescribes the outreach, so it governs outbound contacts. A
    // customer who calls or writes in chooses its own channel.
    if (row.direction === "outbound") {
      assert.equal(row.channel, stage.channel, `${row.contact_id} went out on a channel the ladder does not open at its stage`);
    }
  }
  assert.ok(
    new Set(rows.map((r) => r.dunning_stage)).size >= 2,
    "every account is at one stage, so the ladder decides nothing"
  );
});

test("FIN-16: every contact is owned by the AR clerk who owns that account in FIN-04, and that clerk holds the ladder's role", () => {
  const { rows, policy } = outputs();
  const owners = new Map(aging.map((r) => [r.customer_canon_id, r.ar_owner_employee_id]));
  const owned = new Set();
  for (const row of rows) {
    assert.equal(
      row.owner_employee_id, owners.get(row.customer_canon_id),
      `${row.contact_id} was made by someone other than the clerk who owns the account in FIN-04`
    );
    const person = employee(row.owner_employee_id);
    assert.ok(person, `${row.contact_id}: ${row.owner_employee_id} is not on the CORE-04 roster`);
    assert.equal(person.employment_status, "active", `${row.contact_id}: the owner is not active`);
    assert.equal(person.department, "Finance", `${row.contact_id}: the owner is not in Finance`);
    assert.equal(
      person.role_title, policy.dunning_ladder[Number(row.dunning_stage) - 1].owner_role,
      `${row.contact_id}: the owner does not hold the role the ladder gives its stage`
    );
    owned.add(row.owner_employee_id);
  }
  assert.equal(owned.size, 2, `${owned.size} clerks work the book, and the aging assigns it to two`);
});

// ---------------------------------------------------------------- the plants

test("FIN-16: exactly one account is past the credit-hold threshold, recomputed from the aging against the policy's own limits", () => {
  const { policy } = outputs();
  const limits = new Map(policy.credit_limits.map((l) => [l.customer_canon_id, cents(l.credit_limit)]));
  const overLimit = [...customers.values()].filter((c) => c.openCents > limits.get(c.customer_canon_id));
  assert.equal(overLimit.length, 1, `${overLimit.length} accounts are over their credit limit, expected 1`);
  const onHold = overLimit.filter((c) => c.oldestDaysPastDue > policy.credit_hold_rule.oldest_days_past_due_over);
  assert.equal(onHold.length, 1, "the account over its limit is not delinquent enough to go on hold");
  assert.ok(
    onHold[0].oldestDaysPastDue > 60,
    "the account on hold carries nothing 61 or more days past due, which is not the aging the spec describes"
  );
  const { rows } = outputs();
  assert.ok(
    rows.some((r) => r.customer_canon_id === onHold[0].customer_canon_id),
    "the account on hold is not being worked in the contact log"
  );
});

test("FIN-16: exactly one promise to pay is broken, and at least one other was kept", () => {
  const { rows } = outputs();
  const promises = rows.filter((r) => r.outcome === "promise_to_pay");
  assert.ok(promises.length >= 3, "fewer than three promises makes a broken one structural rather than planted");
  const broken = promises.filter((promise) => {
    if (!(promise.promise_to_pay_date < CONTACT_AS_OF)) return false;
    return !rows.some((r) => (
      r.customer_canon_id === promise.customer_canon_id &&
      r.outcome === "payment_received" &&
      r.contact_date > promise.contact_date &&
      cents(r.promise_amount) >= cents(promise.promise_amount)
    ));
  });
  assert.equal(broken.length, 1, `${broken.length} promises to pay were broken, expected 1`);
  assert.equal(
    new Set(broken.map((r) => r.customer_canon_id)).size, 1,
    "the broken promise spans more than one account"
  );
  for (const promise of promises) {
    assert.notEqual(promise.promise_to_pay_date, "", `${promise.contact_id} promises payment on no date`);
    assert.ok(cents(promise.promise_amount) > 0, `${promise.contact_id} promises nothing`);
    assert.ok(
      promise.promise_to_pay_date > promise.contact_date,
      `${promise.contact_id} promises payment on or before the day of the call`
    );
    const openCents = customers.get(promise.customer_canon_id).openCents;
    assert.ok(
      cents(promise.promise_amount) <= openCents,
      `${promise.contact_id} promises more than the account owes`
    );
  }
});

test("FIN-16: promise_to_pay_date and promise_amount are populated exactly where an amount is on the table", () => {
  for (const row of outputs().rows) {
    const carriesAmount = row.outcome === "promise_to_pay" || row.outcome === "payment_received";
    assert.equal(
      row.promise_amount !== "", carriesAmount,
      `${row.contact_id} disagrees with its own outcome about whether money was named`
    );
    assert.equal(
      row.promise_to_pay_date !== "", row.outcome === "promise_to_pay",
      `${row.contact_id} carries a promise date without promising anything`
    );
  }
});

test("FIN-16: exactly one dispute is still live, and it resolves to a FIN-04 invoice and to a FIN-15 note still requested", () => {
  const { rows } = outputs();
  const disputes = rows.filter((r) => r.outcome === "dispute_raised");
  assert.ok(disputes.length >= 2, "one dispute makes a live one structural rather than planted");
  const live = disputes.filter((dispute) => !rows.some((r) => (
    r.customer_canon_id === dispute.customer_canon_id &&
    r.disputed_document_number === dispute.disputed_document_number &&
    r.contact_date > dispute.contact_date
  )));
  assert.equal(live.length, 1, `${live.length} disputes are still live, expected 1`);

  const [dispute] = live;
  const invoice = agingByNumber.get(dispute.disputed_document_number);
  assert.ok(invoice, "the live dispute names a document the aging does not carry");
  assert.equal(invoice.document_type, "invoice", "the live dispute is raised against a credit memo");
  assert.equal(invoice.customer_canon_id, dispute.customer_canon_id, "the disputed invoice belongs to another customer");

  const creditNotes = csvTable(
    fileByPath(generateArtifact(creditNoteSpec, canon), "customer-credit-notes.csv").content
  ).rows;
  const behind = creditNotes.filter((n) => n.applied_to_document === dispute.disputed_document_number);
  assert.equal(behind.length, 1, `${behind.length} credit notes sit behind the disputed invoice, expected 1`);
  assert.equal(
    behind[0].status, "requested",
    "the note behind the disputed invoice is already issued, so the invoice is collectable as billed after all"
  );
  assert.equal(behind[0].customer_canon_id, dispute.customer_canon_id);

  const ranked = [...customers.values()].sort((a, b) => a.oldestDaysPastDue - b.oldestDaysPastDue);
  assert.notEqual(ranked[0].oldestDaysPastDue, ranked[1].oldestDaysPastDue, "two accounts tie as the healthiest payer");
  assert.equal(
    dispute.customer_canon_id, ranked[0].customer_canon_id,
    "the live dispute sits on a delinquent account, so the distressed account answers every question the log asks"
  );
});

test("FIN-16: disputed_document_number is populated only where a document is actually in dispute", () => {
  const { rows } = outputs();
  for (const row of rows) {
    if (row.disputed_document_number === "") continue;
    assert.ok(
      ["dispute_raised", "payment_received", "escalated"].includes(row.outcome),
      `${row.contact_id} names a disputed document on a "${row.outcome}" contact`
    );
    const document = agingByNumber.get(row.disputed_document_number);
    assert.ok(document, `${row.contact_id} disputes a document the aging does not carry`);
    assert.equal(
      document.customer_canon_id, row.customer_canon_id,
      `${row.contact_id} disputes another customer's document`
    );
  }
  assert.ok(
    rows.some((r) => r.disputed_document_number === ""),
    "every contact names a disputed document, so the column decides nothing"
  );
});

// ---------------------------------------------------------------- determinism

test("FIN-16: two runs of the generator produce identical bytes", () => {
  const runA = generateArtifact(spec, canon);
  const runB = generateArtifact(spec, canon);
  assert.deepEqual(runA.map((f) => f.path), runB.map((f) => f.path));
  for (let i = 0; i < runA.length; i += 1) {
    assert.equal(runA[i].content, runB[i].content, `${runA[i].path} differs between runs`);
  }
});
