// FIN-33 actuals-24mo and FIN-34 drivers: the wave's red tests.
//
// SKELETON, shipped by D5a foundations. Every test carrying `{ todo: WAVE }`
// fails today on purpose: the generator is not registered, so generateArtifact
// throws NOT_IMPLEMENTED. `node --test` runs a todo test and reports its
// failure without counting it, so `npm test` stays at zero failures while still
// printing what is not built yet.
//
// The wave that builds FIN-33 deletes the `{ todo: WAVE }` option from every
// test in this file, in the same commit as the bytes. Leaving it in place would
// ship an artifact whose own tests do not gate it, which is worse than shipping
// no test at all.
//
// What the wave still has to write is marked TODO inside each test. The rule
// that does not change: re-derive every plant from the generated bytes by its
// own stated rule, never by naming the row that carries it, and never by
// importing the builder's own predicate. A test that imports the predicate it
// is checking cannot disagree with the generator.
import { test } from "node:test";
import assert from "node:assert/strict";
import { join } from "node:path";
import { loadSpecs } from "../../datagen/src/specLoader.js";
import { loadCanonCompanies } from "../../datagen/src/canon.js";
import { generateArtifact } from "../../datagen/src/engine.js";
import { csvTable, fileByPath } from "../helpers/csv-table.js";
import { buildBudgetVsActualTemplate } from "../../datagen/src/generators/fin-37-budget-vs-actual-template.js";
import { buildTrialBalance } from "../../datagen/src/generators/fin-05-gl-trial-balance.js";
import { COLUMNS, DRIVER_IDS, SCENARIOS } from "../../datagen/src/generators/fin-33-actuals-24mo.js";
import { actualAmountCents } from "../../datagen/src/generators/finance-statement.js";
import { cents, toCents } from "../../datagen/src/money.js";
import { createRng } from "../../datagen/src/seed.js";
import { CLOSE_PERIOD_END, monthEnds, TREND_MONTHS } from "../../datagen/src/dates.js";

const WAVE = "D5a wave A (plan Task 5) builds FIN-33 and FIN-34 and deletes this marker";

const REPO_ROOT = join(import.meta.dirname, "..", "..");
const specs = loadSpecs(join(REPO_ROOT, "specs", "artifact-specs.yaml"));
const canon = loadCanonCompanies(join(REPO_ROOT, "canon", "companies.md"));
const OUTPUT_FILE = "actuals-24mo.csv";

const PERIODS = monthEnds(TREND_MONTHS, CLOSE_PERIOD_END).map((d) => d.slice(0, 7));

/** The shipped FIN-37 spine, from its own builder under its own seed. */
const templateLines = () => buildBudgetVsActualTemplate((stream) => createRng("FIN-37", stream));

function trend() {
  const table = csvTable(fileByPath(generateArtifact(specs.byId.get("FIN-33"), canon), OUTPUT_FILE).content);
  assert.deepEqual(table.cols, specs.byId.get("FIN-33").columns, "FIN-33: header does not match spec.columns");
  return table.rows;
}

// --------------------------------------------------------- green before bytes
// These hold the contract the wave builds against, and they pass today.

test("FIN-33: the generator's column list and the spec agree before a byte exists", () => {
  assert.deepEqual(COLUMNS, specs.byId.get("FIN-33").columns);
});

test("FIN-33: the shape the two reconciliation rules have to hit is already fixed by frozen bytes", () => {
  const lines = templateLines();
  assert.equal(lines.length, 27, "the FIN-37 spine is no longer 27 lines, so 648 is the wrong row count");
  assert.equal(PERIODS.length, 24);
  assert.equal(PERIODS[0], "2024-04");
  assert.equal(PERIODS[23], "2026-03");
  assert.equal(lines.length * PERIODS.length, 648, "27 lines by 24 months is the whole file");

  // Rule 2 rests on the fiscal year being the calendar year, so a profit-and-loss
  // beginning balance at 2026-03-01 is exactly January plus February.
  const tb = new Map(buildTrialBalance().rows.map((r) => [r.account_code, r]));
  for (const line of lines) {
    const row = tb.get(line.account_code);
    assert.ok(row, `${line.line_id} names account ${line.account_code}, which FIN-05 does not carry`);
    assert.doesNotThrow(() => toCents(row.beginning_balance), `${line.account_code} has no parseable beginning balance`);
  }
});

// ------------------------------------------------------------ red until built

test("FIN-33: 648 rows, the 27 FIN-37 lines by the 24 month-ends, spine imported not retyped", { todo: WAVE }, () => {
  const rows = trend();
  assert.equal(rows.length, 648);
  assert.deepEqual([...new Set(rows.map((r) => r.period))].sort(), [...PERIODS].sort());
  // TODO(wave): compare the (line_id, account_code, account_name,
  // statement_section, normal_balance) spine against buildBudgetVsActualTemplate()
  // row for row, so a template edit lands here rather than drifting silently.
});

test("FIN-33 T-T1: every 2026-03 actual equals FIN-05's period movement to the cent", { todo: WAVE }, () => {
  const tb = new Map(buildTrialBalance().rows.map((r) => [r.account_code, r]));
  const march = trend().filter((r) => r.period === "2026-03");
  assert.equal(march.length, 27);
  for (const row of march) {
    assert.equal(
      row.actual_amount,
      cents(actualAmountCents(tb.get(row.account_code), row.normal_balance)),
      `${row.line_id} does not equal FIN-05's March movement`
    );
  }
  // The FIN-24 leg of T-T1 lives in fin-24-actuals-vs-budget.test.js, because
  // FIN-24 does not exist when this wave runs.
});

test("FIN-33 T-T2 and T-T7: January plus February is the beginning balance, and all three months are the ending balance", { todo: WAVE }, () => {
  const tb = new Map(buildTrialBalance().rows.map((r) => [r.account_code, r]));
  const rows = trend();
  const byAccount = new Map();
  for (const row of rows) {
    const seen = byAccount.get(row.account_code) ?? new Map();
    seen.set(row.period, toCents(row.actual_amount));
    byAccount.set(row.account_code, seen);
  }
  for (const [accountCode, months] of byAccount) {
    const balance = tb.get(accountCode);
    const opening = months.get("2026-01") + months.get("2026-02");
    assert.equal(cents(opening), balance.beginning_balance, `${accountCode}: January plus February is not the beginning balance`);
    const full = opening + months.get("2026-03");
    assert.equal(cents(full), balance.ending_balance, `${accountCode}: the quarter does not close at the ending balance`);
  }
  // TODO(wave): FIN-05 states an ending balance in the account's own direction,
  // so a credit-normal line's comparison flips. Assert both directions rather
  // than taking the absolute value, which would hide a sign error.
});

test("FIN-33 T-T4: exactly 3 lines breach the flux rule and exactly 1 of them also breaches the budget rule", { todo: WAVE }, () => {
  const rows = trend();
  assert.ok(rows.length > 0);
  // TODO(wave): recompute the flux threshold from FIN-26's published rule in
  // this test's own arithmetic, count the February-to-March breaches, and
  // assert 3, the overlap of 1, and the qualifier-free count of 27 that a
  // reader gets with no threshold at all.
});

test("FIN-33 V25: exactly one line has a peak that repeats at 12-month spacing", { todo: WAVE }, () => {
  const rows = trend();
  assert.ok(rows.length > 0);
  // TODO(wave): state the repeat rule in the test, apply it to all 27 series,
  // assert the cardinality of 1, and assert the qualifier-free count of 27
  // (every line moves month to month; only one peak repeats). The line is
  // account 6310 Events and Conferences, the SECOND smallest budget on the
  // tracker at 18300.00. The smallest is 6700 Bank Fees at 400.00, which is too
  // small to carry a visible amplitude.
});

test("FIN-34: five drivers, three scenarios, and every applies_to resolving in a shipped file", { todo: WAVE }, () => {
  const files = generateArtifact(specs.byId.get("FIN-34"), canon);
  const yamlText = fileByPath(files, "drivers.yaml").content;
  for (const driver of DRIVER_IDS) assert.ok(yamlText.includes(driver), `drivers.yaml does not carry ${driver}`);
  for (const scenario of SCENARIOS) assert.ok(yamlText.includes(scenario), `drivers.yaml does not carry ${scenario}`);
  // TODO(wave): parse the YAML, assert T-T5 (every applies_to is a FIN-33
  // line_id or a FIN-31 metric_id), T-T6 (the derived cost per head recomputes
  // from FIN-05 and CORE-04 in this test's own arithmetic), V23 (exactly one
  // band crosses zero, five bands in total) and V24 (exactly one driver moves
  // cash without moving margin, two if contract_win_loss is misread).
});

test("FIN-33 and FIN-34 V19: no emitted file names the absent metric", { todo: WAVE }, () => {
  const emitted = [
    ...generateArtifact(specs.byId.get("FIN-33"), canon),
    ...generateArtifact(specs.byId.get("FIN-34"), canon),
  ];
  for (const file of emitted) {
    // FIN-34's own spec planted_features carry the word, which is why the scope
    // of this rule is the emitted datasets and never the repository.
    assert.ok(!/runway/i.test(file.content), `${file.path} names the metric the pack deliberately does not declare`);
  }
});
