// FIN-33 actuals-24mo and FIN-34 drivers.
//
// The rule this file follows: re-derive every plant from the generated bytes by
// its own stated rule, never by naming the row that carries it, and never by
// importing the builder's own predicate. A test that imports the predicate it
// is checking cannot disagree with the generator. So the flux threshold, the
// budget threshold, the peak rule and the cost per head are all recomputed
// here, in this file's own arithmetic, from bytes that were frozen before
// FIN-33 existed.
//
// Every plant is asserted twice: the count under its stated rule, and the count
// with the one qualifier the rule names dropped. A qualifier that only one side
// knows about is a qualifier a later edit deletes silently.
import { test } from "node:test";
import assert from "node:assert/strict";
import { join } from "node:path";
import { readFileSync } from "node:fs";
import yaml from "js-yaml";
import { loadSpecs } from "../../datagen/src/specLoader.js";
import { loadCanonCompanies } from "../../datagen/src/canon.js";
import { generateArtifact } from "../../datagen/src/engine.js";
import { csvTable, fileByPath } from "../helpers/csv-table.js";
import { buildBudgetVsActualTemplate } from "../../datagen/src/generators/fin-37-budget-vs-actual-template.js";
import { buildTrialBalance } from "../../datagen/src/generators/fin-05-gl-trial-balance.js";
import { COLUMNS, DRIVER_IDS, SCENARIOS } from "../../datagen/src/generators/fin-33-actuals-24mo.js";
import { actualAmountCents } from "../../datagen/src/generators/finance-statement.js";
import { cents, toCents } from "../../datagen/src/money.js";
import { createRng } from "../../datagen/src/seed.js";
import { CLOSE_PERIOD_END, monthEnds, TREND_MONTHS } from "../../datagen/src/dates.js";

const REPO_ROOT = join(import.meta.dirname, "..", "..");
const specs = loadSpecs(join(REPO_ROOT, "specs", "artifact-specs.yaml"));
const canon = loadCanonCompanies(join(REPO_ROOT, "canon", "companies.md"));
const OUTPUT_FILE = "actuals-24mo.csv";

const PERIODS = monthEnds(TREND_MONTHS, CLOSE_PERIOD_END).map((d) => d.slice(0, 7));

/** The shipped FIN-37 spine, from its own builder under its own seed. */
const templateLines = () => buildBudgetVsActualTemplate((stream) => createRng("FIN-37", stream));

/** A shipped dataset's own committed bytes, read off disk rather than rebuilt. */
const shipped = (name, file) =>
  csvTable(readFileSync(join(REPO_ROOT, "datasets", ...name.split("/"), file), "utf8")).rows;

function trend() {
  const table = csvTable(fileByPath(generateArtifact(specs.byId.get("FIN-33"), canon), OUTPUT_FILE).content);
  assert.deepEqual(table.cols, specs.byId.get("FIN-33").columns, "FIN-33: header does not match spec.columns");
  return table.rows;
}

/** The generated trend as line_id -> the 24 monthly amounts, oldest first, in cents. */
function seriesByLine(rows) {
  const byLine = new Map();
  for (const row of rows) {
    const seen = byLine.get(row.line_id) ?? new Map();
    seen.set(row.period, toCents(row.actual_amount));
    byLine.set(row.line_id, seen);
  }
  const out = new Map();
  for (const [lineId, months] of byLine) {
    assert.equal(months.size, PERIODS.length, `${lineId} does not carry all ${PERIODS.length} months`);
    out.set(lineId, PERIODS.map((p) => months.get(p)));
  }
  return out;
}

// ------------------------------------------------------- the rules, restated
// FIN-26 publishes the flux rule and FIN-37 already carries the budget
// threshold column. Both are recomputed below from their own stated terms, so
// this file agrees with the generator only when both are right.

/** The three numbers the FIN-26 spec states, pinned so a policy edit lands here. */
const FLUX_PCT_OF_PRIOR = 0.1;
const FLUX_FLOOR_CENTS = 10000 * 100;
const FLUX_ROUNDING_CENTS = 1000 * 100;

function fluxThreshold(priorPeriodCents) {
  const pct = Math.abs(priorPeriodCents) * FLUX_PCT_OF_PRIOR;
  return Math.max(FLUX_FLOOR_CENTS, Math.ceil(pct / FLUX_ROUNDING_CENTS) * FLUX_ROUNDING_CENTS);
}

/** A month at or above this multiple of the mean of its two neighbours is a peak. */
const PEAK_RATIO = 1.5;

function peakIndexes(values) {
  const peaks = [];
  for (let t = 1; t < values.length - 1; t += 1) {
    if (values[t] / ((values[t - 1] + values[t + 1]) / 2) >= PEAK_RATIO) peaks.push(t);
  }
  return peaks;
}

// --------------------------------------------------------- green before bytes
// These hold the contract the wave builds against, and they pass today.

test("FIN-33: the generator's column list and the spec agree before a byte exists", () => {
  assert.deepEqual(COLUMNS, specs.byId.get("FIN-33").columns);
});

test("FIN-33: the shape the two reconciliation rules have to hit is already fixed by frozen bytes", () => {
  const lines = templateLines();
  assert.equal(lines.length, 27, "the FIN-37 spine is no longer 27 lines, so 648 is the wrong row count");
  assert.equal(PERIODS.length, 24);
  assert.equal(PERIODS[0], "2024-04");
  assert.equal(PERIODS[23], "2026-03");
  assert.equal(lines.length * PERIODS.length, 648, "27 lines by 24 months is the whole file");

  // Rule 2 rests on the fiscal year being the calendar year, so a profit-and-loss
  // beginning balance at 2026-03-01 is exactly January plus February.
  const tb = new Map(buildTrialBalance().rows.map((r) => [r.account_code, r]));
  for (const line of lines) {
    const row = tb.get(line.account_code);
    assert.ok(row, `${line.line_id} names account ${line.account_code}, which FIN-05 does not carry`);
    assert.doesNotThrow(() => toCents(row.beginning_balance), `${line.account_code} has no parseable beginning balance`);
  }
});

// ----------------------------------------------------------------- the bytes

test("FIN-33: 648 rows, the 27 FIN-37 lines by the 24 month-ends, spine imported not retyped", () => {
  const rows = trend();
  assert.equal(rows.length, 648);
  assert.deepEqual([...new Set(rows.map((r) => r.period))].sort(), [...PERIODS].sort());

  // T-T3: the (line_id, account_code, account_name, statement_section,
  // normal_balance) spine, compared against FIN-37 row for row, so a template
  // edit lands here rather than drifting silently.
  const spine = ["line_id", "account_code", "account_name", "statement_section", "normal_balance"];
  const fromTrend = [];
  const seen = new Set();
  for (const row of rows) {
    if (seen.has(row.line_id)) continue;
    seen.add(row.line_id);
    fromTrend.push(Object.fromEntries(spine.map((c) => [c, row[c]])));
  }
  assert.deepEqual(fromTrend, templateLines().map((l) => Object.fromEntries(spine.map((c) => [c, l[c]]))));
  assert.equal(new Set(rows.map((r) => r.currency)).size, 1);
  assert.equal(rows[0].currency, "USD");
});

test("FIN-33 T-T1: every 2026-03 actual equals FIN-05's period movement to the cent", () => {
  // The shipped FIN-05 bytes, and this file's own arithmetic over them: period
  // debit less period credit on a debit-normal line, the reverse on a credit
  // one. Never the generator's helper, because a merged trazomo module already
  // prints four figures that depend on this exact convention.
  const tb = new Map(shipped("finance/gl-trial-balance", "gl-trial-balance.csv").map((r) => [r.account_code, r]));
  const march = trend().filter((r) => r.period === "2026-03");
  assert.equal(march.length, 27);
  for (const row of march) {
    const balance = tb.get(row.account_code);
    const debit = toCents(balance.period_debit);
    const credit = toCents(balance.period_credit);
    const movement = row.normal_balance === "debit" ? debit - credit : credit - debit;
    assert.equal(row.actual_amount, cents(movement), `${row.line_id} does not equal FIN-05's March movement`);
    // And the shared R-SIGN helper agrees with the arithmetic above, so FIN-24
    // and FIN-33 cannot part company over the convention.
    assert.equal(movement, actualAmountCents(balance, row.normal_balance), `${row.line_id}: R-SIGN convention 1 disagrees`);
  }
  // The FIN-24 leg of T-T1 lives in fin-24-actuals-vs-budget.test.js, because
  // FIN-24 does not exist when this wave runs.
});

test("FIN-33 T-T2 and T-T7: January plus February is the beginning balance, and all three months are the ending balance", () => {
  const tb = new Map(shipped("finance/gl-trial-balance", "gl-trial-balance.csv").map((r) => [r.account_code, r]));
  const rows = trend();
  const byAccount = new Map();
  for (const row of rows) {
    const seen = byAccount.get(row.account_code) ?? new Map();
    seen.set(row.period, toCents(row.actual_amount));
    byAccount.set(row.account_code, seen);
  }
  assert.equal(byAccount.size, 27);
  for (const [accountCode, months] of byAccount) {
    const balance = tb.get(accountCode);
    const opening = months.get("2026-01") + months.get("2026-02");
    assert.equal(cents(opening), balance.beginning_balance, `${accountCode}: January plus February is not the beginning balance`);
    const full = opening + months.get("2026-03");
    assert.equal(cents(full), balance.ending_balance, `${accountCode}: the quarter does not close at the ending balance`);

    // FIN-05 states an ending balance in the account's own direction and puts
    // the magnitude in exactly one of the two side columns. Assert the side
    // rather than the absolute value, which would hide a sign error.
    const side = balance.normal_balance === "debit" ? balance.ending_debit : balance.ending_credit;
    const other = balance.normal_balance === "debit" ? balance.ending_credit : balance.ending_debit;
    assert.equal(other, "", `${accountCode}: the quarter closes on the side its normal balance does not run on`);
    assert.equal(cents(full), side, `${accountCode}: the quarter does not close on its own side of the trial balance`);
  }
});

test("FIN-33 T-T4: exactly 3 lines breach the flux rule and exactly 1 of them also breaches the budget rule", () => {
  // The flux rule's three numbers are the ones FIN-26's spec states. Pinning
  // them to the spec text rather than to a comment is what makes a policy edit
  // fail here instead of moving the plant quietly.
  const fluxFeature = specs.byId.get("FIN-26").planted_features.find((f) => f.includes("flux rule"));
  assert.ok(fluxFeature, "FIN-26's spec no longer states a flux rule");
  assert.match(fluxFeature, /10 percent of the prior period/);
  assert.match(fluxFeature, /10000\.00 floor/);
  assert.match(fluxFeature, /same ceiling rounding as the budget rule/);

  const rows = trend();
  const series = seriesByLine(rows);
  const budget = new Map(templateLines().map((l) => [l.line_id, l]));

  const fluxBreach = [];
  const budgetBreach = [];
  const moves = [];
  for (const [lineId, values] of series) {
    const february = values[values.length - 2];
    const march = values[values.length - 1];
    const flux = march - february;
    if (flux !== 0) moves.push(lineId);
    if (Math.abs(flux) >= fluxThreshold(february)) fluxBreach.push(lineId);
    const line = budget.get(lineId);
    if (Math.abs(march - toCents(line.budget_amount)) >= toCents(line.explanation_threshold_usd)) {
      budgetBreach.push(lineId);
    }
  }

  // V2, both cardinalities: 3 under the rule, 27 with no threshold at all.
  assert.equal(fluxBreach.length, 3, `flux breaches: ${fluxBreach.join(", ")}`);
  assert.equal(moves.length, 27, "a line whose February and March are equal has no flux to threshold");
  // The budget set is the one FIN-37 and FIN-05 already produce, untouched.
  assert.equal(budgetBreach.length, 4, `budget-material lines: ${budgetBreach.join(", ")}`);

  // V3, both cardinalities: the two rules disagree on 5 lines, agree on 1, and
  // a reader who assumes they agree finds 0 disagreements.
  const both = fluxBreach.filter((l) => budgetBreach.includes(l));
  assert.equal(both.length, 1, `lines breaching both rules: ${both.join(", ")}`);
  const disagree = [...new Set([...fluxBreach, ...budgetBreach])].filter((l) => !both.includes(l));
  assert.equal(disagree.length, 5, `lines breaching exactly one rule: ${disagree.join(", ")}`);
  assert.notDeepEqual([...fluxBreach].sort(), [...budgetBreach].sort(), "the two rules cannot be assumed to agree");

  // The FIN-25 premise, re-derived here rather than assumed there: the account
  // set module 23 investigates is the 4 budget-material lines plus the 2
  // flux-only ones, and exactly 2 of those 6 carry a FIN-09 line. Neither
  // flux-only account carries one, which is what holds FIN-25's timing plant at
  // a single instance.
  const fluxOnly = fluxBreach.filter((l) => !both.includes(l));
  assert.equal(fluxOnly.length, 2);
  const accountFor = (lineId) => budget.get(lineId).account_code;
  const batchAccounts = new Set(shipped("finance/journal-entries-batch", "journal-entries-batch.csv").map((r) => r.gl_account));
  const investigated = [...budgetBreach, ...fluxOnly].map(accountFor);
  assert.equal(new Set(investigated).size, 6);
  assert.equal(fluxOnly.map(accountFor).filter((a) => batchAccounts.has(a)).length, 0);
  assert.equal(investigated.filter((a) => batchAccounts.has(a)).length, 2);
});

test("FIN-33 V25: exactly one line has a peak that repeats at 12-month spacing", () => {
  const series = seriesByLine(trend());

  // The rule: a month at or above 1.5 times the mean of its two neighbours is a
  // peak, and a line is seasonal when two of its peaks sit exactly 12 months
  // apart. A trailing-three-month run rate over-forecasts such a line for the
  // three months after the peak.
  const seasonal = [];
  const moving = [];
  for (const [lineId, values] of series) {
    const peaks = peakIndexes(values);
    if (peaks.some((t) => peaks.includes(t + 12))) seasonal.push(lineId);
    if (values.some((v, i) => i > 0 && v !== values[i - 1])) moving.push(lineId);
  }

  // Both cardinalities: 1 under the repeat rule, 27 with the repeat dropped and
  // only month-to-month movement left, which is why the repeat is the qualifier
  // that selects and the movement is not.
  assert.equal(seasonal.length, 1, `lines with a repeating annual peak: ${seasonal.join(", ")}`);
  assert.equal(moving.length, 27);

  // And the peak is a real over-forecast: the month after the second peak sits
  // well below the trailing three months that include it.
  const values = series.get(seasonal[0]);
  const peaks = peakIndexes(values);
  const second = peaks[peaks.length - 1];
  const trailing = (values[second] + values[second - 1] + values[second - 2]) / 3;
  assert.ok(values[second + 1] < trailing * 0.8, "the peak does not over-forecast the month that follows it");
});

// --------------------------------------------------------------- FIN-34

function driversConfig() {
  const files = generateArtifact(specs.byId.get("FIN-34"), canon);
  return { text: fileByPath(files, "drivers.yaml").content, parsed: yaml.load(fileByPath(files, "drivers.yaml").content) };
}

test("FIN-34: five drivers, three scenarios, and every applies_to resolving in a shipped file", () => {
  const { text, parsed } = driversConfig();
  for (const driver of DRIVER_IDS) assert.ok(text.includes(driver), `drivers.yaml does not carry ${driver}`);
  for (const scenario of SCENARIOS) assert.ok(text.includes(scenario), `drivers.yaml does not carry ${scenario}`);

  // The key list the spec pins, in the order it pins it.
  assert.deepEqual(Object.keys(parsed), ["base_period", "horizon_months", "source_artifacts", "scenarios", "drivers"]);
  assert.equal(parsed.base_period, "2026-03");
  assert.equal(parsed.horizon_months, 18);
  assert.deepEqual(parsed.scenarios, ["base", "upside", "downside"]);
  assert.deepEqual(parsed.drivers.map((d) => d.driver_id), DRIVER_IDS);
  for (const driver of parsed.drivers) {
    assert.deepEqual(Object.keys(driver).slice(0, 6), ["driver_id", "applies_to", "unit", "base", "upside", "downside"]);
  }

  // T-T5: every applies_to resolves to a FIN-33 line_id from the generated
  // bytes, or to a FIN-31 metric_id the FIN-31 spec names. FIN-31 is built
  // after FIN-33 in the DAG, so its spec entry is the only shipped statement of
  // its metric ids at this point; a renamed metric fails here.
  const lineIds = new Set(trend().map((r) => r.line_id));
  const fin31 = specs.byId.get("FIN-31").planted_features.join(" ");
  for (const driver of parsed.drivers) {
    assert.ok(driver.applies_to.length > 0, `${driver.driver_id} applies to nothing`);
    for (const target of driver.applies_to) {
      if (lineIds.has(target)) continue;
      assert.match(fin31, new RegExp(`\\b${target}\\b`), `${driver.driver_id} applies to "${target}", which is neither a FIN-33 line_id nor a FIN-31 metric_id`);
    }
  }
});

test("FIN-34 V23 and V24: one band crosses zero, one driver moves cash without moving margin", () => {
  const { parsed } = driversConfig();
  const lineIds = new Set(trend().map((r) => r.line_id));
  // A metric is a metric because the FIN-31 spec names it, not because it
  // failed to be a line_id. A driver pointing at a target no shipped file
  // carries moves nothing, so it must not count toward either cardinality.
  const fin31 = specs.byId.get("FIN-31").planted_features.join(" ");
  const isMetric = (t) => !lineIds.has(t) && new RegExp(`\\b${t}\\b`).test(fin31);
  const namesLine = (d) => d.applies_to.some((t) => lineIds.has(t));
  const namesMetric = (d) => d.applies_to.some(isMetric);

  for (const driver of parsed.drivers) {
    for (const target of driver.applies_to) {
      assert.ok(lineIds.has(target) || isMetric(target), `${driver.driver_id} applies to "${target}", which moves nothing`);
    }
  }

  // V23, both cardinalities: 1 band changes sign, 5 carry a band at all.
  const crossesZero = parsed.drivers.filter((d) => Math.sign(d.upside) * Math.sign(d.downside) < 0);
  const banded = parsed.drivers.filter((d) => !(d.base === d.upside && d.base === d.downside));
  assert.equal(crossesZero.length, 1, `driver bands that cross zero: ${crossesZero.map((d) => d.driver_id).join(", ")}`);
  assert.equal(banded.length, 5);

  // V24, both cardinalities: 1 driver names a metric and no line, 2 name a
  // metric at all, which is the count a reader gets who reads contract win and
  // loss as cash only.
  const cashOnly = parsed.drivers.filter((d) => namesMetric(d) && !namesLine(d));
  const anyMetric = parsed.drivers.filter(namesMetric);
  assert.equal(cashOnly.length, 1, `drivers moving cash without margin: ${cashOnly.map((d) => d.driver_id).join(", ")}`);
  assert.equal(anyMetric.length, 2, `drivers naming a metric: ${anyMetric.map((d) => d.driver_id).join(", ")}`);
});

test("FIN-34 T-T6: the derived cost per head recomputes from FIN-05 and CORE-04", () => {
  const { parsed } = driversConfig();
  const derived = parsed.drivers.find((d) => d.derivation);
  assert.ok(derived, "no driver publishes its derivation");
  assert.equal(derived.driver_id, "hiring");

  // This file's own arithmetic, over the shipped FIN-05 and CORE-04 bytes.
  const tb = new Map(shipped("finance/gl-trial-balance", "gl-trial-balance.csv").map((r) => [r.account_code, r]));
  let totalCents = 0;
  for (const account of derived.derivation.source_accounts) {
    const balance = tb.get(String(account));
    assert.ok(balance, `${account} is not a FIN-05 account`);
    assert.equal(balance.normal_balance, "debit", `${account} is not a cost account`);
    totalCents += toCents(balance.period_debit) - toCents(balance.period_credit);
  }
  const roster = shipped("core/people-roster", "people-roster.csv");
  const heads = roster.filter((r) => r.employment_status === "active" && r.start_date <= CLOSE_PERIOD_END).length;
  assert.equal(heads, derived.derivation.headcount);
  assert.equal(cents(Math.round(totalCents / heads)), derived.derivation.value_usd);

  // The judgment the spec requires the file to state plainly: one of the four
  // accounts is cost of revenue rather than operating expense.
  const blended = derived.derivation.source_accounts.map(String)
    .filter((a) => shipped("finance/chart-of-accounts", "chart-of-accounts.csv")
      .find((r) => r.account_code === a)?.subtype === "cost_of_revenue");
  assert.equal(blended.length, 1);
  assert.match(derived.derivation.judgment, /cost of revenue/);
  assert.match(derived.derivation.judgment, new RegExp(blended[0]));
});

test("FIN-33 and FIN-34 V19: no emitted file names the absent metric", () => {
  const emitted = [
    ...generateArtifact(specs.byId.get("FIN-33"), canon),
    ...generateArtifact(specs.byId.get("FIN-34"), canon),
  ];
  for (const file of emitted) {
    // FIN-34's own spec planted_features carry the word, which is why the scope
    // of this rule is the emitted datasets and never the repository.
    assert.ok(!/runway/i.test(file.content), `${file.path} names the metric the pack deliberately does not declare`);
  }
});
