// FIN-31 kpi-source-data and FIN-32 bank-balances.
//
// The rule this file follows: re-derive every plant and every tie-out from the
// generated bytes by its own stated rule, out of files that were frozen before
// either artifact existed, and never by importing the builder's own predicate.
// A test that imports the predicate it is checking cannot disagree with the
// generator. So the headcount rule, the subledger gap, the reconciling
// subtraction and both denominators of the metric the pack declines to declare
// are all recomputed here, in this file's own arithmetic.
//
// Every plant is asserted twice: the count under its stated rule, and the count
// with the one qualifier the rule names dropped. A qualifier that only one side
// knows about is a qualifier a later edit deletes silently.
//
// The mutation this file has to catch: a headcount rule that starts counting
// the departed rows, which moves every month in a 24-point series at once and
// looks perfectly plausible at any single date.
import { test } from "node:test";
import assert from "node:assert/strict";
import { join } from "node:path";
import { readFileSync } from "node:fs";
import { loadSpecs } from "../../datagen/src/specLoader.js";
import { loadCanonCompanies } from "../../datagen/src/canon.js";
import { generateArtifact } from "../../datagen/src/engine.js";
import { hasGenerator } from "../../datagen/src/generators/index.js";
import { csvTable, fileByPath } from "../helpers/csv-table.js";
import { buildTrialBalance } from "../../datagen/src/generators/fin-05-gl-trial-balance.js";
import {
  ABSENT_BY_DESIGN, BANK_BALANCE_COLUMNS, COLUMNS, METRIC_IDS, RECONCILED_CASH_ACCOUNT,
} from "../../datagen/src/generators/fin-31-kpi-source-data.js";
import { cents, toCents } from "../../datagen/src/money.js";
import { CLOSE_PERIOD_END, monthEnds, TREND_MONTHS } from "../../datagen/src/dates.js";

const REPO_ROOT = join(import.meta.dirname, "..", "..");
const specs = loadSpecs(join(REPO_ROOT, "specs", "artifact-specs.yaml"));
const canon = loadCanonCompanies(join(REPO_ROOT, "canon", "companies.md"));

const PERIOD_ENDS = monthEnds(TREND_MONTHS, CLOSE_PERIOD_END);

/** A shipped dataset's own committed bytes, read off disk rather than rebuilt. */
const shippedCsv = (dataset, file) =>
  csvTable(readFileSync(join(REPO_ROOT, "datasets", ...dataset.split("/"), file), "utf8"));
const shippedJson = (dataset, file) =>
  JSON.parse(readFileSync(join(REPO_ROOT, "datasets", ...dataset.split("/"), file), "utf8"));

const roster = () => csvTable(
  fileByPath(generateArtifact(specs.byId.get("CORE-04"), canon), "people-roster.csv").content
).rows;
const cashAccounts = () => buildTrialBalance().rows.filter((r) => r.subtype === "cash");

function kpiRows() {
  const table = csvTable(fileByPath(generateArtifact(specs.byId.get("FIN-31"), canon), "kpi-source-data.csv").content);
  assert.deepEqual(table.cols, specs.byId.get("FIN-31").columns, "FIN-31: header does not match spec.columns");
  return table.rows;
}

function bankRows() {
  const table = csvTable(fileByPath(generateArtifact(specs.byId.get("FIN-32"), canon), "bank-balances.csv").content);
  assert.deepEqual(table.cols, specs.byId.get("FIN-32").columns, "FIN-32: header does not match spec.columns");
  return table.rows;
}

// ------------------------------------------------- the contract, before bytes

test("FIN-31 and FIN-32: the generators' column lists and the specs agree, and both plot one series", () => {
  assert.deepEqual(COLUMNS, specs.byId.get("FIN-31").columns);
  assert.deepEqual(BANK_BALANCE_COLUMNS, specs.byId.get("FIN-32").columns);
  assert.equal(METRIC_IDS.length, 7);
  assert.equal(PERIOD_ENDS.length * METRIC_IDS.length, 168, "seven inputs by 24 month-ends");
  assert.equal(PERIOD_ENDS.length * cashAccounts().length, 96, "four cash accounts by 24 month-ends");
});

test("FIN-31 T-S2: the headcount rule is forced by CORE-04's own columns, and the series it produces", () => {
  const people = roster();
  assert.ok(!("termination_date" in people[0]), "CORE-04 gained a termination date, so excluding the departed is no longer forced");
  assert.ok(!Object.keys(people[0]).some((c) => /salary|compensation|pay_rate/.test(c)), "CORE-04 gained a salary column");
  const active = people.filter((r) => r.employment_status === "active");
  assert.equal(active.length, 582);
  assert.equal(people.filter((r) => r.employment_status === "departed").length, 18);
  const headcountAt = (periodEnd) => active.filter((r) => r.start_date <= periodEnd).length;
  assert.equal(headcountAt("2024-04-30"), 413, "the series no longer opens at 413");
  assert.equal(headcountAt("2026-03-31"), 582, "the series no longer closes at the full active roster");
  let previous = 0;
  for (const periodEnd of PERIOD_ENDS) {
    const value = headcountAt(periodEnd);
    assert.ok(value >= previous, `headcount fell at ${periodEnd}, which the rule cannot produce`);
    previous = value;
  }
});

test("FIN-31 T-S1: the five values frozen bytes pin at 2026-03-31", () => {
  const summary = JSON.parse(
    fileByPath(generateArtifact(specs.byId.get("FIN-04"), canon), "ar-aging-summary.json").content
  );
  assert.equal(summary.subledger_total, "3438041.42");
  assert.equal(summary.customer_count, 19);
  const tb = new Map(buildTrialBalance().rows.map((r) => [r.account_code, r]));
  assert.equal(tb.get("2300").ending_credit, "20031018.96", "deferred revenue current");
  assert.equal(tb.get("2310").ending_credit, "2263716.56", "deferred revenue non-current");
  // The subledger-only invoice: FIN-05's control account 1100 stands 17446.72
  // below FIN-04's subledger total, and computation_note has to say so rather
  // than hide it. Naming the AR figure is what makes days sales outstanding
  // single-method (plan U17).
  assert.equal(
    cents(toCents(summary.subledger_total) - toCents(tb.get("1100").ending_debit)),
    "17446.72"
  );
});

test("FIN-32 T-S3 and T-S4: both ends of the close, and the one account with a bank feed", () => {
  const accounts = cashAccounts();
  assert.deepEqual(accounts.map((a) => a.account_code), ["1010", "1020", "1030", "1050"]);
  const operating = accounts.find((a) => a.account_code === RECONCILED_CASH_ACCOUNT);
  assert.equal(operating.beginning_balance, "3482915.22", "the February anchor the canon timeline records");
  assert.equal(operating.ending_balance, "2740359.09");
  const statement = JSON.parse(
    fileByPath(generateArtifact(specs.byId.get("FIN-01"), canon), "bank-statement-summary.json").content
  );
  const bankEnding = statement.ending_balance ?? statement.closing_balance;
  assert.equal(String(bankEnding), "2806284.46", "FIN-01's bank-side ending balance moved");
  assert.equal(cents(toCents(String(bankEnding)) - toCents(operating.ending_balance)), "65925.37");

  // Not a two-item reconciliation: the twelve outstanding checks are less than
  // the difference, and FIN-03 carries no account attribution at all.
  const checks = csvTable(
    fileByPath(generateArtifact(specs.byId.get("FIN-03"), canon), "outstanding-checks.csv").content
  );
  assert.equal(checks.rows.length, 12);
  assert.equal(cents(checks.rows.reduce((sum, r) => sum + toCents(r.amount), 0)), "57212.36");
  assert.ok(!checks.cols.includes("gl_account"));
});

// ----------------------------------------------------------------- the bytes

test("FIN-31: 168 rows, seven inputs by the shared 24 month-ends", () => {
  const rows = kpiRows();
  assert.equal(rows.length, 168);
  assert.deepEqual([...new Set(rows.map((r) => r.period_end))].sort(), [...PERIOD_ENDS].sort());
  assert.deepEqual([...new Set(rows.map((r) => r.metric_id))].sort(), [...METRIC_IDS].sort());
  for (const metricId of METRIC_IDS) {
    const series = rows.filter((r) => r.metric_id === metricId);
    assert.equal(series.length, 24, `${metricId} is not a full series`);
    assert.deepEqual(series.map((r) => r.period_end), PERIOD_ENDS, `${metricId} is not in month order`);
    assert.equal(new Set(series.map((r) => r.metric_name)).size, 1, `${metricId} changes name mid series`);
    assert.equal(new Set(series.map((r) => r.unit)).size, 1, `${metricId} changes unit mid series`);
    // One column carries money and counts, so the unit is what says which, and
    // every cell has to parse under the unit its own row declares.
    for (const row of series) {
      if (row.unit === "usd") assert.match(row.value, /^\d+\.\d{2}$/, `${metricId} at ${row.period_end}`);
      else assert.match(row.value, /^[1-9]\d*$/, `${metricId} at ${row.period_end} is not a whole count`);
      assert.match(row.period_end, /^\d{4}-\d{2}-\d{2}$/);
      assert.notEqual(row.computation_note, "", `${metricId} at ${row.period_end} states no computation note`);
    }
    // A KPI input that never moves is a constant, not a series to plot.
    assert.ok(
      series.some((r, i) => i > 0 && r.value !== series[i - 1].value),
      `${metricId} does not move across the window`
    );
  }
});

test("FIN-31 T-S1: every value a frozen file pins, recomputed from that file's committed bytes", () => {
  const rows = kpiRows();
  const at = (metricId, periodEnd) => rows.find((r) => r.metric_id === metricId && r.period_end === periodEnd);

  // FIN-04's own summary, read off disk.
  const summary = shippedJson("finance/ar-aging-export", "ar-aging-summary.json");
  assert.equal(summary.as_of, CLOSE_PERIOD_END, "FIN-04 is no longer an as-of 2026-03-31 snapshot");
  assert.equal(
    at("ar_subledger_balance", CLOSE_PERIOD_END).value, summary.subledger_total,
    `ar_subledger_balance at ${CLOSE_PERIOD_END} does not equal FIN-04's subledger total`
  );
  assert.equal(
    at("ar_customer_count", CLOSE_PERIOD_END).value, String(summary.customer_count),
    `ar_customer_count at ${CLOSE_PERIOD_END} does not equal FIN-04's customer count`
  );

  // FIN-05's own bytes, at both ends of the close: beginning_balance is the
  // balance at the February month end and ending_balance the balance at the
  // March one, so the two deferred inputs are pinned twice rather than once.
  const tb = new Map(shippedCsv("finance/gl-trial-balance", "gl-trial-balance.csv").rows.map((r) => [r.account_code, r]));
  for (const [metricId, accountCode] of [["deferred_revenue_current", "2300"], ["deferred_revenue_noncurrent", "2310"]]) {
    const balance = tb.get(accountCode);
    assert.equal(balance.normal_balance, "credit", `${accountCode} is not credit normal`);
    assert.equal(balance.ending_debit, "", `${accountCode} closes on the side its normal balance does not run on`);
    assert.equal(at(metricId, CLOSE_PERIOD_END).value, balance.ending_balance, `${metricId} at the close`);
    assert.equal(at(metricId, "2026-02-28").value, balance.beginning_balance, `${metricId} at February`);
  }

  // CORE-04's own bytes at the close, by the rule the file publishes.
  const roster = shippedCsv("core/people-roster", "people-roster.csv").rows;
  const heads = (periodEnd) =>
    roster.filter((r) => r.employment_status === "active" && r.start_date <= periodEnd).length;
  assert.equal(at("headcount", CLOSE_PERIOD_END).value, String(heads(CLOSE_PERIOD_END)));

  // Five inputs pinned at the close is the qualified count; the qualifier the
  // rule names is the date, and with it dropped the pack pins 30 of the 168
  // rows: the two deferred inputs again at February, and headcount at all 24.
  const pinnedAtClose = rows.filter((r) => r.period_end === CLOSE_PERIOD_END && r.source_artifact !== "");
  assert.equal(pinnedAtClose.length, 5, `pinned at the close: ${pinnedAtClose.map((r) => r.metric_id).join(", ")}`);
  assert.equal(rows.filter((r) => r.source_artifact !== "").length, 30);

  // Plan U17, and the whole reason days sales outstanding is single-method
  // here: the subledger stands above FIN-05's own control account, and the note
  // states the difference rather than hiding it. Recomputed, never quoted.
  const gap = cents(toCents(summary.subledger_total) - toCents(tb.get("1100").ending_debit));
  assert.equal(gap, "17446.72");
  const note = at("ar_subledger_balance", CLOSE_PERIOD_END).computation_note;
  assert.ok(note.includes(gap), `the note does not state the ${gap} subledger difference`);
  assert.ok(note.includes("1100"), "the note does not name the control account it stands against");
});

test("FIN-31 T-S2: the headcount series is CORE-04's own rule at all 24 dates", () => {
  const roster = shippedCsv("core/people-roster", "people-roster.csv");
  assert.ok(!roster.cols.includes("termination_date"), "CORE-04 gained a termination date, so the exclusion stops being forced");
  const active = roster.rows.filter((r) => r.employment_status === "active");
  const departed = roster.rows.filter((r) => r.employment_status === "departed");
  assert.equal(departed.length, 18);

  const emitted = kpiRows().filter((r) => r.metric_id === "headcount");
  let previous = 0;
  for (const row of emitted) {
    const byRule = active.filter((r) => r.start_date <= row.period_end).length;
    assert.equal(row.value, String(byRule), `headcount at ${row.period_end}`);
    assert.ok(byRule >= previous, `the series falls at ${row.period_end}, which the rule cannot produce`);
    previous = byRule;

    // The mutation this file exists to catch: counting the departed rows moves
    // every month at once, so assert the wrong rule gives a different answer.
    const withDeparted = roster.rows.filter((r) => r.start_date <= row.period_end).length;
    assert.notEqual(String(withDeparted), row.value, `including the departed rows changes nothing at ${row.period_end}`);
  }
  assert.equal(emitted[0].value, "413", "the series no longer opens at the roster's own 2024-04-30 count");
  assert.equal(emitted[emitted.length - 1].value, String(active.length));
  assert.equal(new Set(emitted.map((r) => r.source_artifact)).size, 1);
  assert.equal(emitted[0].source_artifact, "CORE-04");
});

test("FIN-31: every source_artifact names a shipped id, and every source_reference resolves in it", () => {
  const rows = kpiRows();
  const sourced = rows.filter((r) => r.source_artifact !== "");
  const emittedFiles = new Map();
  for (const row of sourced) {
    const spec = specs.byId.get(row.source_artifact);
    assert.ok(spec, `${row.metric_id} at ${row.period_end} cites ${row.source_artifact}, which is not in the catalog`);
    assert.notEqual(row.source_reference, "", `${row.metric_id} at ${row.period_end} cites an artifact and no field in it`);
    if (!emittedFiles.has(row.source_artifact)) {
      emittedFiles.set(row.source_artifact, new Set(generateArtifact(spec, canon).map((f) => f.path)));
    }
    const file = row.source_reference.split(" ")[0];
    assert.ok(
      emittedFiles.get(row.source_artifact).has(file),
      `${row.source_artifact} emits no file called "${file}"`
    );
  }
  // A row with no source states so in both columns rather than in one.
  for (const row of rows.filter((r) => r.source_artifact === "")) {
    assert.equal(row.source_reference, "", `${row.metric_id} at ${row.period_end} cites a field with no artifact`);
  }
  // The two recurring-revenue inputs are the ones no frozen file carries at any
  // date, which is what the split between the three FP&A files leaves over.
  const unsourcedMetrics = [...new Set(rows.filter((r) => r.source_artifact === "").map((r) => r.metric_id))];
  assert.deepEqual(
    unsourcedMetrics.filter((m) => rows.filter((r) => r.metric_id === m).every((r) => r.source_artifact === "")).sort(),
    ["churned_arr", "new_arr"]
  );
});

test("FIN-32 T-S3: 96 rows, and every book balance tied to FIN-05's committed bytes at both ends of the close", () => {
  const rows = bankRows();
  assert.equal(rows.length, 96);
  const tb = new Map(
    shippedCsv("finance/gl-trial-balance", "gl-trial-balance.csv").rows
      .filter((r) => r.subtype === "cash").map((r) => [r.account_code, r])
  );
  assert.equal(tb.size, 4, "FIN-05 no longer carries four cash accounts, so 96 is the wrong row count");
  for (const [accountCode, balance] of tb) {
    const series = rows.filter((r) => r.account_code === accountCode);
    assert.equal(series.length, 24, `${accountCode} is not a full series`);
    assert.deepEqual(series.map((r) => r.period_end), PERIOD_ENDS, `${accountCode} is not in month order`);
    assert.equal(new Set(series.map((r) => r.account_name)).size, 1);
    assert.equal(series[0].account_name, balance.account_name, `${accountCode} does not carry FIN-05's own name`);
    const at = (periodEnd) => series.find((r) => r.period_end === periodEnd);
    assert.equal(at("2026-02-28").book_balance, balance.beginning_balance, `${accountCode} at 2026-02-28`);
    assert.equal(at(CLOSE_PERIOD_END).book_balance, balance.ending_balance, `${accountCode} at ${CLOSE_PERIOD_END}`);
    for (const row of series) {
      assert.match(row.book_balance, /^\d+\.\d{2}$/, `${accountCode} at ${row.period_end} is not a positive 2dp amount`);
    }
  }
  // Both ends pinned is the qualified count; with the qualifier dropped, the
  // other 22 months of each series are free and are constrained by continuity
  // alone, which is 88 of the 96 rows.
  assert.equal(rows.filter((r) => r.source_artifact !== "").length, 8);
  assert.equal(rows.filter((r) => r.source_artifact === "").length, 88);
});

test("FIN-32 T-S4: the one account with a bank feed, and the two ends FIN-01 pins", () => {
  const summary = shippedJson("finance/bank-transactions", "bank-statement-summary.json");
  assert.equal(summary.account.gl_account, RECONCILED_CASH_ACCOUNT, "FIN-01 is no longer the 1010 statement");
  const series = bankRows().filter((r) => r.account_code === RECONCILED_CASH_ACCOUNT);
  const at = (periodEnd) => series.find((r) => r.period_end === periodEnd);

  assert.equal(at(CLOSE_PERIOD_END).bank_balance, summary.ending_balance, "1010 at the close is not FIN-01's ending balance");
  assert.equal(at("2026-02-28").bank_balance, summary.opening_balance, "1010 at February is not FIN-01's opening balance");
  assert.equal(at("2026-02-28").reconciling_difference, "0.00", "the February reconciliation carries an item");
  assert.equal(
    at(CLOSE_PERIOD_END).reconciling_difference,
    cents(toCents(summary.ending_balance) - toCents(at(CLOSE_PERIOD_END).book_balance))
  );

  // Not a two-item reconciliation: FIN-03's twelve outstanding checks come to
  // less than the difference and FIN-03 carries no account attribution at all,
  // so the remainder is FIN-01's other reconciling items.
  const checks = shippedCsv("finance/outstanding-checks", "outstanding-checks.csv");
  assert.equal(checks.rows.length, 12);
  assert.ok(!checks.cols.includes("gl_account"));
  const checkTotal = checks.rows.reduce((sum, r) => sum + toCents(r.amount), 0);
  assert.ok(
    checkTotal < toCents(at(CLOSE_PERIOD_END).reconciling_difference),
    `the outstanding checks (${cents(checkTotal)}) now explain the whole difference`
  );

  // Exactly one month-end in the series closes with no carry-forward items, and
  // it is the one the canon timeline names. With the qualifier dropped, all 24
  // month-ends carry a difference column at all.
  const clean = series.filter((r) => r.reconciling_difference === "0.00");
  assert.equal(clean.length, 1, `month-ends with no carry-forward items: ${clean.map((r) => r.period_end).join(", ")}`);
  assert.equal(clean[0].period_end, "2026-02-28");
  assert.equal(series.length, 24);
});

test("FIN-32 T-S5: reconciling_difference is the subtraction its own columns state, on all 96 rows", () => {
  const rows = bankRows();
  for (const row of rows) {
    assert.equal(
      row.reconciling_difference,
      cents(toCents(row.bank_balance) - toCents(row.book_balance)),
      `${row.account_code} at ${row.period_end}`
    );
    if (row.account_code !== RECONCILED_CASH_ACCOUNT) {
      assert.equal(row.reconciling_difference, "0.00", `${row.account_code} has no bank feed, so it cannot carry a difference`);
      assert.equal(row.bank_balance, row.book_balance, `${row.account_code} at ${row.period_end}`);
    }
  }
  const march1010 = rows.find((r) => r.account_code === RECONCILED_CASH_ACCOUNT && r.period_end === CLOSE_PERIOD_END);
  assert.equal(march1010.bank_balance, "2806284.46");
  assert.equal(march1010.reconciling_difference, "65925.37");
});

test("FIN-32 P3: one account with a feed, three held at the bank, four cash accounts", () => {
  const rows = bankRows();
  const summary = shippedJson("finance/bank-transactions", "bank-statement-summary.json");
  const byAccount = new Map();
  for (const row of rows) byAccount.set(row.account_code, row);

  // Both cardinalities, three deep: the pack ships a statement for 1 account,
  // 3 are held at the canon bank, and FIN-05 carries 4 accounts with subtype
  // cash. Dropping the feed qualifier gives 3; dropping the bank qualifier too
  // gives 4, which is the count a reader takes without asking.
  const withFeed = [...byAccount.values()].filter((r) => r.account_code === summary.account.gl_account);
  const heldAtBank = [...byAccount.values()].filter((r) => r.bank_canon_id !== "");
  assert.equal(withFeed.length, 1);
  assert.equal(heldAtBank.length, 3, `held at a bank: ${heldAtBank.map((r) => r.account_code).join(", ")}`);
  assert.equal(byAccount.size, 4);

  // The three that are held at a bank name the canon bank and nothing else, and
  // their masked numbers are FIN-01's own rather than three new inventions.
  const feed = shippedCsv("finance/bank-transactions", "bank-transactions.csv").rows;
  const maskedIn = (pattern) => {
    const found = new Set();
    for (const row of feed) {
      const match = pattern.exec(row.description);
      if (match) found.add(match[1]);
    }
    assert.equal(found.size, 1, `FIN-01's feed names ${found.size} masked numbers for ${pattern}`);
    return [...found][0];
  };
  assert.equal(byAccount.get("1010").account_number_masked, summary.account.number_masked);
  assert.equal(byAccount.get("1020").account_number_masked, maskedIn(/TRANSFER TO PAYROLL ACCT (XXXX-\d{4})/));
  assert.equal(byAccount.get("1030").account_number_masked, maskedIn(/TRANSFER FROM MONEY MARKET (XXXX-\d{4})/));
  assert.equal(new Set(heldAtBank.map((r) => r.account_number_masked)).size, 3);
  for (const row of heldAtBank) {
    assert.equal(row.bank_canon_id, summary.bank.canon_id, `${row.account_code} names a different bank`);
    assert.equal(row.bank_name, summary.bank.name);
    assert.ok(canon.has(row.bank_canon_id), `${row.bank_canon_id} is not a canon company`);
  }
  // The fourth is cash on hand: no bank, no masked number, and it says so by
  // leaving the columns empty rather than by inventing a fourth bank feed.
  const onHand = [...byAccount.values()].filter((r) => r.bank_canon_id === "");
  assert.equal(onHand.length, 1);
  assert.equal(onHand[0].bank_name, "");
  assert.equal(onHand[0].account_number_masked, "");
});

test("FIN-31 and FIN-32 V20, V21 and V22: every input both readings need is emitted, and no reading is", () => {
  const kpi = kpiRows();
  const bank = bankRows();
  const at = (rows, key, value) => rows.filter((r) => r[key] === value);
  const totalCash = (periodEnd) =>
    at(bank, "period_end", periodEnd).reduce((sum, r) => sum + toCents(r.book_balance), 0);

  // V22, both cardinalities: the numerator has two defensible readings, all
  // four cash accounts against the one account the pack ships a statement for.
  // Drop the qualifier and take FIN-05's subtype at face value and there is 1.
  const allFour = totalCash(CLOSE_PERIOD_END);
  const operatingAlone = toCents(
    bank.find((r) => r.account_code === RECONCILED_CASH_ACCOUNT && r.period_end === CLOSE_PERIOD_END).book_balance
  );
  assert.equal(new Set([allFour, operatingAlone]).size, 2, "the account choice no longer changes the answer");
  // The qualifier-free reading takes FIN-05's subtype at face value and pools
  // every cash account. Counting the subtypes of the rows the subtype filter
  // selected is a tautology, so the contrast is counted over the emitted FIN-32
  // rows instead: they group into 4 account_codes, and exactly 1 of the 4
  // carries the bank feed the pack actually ships.
  const emittedAccounts = new Set(bank.map((r) => r.account_code));
  const feedAccount = shippedJson("finance/bank-transactions", "bank-statement-summary.json").account.gl_account;
  const withFeed = [...emittedAccounts].filter((code) => code === feedAccount);
  assert.equal(emittedAccounts.size, 4, "the pooled reading no longer covers four accounts");
  assert.equal(withFeed.length, 1, "a second bank feed would make the account choice a lookup rather than a judgment");
  assert.equal(withFeed[0], RECONCILED_CASH_ACCOUNT, "the account the pack reconciles is not the one with the feed");
  assert.equal(cents(allFour), "30632542.04");

  // V20, both cardinalities: two denominators the pack supports, and no file
  // declaring which. One of the two is computable from FIN-32 alone, which is
  // the count a reader gets who assumes the term is defined.
  const netCashChange = totalCash("2026-02-28") - allFour;
  const netLoss = toCents(
    shippedCsv("finance/gl-trial-balance", "gl-trial-balance.csv").rows
      .find((r) => r.account_code === "3200").period_debit
  );
  const denominators = [
    { name: "net cash change", cents: netCashChange, fromCashAlone: true },
    { name: "net loss", cents: netLoss, fromCashAlone: false },
  ];
  // Both denominators are checked against the cells they come out of, not
  // against the shape of the array that holds them. Net cash change is a
  // difference of two emitted FIN-32 book columns and its opening side ties to
  // FIN-05's cash beginning balances; net loss is a FIN-05 cell that appears
  // nowhere in FIN-32, which is what makes only one of the two reachable from
  // cash alone.
  const openingCash = totalCash("2026-02-28");
  assert.equal(at(bank, "period_end", "2026-02-28").length, 4, "the opening side is no longer four emitted rows");
  assert.equal(netCashChange, openingCash - allFour, "the net cash change left FIN-32's own columns");
  assert.equal(
    openingCash,
    cashAccounts().reduce((sum, r) => sum + toCents(r.beginning_balance), 0),
    "FIN-32's opening cash no longer ties to FIN-05's beginning balances"
  );
  const bankCells = new Set(bank.flatMap((r) => [r.book_balance, r.bank_balance, r.reconciling_difference]));
  assert.ok(
    !bankCells.has(cents(netLoss)),
    "FIN-32 now carries the net loss, so the second denominator is no longer a second file"
  );
  assert.equal(
    denominators.filter((d) => d.fromCashAlone).length, 1,
    "exactly one denominator is reachable from the cash file alone"
  );
  for (const denominator of denominators) assert.ok(denominator.cents > 0, `${denominator.name} is not a positive burn`);
  assert.equal(cents(netCashChange), "921297.54");
  assert.equal(cents(netLoss), "1768047.78");
  // Two denominators against one numerator is two different answers, and the
  // gap between them is not a rounding difference.
  const months = denominators.map((d) => Math.round((allFour / d.cents) * 10) / 10);
  assert.equal(new Set(months).size, 2, "the two methods no longer disagree");
  assert.ok(Math.abs(months[0] - months[1]) > 1, `the two methods differ by ${Math.abs(months[0] - months[1])} months`);

  // V21, both cardinalities: exactly one FIN-31 caption stands against cash and
  // makes a third reading, and a reader who never opens the balance sheet finds
  // none, because FIN-32 carries no liability at all.
  const tb = new Map(shippedCsv("finance/gl-trial-balance", "gl-trial-balance.csv").rows.map((r) => [r.account_code, r]));
  const liabilityBacked = at(kpi, "period_end", CLOSE_PERIOD_END).filter((row) => {
    if (row.source_artifact !== "FIN-05") return false;
    const account = tb.get(row.source_reference.split(" ")[2]);
    return account?.type === "liability";
  });
  assert.equal(liabilityBacked.length, 2, "the two deferred revenue components");
  const captions = new Set(liabilityBacked.map((r) => r.metric_id.replace(/_(current|noncurrent)$/, "")));
  assert.equal(captions.size, 1, `captions standing against cash: ${[...captions].join(", ")}`);
  const deferred = liabilityBacked.reduce((sum, r) => sum + toCents(r.value), 0);
  assert.equal(cents(deferred), "22294735.52");
  assert.ok(deferred < allFour, "the caveat only bites while cash stands above the contract liability");
  assert.equal(
    bank.filter((r) => Object.keys(r).some((c) => /liabilit|deferred/.test(c))).length, 0,
    "FIN-32 now carries a liability, so the third reading no longer needs the balance sheet"
  );
});

test("FIN-31 and FIN-32: the committed bytes are the generated bytes, row for row", () => {
  // The byte guard `validate` runs, restated as a test so a hand edit to either
  // committed file fails the suite naming the row it landed on.
  for (const [dataset, file, rows, key] of [
    ["finance/kpi-source-data", "kpi-source-data.csv", kpiRows(), (r) => `${r.metric_id} ${r.period_end}`],
    ["finance/bank-balances", "bank-balances.csv", bankRows(), (r) => `${r.account_code} ${r.period_end}`],
  ]) {
    const committed = shippedCsv(dataset, file).rows;
    assert.equal(committed.length, rows.length, `${file}: the committed row count moved`);
    for (const [i, row] of rows.entries()) {
      assert.deepEqual(committed[i], row, `${file} row ${key(row)} was edited by hand`);
    }
  }
});

test("FIN-31 and FIN-32 T-S6 and V19: no emitted file names the absent metric", () => {
  const built = ["FIN-29", "FIN-31", "FIN-32", "FIN-33", "FIN-34"].filter((specId) => hasGenerator(specId));
  assert.ok(built.includes("FIN-31") && built.includes("FIN-32"), "this wave's own ids are not registered");
  const emitted = built.flatMap((specId) => generateArtifact(specs.byId.get(specId), canon));
  for (const file of emitted) {
    assert.ok(
      !new RegExp(ABSENT_BY_DESIGN, "i").test(file.content),
      `${file.path} names the metric the pack deliberately does not declare`
    );
  }
  // The scope is the emitted datasets and never the repository: FIN-31's own
  // spec planted_features carry the word, and so does FIN-34's. Both
  // cardinalities: 0 emitted files name it, and the catalog names it twice,
  // which is why a repository-wide assertion would fail on D5's own work.
  const catalog = readFileSync(join(REPO_ROOT, "specs", "artifact-specs.yaml"), "utf8");
  assert.equal(catalog.match(new RegExp(ABSENT_BY_DESIGN, "gi")).length, 2);
});
