// FIN-35 inbound-requests-queue: the untriaged finance inbox module 11 routes.
//
// The queue's whole value is that every row points at something real, so this
// file re-resolves each pointer against the artifact it claims to name: a
// vendor invoice against buildProcureToPay()'s invoices, an expense report
// against buildExpenseReports(), and the cross-track row against the CORE-02
// invoice.json the pack already ships. A FIN-07 or FIN-13 reroll that leaves a
// queue row pointing at a document that no longer exists fails here.
//
// The three plants are re-derived from the generated bytes by their own rules
// and never by naming the row that carries them: the missing field by looking
// for the one column its own request_type otherwise always fills, the duplicate
// by the (counterparty, document, amount) tuple, and the routing boundary by
// looking for the one counterparty that is neither an AP vendor nor an employee.
import { test } from "node:test";
import assert from "node:assert/strict";
import { join } from "node:path";
import { loadSpecs } from "../../datagen/src/specLoader.js";
import { loadCanonCompanies } from "../../datagen/src/canon.js";
import { generateArtifact } from "../../datagen/src/engine.js";
import { csvTable, fileByPath } from "../helpers/csv-table.js";
import { buildProcureToPay } from "../../datagen/src/generators/fin-06-procure-to-pay.js";
import { buildExpenseReports } from "../../datagen/src/generators/fin-13-expense-reports.js";
import { buildDecisionAuthorityMatrix } from "../../datagen/src/generators/fin-39-decision-authority-matrix.js";
import { financeRoster } from "../../datagen/src/generators/finance-roles.js";
import { generate as generateInvoice } from "../../datagen/src/generators/core-02-invoice.js";
import { createRng } from "../../datagen/src/seed.js";
import { diffDays } from "../../datagen/src/dates.js";
import {
  CHANNELS, REQUEST_TYPES, QUEUE_PERIOD, QUEUE_STATUS, TARGET_ROWS,
  VENDOR_INVOICE_COUNT, EXPENSE_REPORT_COUNT, VENDOR_REQUEST_COUNT,
  ROUTING_DECISION_ID, VENDOR_MASTER_DECISION_ID, VENDOR_POOL,
} from "../../datagen/src/generators/fin-35-inbound-queue.js";

const REPO_ROOT = join(import.meta.dirname, "..", "..");
const specs = loadSpecs(join(REPO_ROOT, "specs", "artifact-specs.yaml"));
const canon = loadCanonCompanies(join(REPO_ROOT, "canon", "companies.md"));
const spec = specs.byId.get("FIN-35");
const OUTPUT_FILE = "inbound-requests-queue.csv";

const roster = financeRoster();
const employee = (employeeId) => roster.find((r) => r.employee_id === employeeId);
const cents = (money) => Math.round(Number(money) * 100);

const { invoices } = buildProcureToPay();
const invoiceRowsByNumber = (() => {
  const out = new Map();
  for (const row of invoices) {
    if (!out.has(row.invoice_number)) out.set(row.invoice_number, []);
    out.get(row.invoice_number).push(row);
  }
  return out;
})();

const expenseReports = (() => {
  const out = new Map();
  for (const row of buildExpenseReports()) {
    if (!out.has(row.report_id)) out.set(row.report_id, row);
  }
  return out;
})();

/** The shipped CORE-02 invoice, read from the generator rather than retyped. */
const outsideCounselInvoice = JSON.parse(
  generateInvoice({ rng: (stream) => createRng("CORE-02", stream) })
    .find((f) => f.path === "invoice.json").content
);

const vendorIds = new Set(VENDOR_POOL.map((v) => v.canon_id));

function queue() {
  assert.ok(spec, "FIN-35 not found in specs/artifact-specs.yaml");
  const files = generateArtifact(spec, canon);
  const table = csvTable(fileByPath(files, OUTPUT_FILE).content);
  assert.deepEqual(table.cols, spec.columns, "FIN-35: header does not match spec.columns");
  return table.rows;
}

const byType = (rows, type) => rows.filter((r) => r.request_type === type);

// ------------------------------------------------------------------ the shape

test("FIN-35: thirty-eight requests, uniquely numbered, received inside the intake window", () => {
  const rows = queue();
  assert.equal(rows.length, TARGET_ROWS, `the queue is ${rows.length} deep, expected ${TARGET_ROWS}`);
  assert.equal(new Set(rows.map((r) => r.request_id)).size, rows.length, "request_id repeats");
  for (const row of rows) {
    assert.match(row.request_id, /^REQ-2026-0\d{3}$/, `${row.request_id} is not in the REQ-2026-0NNN series`);
    assert.ok(CHANNELS.includes(row.channel), `${row.request_id} arrived on channel "${row.channel}"`);
    assert.ok(REQUEST_TYPES.includes(row.request_type), `${row.request_id} is a "${row.request_type}"`);
    assert.ok(
      row.received_date >= QUEUE_PERIOD.start && row.received_date <= QUEUE_PERIOD.end,
      `${row.request_id} was received on ${row.received_date}, outside the intake window`
    );
    assert.ok(Number(row.attachment_count) >= 1, `${row.request_id} arrived with nothing attached`);
    assert.equal(
      row.currency === "USD", row.amount !== "",
      `${row.request_id} disagrees with itself about whether an amount is on the table`
    );
  }
  for (const channel of CHANNELS) {
    assert.ok(rows.some((r) => r.channel === channel), `nothing arrived on "${channel}", so the column decides nothing`);
  }
  assert.equal(byType(rows, "vendor_invoice").length, VENDOR_INVOICE_COUNT + 1, "the vendor-invoice block is not the sixteen invoices plus the resend");
  assert.equal(byType(rows, "expense_report").length, EXPENSE_REPORT_COUNT);
  assert.equal(byType(rows, "vendor_request").length, VENDOR_REQUEST_COUNT);
  assert.equal(byType(rows, "other").length, 1, "more than one request resists classification");
});

test("FIN-35: the queue is untriaged, so status is pending_classification on every row", () => {
  for (const row of queue()) {
    assert.equal(
      row.status, QUEUE_STATUS,
      `${row.request_id} has already been classified, which makes routing a post mortem`
    );
  }
  assert.equal(
    QUEUE_STATUS, outsideCounselInvoice.finance_queue_status,
    "the queue's own status does not match the one the shipped CORE-02 invoice says it is waiting in"
  );
});

test("FIN-35: every submitter is an active CORE-04 employee and names their own department", () => {
  for (const row of queue()) {
    const person = employee(row.submitter_employee_id);
    assert.ok(person, `${row.request_id}: ${row.submitter_employee_id} is not on the CORE-04 roster`);
    assert.equal(person.employment_status, "active", `${row.request_id}: the submitter is not active`);
    assert.equal(
      row.submitter_department, person.department,
      `${row.request_id} claims a department its submitter does not work in`
    );
  }
});

test("FIN-35: every counterparty is a screened vendor, the outside-counsel firm, or the employee who submitted the row", () => {
  const screened = new Map(VENDOR_POOL.map((v) => [v.canon_id, v.name]));
  screened.set(outsideCounselInvoice.law_firm_id, canon.get(outsideCounselInvoice.law_firm_id).name);
  for (const row of queue()) {
    if (row.counterparty_canon_id !== "") {
      assert.ok(
        screened.has(row.counterparty_canon_id),
        `${row.request_id} names ${row.counterparty_canon_id}, which is not a screened counterparty`
      );
      assert.equal(
        row.counterparty_name, screened.get(row.counterparty_canon_id),
        `${row.request_id} calls ${row.counterparty_canon_id} something canon does not`
      );
      continue;
    }
    const person = employee(row.submitter_employee_id);
    assert.equal(
      row.counterparty_name, `${person.first_name} ${person.last_name}`,
      `${row.request_id} has no counterparty id and names someone other than its own submitter`
    );
  }
});

// ------------------------------------------------------------------ the joins

test("FIN-35: every vendor_invoice resolves to exactly one FIN-07 invoice number, with the amounts agreeing to the cent", () => {
  const rows = byType(queue(), "vendor_invoice");
  for (const row of rows) {
    const matches = invoiceRowsByNumber.get(row.reference_document);
    assert.ok(matches, `${row.request_id} cites ${row.reference_document}, which FIN-07 does not carry`);
    assert.equal(
      matches.length, 1,
      `${row.request_id} cites ${row.reference_document}, which FIN-07 carries more than once, so the queue row does not resolve`
    );
    const [invoice] = matches;
    assert.equal(cents(row.amount), cents(invoice.invoice_amount), `${row.request_id} disagrees with FIN-07 about the amount`);
    assert.equal(row.counterparty_canon_id, invoice.vendor_canon_id, `${row.request_id} bills the wrong vendor`);
    assert.equal(row.po_number, invoice.po_number, `${row.request_id} cites a purchase order FIN-07 does not`);
    assert.ok(
      row.received_date >= invoice.received_date,
      `${row.request_id} reached the queue before AP received the invoice it names`
    );
    if (row.due_date === "") continue;
    assert.equal(row.due_date, invoice.due_date, `${row.request_id} disagrees with FIN-07 about when payment is due`);
  }
  assert.equal(
    new Set(rows.map((r) => r.reference_document)).size, VENDOR_INVOICE_COUNT,
    "the queue does not name sixteen distinct vendor invoices"
  );
});

test("FIN-35: every expense_report resolves to a FIN-13 report whose report_total is the queued amount", () => {
  const rows = byType(queue(), "expense_report");
  assert.equal(new Set(rows.map((r) => r.reference_document)).size, rows.length, "one expense report is queued twice");
  for (const row of rows) {
    const report = expenseReports.get(row.reference_document);
    assert.ok(report, `${row.request_id} cites ${row.reference_document}, which FIN-13 does not carry`);
    assert.equal(cents(row.amount), cents(report.report_total), `${row.request_id} disagrees with FIN-13 about the report total`);
    assert.equal(
      row.submitter_employee_id, report.employee_id,
      `${row.request_id} was queued under someone other than the employee whose report it is`
    );
    assert.ok(
      row.received_date >= report.report_submitted_date,
      `${row.request_id} reached the queue before the report it names was submitted`
    );
    assert.equal(row.po_number, "", `${row.request_id} cites a purchase order for an expense report`);
    assert.equal(row.counterparty_canon_id, "", `${row.request_id} bills an expense report to a company`);
  }
});

test("FIN-35: the routing authority the module prints is the shipped FIN-39 row, not a restatement of it", () => {
  const row = buildDecisionAuthorityMatrix().find((r) => r.control_id === ROUTING_DECISION_ID);
  assert.ok(row, `${ROUTING_DECISION_ID} is not a control_id in the shipped FIN-39 matrix`);
  assert.match(row.decision, /inbound finance request for routing/i, "the cited row does not decide how an inbound request is routed");
  assert.equal(row.ai_autonomy_level, "autonomous", "classifying a request for routing is no longer an autonomous decision");
  assert.equal(row.moves_money_or_posts, "false", "classifying a request for routing now moves money");

  const amend = buildDecisionAuthorityMatrix().find((r) => r.control_id === VENDOR_MASTER_DECISION_ID);
  assert.ok(amend, `${VENDOR_MASTER_DECISION_ID} is not a control_id in the shipped FIN-39 matrix`);
  assert.match(amend.decision, /vendor master record/i, "the vendor requests in the queue are decided under a row about something else");
  assert.equal(
    amend.ai_autonomy_level, "approval_before_action",
    "amending a vendor master record no longer needs approval, which is the whole reason these rows are queued"
  );
});

// ---------------------------------------------------------------- the plants

test("FIN-35: exactly one row leaves empty a cell every other row of its own request_type fills", () => {
  const rows = queue();
  const gaps = [];
  for (const type of REQUEST_TYPES) {
    const group = byType(rows, type);
    if (group.length < 2) continue; // a group of one makes "every other row" vacuous
    for (const column of spec.columns) {
      const empty = group.filter((r) => r[column] === "");
      if (empty.length === 1) gaps.push({ type, column, request_id: empty[0].request_id });
    }
  }
  assert.equal(
    gaps.length, 1,
    `${gaps.length} rows are missing a field their own request_type otherwise always carries: ${JSON.stringify(gaps)}`
  );
});

test("FIN-35: exactly one pair of rows is the same submission twice", () => {
  const rows = queue();
  const seen = new Map();
  for (const row of rows) {
    const key = [row.counterparty_canon_id, row.reference_document, row.amount].join("|");
    if (row.reference_document === "") continue; // a request with nothing to point at cannot duplicate one
    seen.set(key, [...(seen.get(key) ?? []), row]);
  }
  const duplicates = [...seen.values()].filter((group) => group.length > 1);
  assert.equal(duplicates.length, 1, `${duplicates.length} submissions arrived twice, expected 1`);
  const [pair] = duplicates;
  assert.equal(pair.length, 2, "the duplicate submission arrived more than twice");
  const [first, second] = [...pair].sort((a, b) => (a.received_date < b.received_date ? -1 : 1));
  assert.notEqual(first.request_id, second.request_id, "the duplicate pair shares a request id");
  assert.notEqual(first.channel, second.channel, "the duplicate arrived on the same channel both times, so nothing distinguishes the copies");
  const apart = diffDays(first.received_date, second.received_date);
  assert.ok(apart >= 1 && apart <= 3, `the duplicate arrived ${apart} days after the original, expected 1 to 3`);
});

test("FIN-35: exactly one request names a counterparty that is neither an AP vendor nor an employee, and it is the outside-counsel invoice", () => {
  const rows = queue();
  const outside = rows.filter((r) => r.counterparty_canon_id !== "" && !vendorIds.has(r.counterparty_canon_id));
  assert.equal(outside.length, 1, `${outside.length} requests name a counterparty finance cannot route on its own, expected 1`);
  const [row] = outside;
  assert.equal(row.counterparty_canon_id, outsideCounselInvoice.law_firm_id, "the unroutable request does not come from the outside-counsel firm");
  assert.equal(row.reference_document, outsideCounselInvoice.invoice_number, "the unroutable request does not cite the CORE-02 invoice number");
  assert.equal(
    cents(row.amount), Math.round(outsideCounselInvoice.invoice_total * 100),
    "the unroutable request disagrees with the CORE-02 invoice about the amount"
  );
  assert.ok(
    row.subject.includes(outsideCounselInvoice.matter_id),
    `the unroutable request does not cite matter ${outsideCounselInvoice.matter_id}`
  );
  assert.ok(
    row.received_date >= outsideCounselInvoice.invoice_date,
    "the unroutable request reached the queue before the invoice it names was raised"
  );
  assert.equal(
    invoiceRowsByNumber.has(row.reference_document), false,
    "the outside-counsel invoice also sits in the AP invoice file, so finance could route it after all"
  );
});

// ---------------------------------------------------------------- determinism

test("FIN-35: two runs of the generator produce identical bytes", () => {
  const runA = generateArtifact(spec, canon);
  const runB = generateArtifact(spec, canon);
  assert.deepEqual(runA.map((f) => f.path), runB.map((f) => f.path));
  for (let i = 0; i < runA.length; i += 1) {
    assert.equal(runA[i].content, runB[i].content, `${runA[i].path} differs between runs`);
  }
});
