// FIN-31 kpi-source-data and FIN-32 bank-balances.
//
// The rule this file follows: re-derive every plant and every tie-out from the
// generated bytes by its own stated rule, out of files that were frozen before
// either artifact existed, and never by importing the builder's own predicate.
// A test that imports the predicate it is checking cannot disagree with the
// generator. So the headcount rule, the subledger gap, the reconciling
// subtraction and both denominators of the metric the pack declines to declare
// are all recomputed here, in this file's own arithmetic.
//
// Every plant is asserted twice: the count under its stated rule, and the count
// with the one qualifier the rule names dropped. A qualifier that only one side
// knows about is a qualifier a later edit deletes silently.
//
// The mutation this file has to catch: a headcount rule that starts counting
// the departed rows, which moves every month in a 24-point series at once and
// looks perfectly plausible at any single date.
import { test } from "node:test";
import assert from "node:assert/strict";
import { join } from "node:path";
import { readFileSync } from "node:fs";
import { loadSpecs } from "../../datagen/src/specLoader.js";
import { loadCanonCompanies } from "../../datagen/src/canon.js";
import { generateArtifact } from "../../datagen/src/engine.js";
import { csvTable, fileByPath } from "../helpers/csv-table.js";
import { buildTrialBalance } from "../../datagen/src/generators/fin-05-gl-trial-balance.js";
import {
  ABSENT_BY_DESIGN, BANK_BALANCE_COLUMNS, COLUMNS, METRIC_IDS, RECONCILED_CASH_ACCOUNT,
} from "../../datagen/src/generators/fin-31-kpi-source-data.js";
import { cents, toCents } from "../../datagen/src/money.js";
import { CLOSE_PERIOD_END, monthEnds, TREND_MONTHS } from "../../datagen/src/dates.js";

const WAVE = "D5a wave 1 (plan Task 7) builds FIN-31 and FIN-32 after FIN-33 and deletes this marker";

const REPO_ROOT = join(import.meta.dirname, "..", "..");
const specs = loadSpecs(join(REPO_ROOT, "specs", "artifact-specs.yaml"));
const canon = loadCanonCompanies(join(REPO_ROOT, "canon", "companies.md"));

const PERIOD_ENDS = monthEnds(TREND_MONTHS, CLOSE_PERIOD_END);

/** A shipped dataset's own committed bytes, read off disk rather than rebuilt. */
const shippedCsv = (dataset, file) =>
  csvTable(readFileSync(join(REPO_ROOT, "datasets", ...dataset.split("/"), file), "utf8"));
const shippedJson = (dataset, file) =>
  JSON.parse(readFileSync(join(REPO_ROOT, "datasets", ...dataset.split("/"), file), "utf8"));

const roster = () => csvTable(
  fileByPath(generateArtifact(specs.byId.get("CORE-04"), canon), "people-roster.csv").content
).rows;
const cashAccounts = () => buildTrialBalance().rows.filter((r) => r.subtype === "cash");

function kpiRows() {
  const table = csvTable(fileByPath(generateArtifact(specs.byId.get("FIN-31"), canon), "kpi-source-data.csv").content);
  assert.deepEqual(table.cols, specs.byId.get("FIN-31").columns, "FIN-31: header does not match spec.columns");
  return table.rows;
}

function bankRows() {
  const table = csvTable(fileByPath(generateArtifact(specs.byId.get("FIN-32"), canon), "bank-balances.csv").content);
  assert.deepEqual(table.cols, specs.byId.get("FIN-32").columns, "FIN-32: header does not match spec.columns");
  return table.rows;
}

// --------------------------------------------------------- green before bytes

test("FIN-31 and FIN-32: the generators' column lists and the specs agree, and both plot one series", () => {
  assert.deepEqual(COLUMNS, specs.byId.get("FIN-31").columns);
  assert.deepEqual(BANK_BALANCE_COLUMNS, specs.byId.get("FIN-32").columns);
  assert.equal(METRIC_IDS.length, 7);
  assert.equal(PERIOD_ENDS.length * METRIC_IDS.length, 168, "seven inputs by 24 month-ends");
  assert.equal(PERIOD_ENDS.length * cashAccounts().length, 96, "four cash accounts by 24 month-ends");
});

test("FIN-31 T-S2: the headcount rule is forced by CORE-04's own columns, and the series it produces", () => {
  const people = roster();
  assert.ok(!("termination_date" in people[0]), "CORE-04 gained a termination date, so excluding the departed is no longer forced");
  assert.ok(!Object.keys(people[0]).some((c) => /salary|compensation|pay_rate/.test(c)), "CORE-04 gained a salary column");
  const active = people.filter((r) => r.employment_status === "active");
  assert.equal(active.length, 582);
  assert.equal(people.filter((r) => r.employment_status === "departed").length, 18);
  const headcountAt = (periodEnd) => active.filter((r) => r.start_date <= periodEnd).length;
  assert.equal(headcountAt("2024-04-30"), 413, "the series no longer opens at 413");
  assert.equal(headcountAt("2026-03-31"), 582, "the series no longer closes at the full active roster");
  let previous = 0;
  for (const periodEnd of PERIOD_ENDS) {
    const value = headcountAt(periodEnd);
    assert.ok(value >= previous, `headcount fell at ${periodEnd}, which the rule cannot produce`);
    previous = value;
  }
});

test("FIN-31 T-S1: the five values frozen bytes pin at 2026-03-31", () => {
  const summary = JSON.parse(
    fileByPath(generateArtifact(specs.byId.get("FIN-04"), canon), "ar-aging-summary.json").content
  );
  assert.equal(summary.subledger_total, "3438041.42");
  assert.equal(summary.customer_count, 19);
  const tb = new Map(buildTrialBalance().rows.map((r) => [r.account_code, r]));
  assert.equal(tb.get("2300").ending_credit, "20031018.96", "deferred revenue current");
  assert.equal(tb.get("2310").ending_credit, "2263716.56", "deferred revenue non-current");
  // The subledger-only invoice: FIN-05's control account 1100 stands 17446.72
  // below FIN-04's subledger total, and computation_note has to say so rather
  // than hide it. Naming the AR figure is what makes days sales outstanding
  // single-method (plan U17).
  assert.equal(
    cents(toCents(summary.subledger_total) - toCents(tb.get("1100").ending_debit)),
    "17446.72"
  );
});

test("FIN-32 T-S3 and T-S4: both ends of the close, and the one account with a bank feed", () => {
  const accounts = cashAccounts();
  assert.deepEqual(accounts.map((a) => a.account_code), ["1010", "1020", "1030", "1050"]);
  const operating = accounts.find((a) => a.account_code === RECONCILED_CASH_ACCOUNT);
  assert.equal(operating.beginning_balance, "3482915.22", "the February anchor the canon timeline records");
  assert.equal(operating.ending_balance, "2740359.09");
  const statement = JSON.parse(
    fileByPath(generateArtifact(specs.byId.get("FIN-01"), canon), "bank-statement-summary.json").content
  );
  const bankEnding = statement.ending_balance ?? statement.closing_balance;
  assert.equal(String(bankEnding), "2806284.46", "FIN-01's bank-side ending balance moved");
  assert.equal(cents(toCents(String(bankEnding)) - toCents(operating.ending_balance)), "65925.37");

  // Not a two-item reconciliation: the twelve outstanding checks are less than
  // the difference, and FIN-03 carries no account attribution at all.
  const checks = csvTable(
    fileByPath(generateArtifact(specs.byId.get("FIN-03"), canon), "outstanding-checks.csv").content
  );
  assert.equal(checks.rows.length, 12);
  assert.equal(cents(checks.rows.reduce((sum, r) => sum + toCents(r.amount), 0)), "57212.36");
  assert.ok(!checks.cols.includes("gl_account"));
});

// ------------------------------------------------------------ red until built

test("FIN-31: 168 rows, seven inputs by the shared 24 month-ends", () => {
  const rows = kpiRows();
  assert.equal(rows.length, 168);
  assert.deepEqual([...new Set(rows.map((r) => r.period_end))].sort(), [...PERIOD_ENDS].sort());
  assert.deepEqual([...new Set(rows.map((r) => r.metric_id))].sort(), [...METRIC_IDS].sort());
  for (const metricId of METRIC_IDS) {
    const series = rows.filter((r) => r.metric_id === metricId);
    assert.equal(series.length, 24, `${metricId} is not a full series`);
    assert.deepEqual(series.map((r) => r.period_end), PERIOD_ENDS, `${metricId} is not in month order`);
    assert.equal(new Set(series.map((r) => r.metric_name)).size, 1, `${metricId} changes name mid series`);
    assert.equal(new Set(series.map((r) => r.unit)).size, 1, `${metricId} changes unit mid series`);
    // One column carries money and counts, so the unit is what says which, and
    // every cell has to parse under the unit its own row declares.
    for (const row of series) {
      if (row.unit === "usd") assert.match(row.value, /^\d+\.\d{2}$/, `${metricId} at ${row.period_end}`);
      else assert.match(row.value, /^[1-9]\d*$/, `${metricId} at ${row.period_end} is not a whole count`);
      assert.match(row.period_end, /^\d{4}-\d{2}-\d{2}$/);
      assert.notEqual(row.computation_note, "", `${metricId} at ${row.period_end} states no computation note`);
    }
    // A KPI input that never moves is a constant, not a series to plot.
    assert.ok(
      series.some((r, i) => i > 0 && r.value !== series[i - 1].value),
      `${metricId} does not move across the window`
    );
  }
});

test("FIN-31 T-S1: every value a frozen file pins, recomputed from that file's committed bytes", () => {
  const rows = kpiRows();
  const at = (metricId, periodEnd) => rows.find((r) => r.metric_id === metricId && r.period_end === periodEnd);

  // FIN-04's own summary, read off disk.
  const summary = shippedJson("finance/ar-aging-export", "ar-aging-summary.json");
  assert.equal(summary.as_of, CLOSE_PERIOD_END, "FIN-04 is no longer an as-of 2026-03-31 snapshot");
  assert.equal(
    at("ar_subledger_balance", CLOSE_PERIOD_END).value, summary.subledger_total,
    `ar_subledger_balance at ${CLOSE_PERIOD_END} does not equal FIN-04's subledger total`
  );
  assert.equal(
    at("ar_customer_count", CLOSE_PERIOD_END).value, String(summary.customer_count),
    `ar_customer_count at ${CLOSE_PERIOD_END} does not equal FIN-04's customer count`
  );

  // FIN-05's own bytes, at both ends of the close: beginning_balance is the
  // balance at the February month end and ending_balance the balance at the
  // March one, so the two deferred inputs are pinned twice rather than once.
  const tb = new Map(shippedCsv("finance/gl-trial-balance", "gl-trial-balance.csv").rows.map((r) => [r.account_code, r]));
  for (const [metricId, accountCode] of [["deferred_revenue_current", "2300"], ["deferred_revenue_noncurrent", "2310"]]) {
    const balance = tb.get(accountCode);
    assert.equal(balance.normal_balance, "credit", `${accountCode} is not credit normal`);
    assert.equal(balance.ending_debit, "", `${accountCode} closes on the side its normal balance does not run on`);
    assert.equal(at(metricId, CLOSE_PERIOD_END).value, balance.ending_balance, `${metricId} at the close`);
    assert.equal(at(metricId, "2026-02-28").value, balance.beginning_balance, `${metricId} at February`);
  }

  // CORE-04's own bytes at the close, by the rule the file publishes.
  const roster = shippedCsv("core/people-roster", "people-roster.csv").rows;
  const heads = (periodEnd) =>
    roster.filter((r) => r.employment_status === "active" && r.start_date <= periodEnd).length;
  assert.equal(at("headcount", CLOSE_PERIOD_END).value, String(heads(CLOSE_PERIOD_END)));

  // Five inputs pinned at the close is the qualified count; the qualifier the
  // rule names is the date, and with it dropped the pack pins 30 of the 168
  // rows: the two deferred inputs again at February, and headcount at all 24.
  const pinnedAtClose = rows.filter((r) => r.period_end === CLOSE_PERIOD_END && r.source_artifact !== "");
  assert.equal(pinnedAtClose.length, 5, `pinned at the close: ${pinnedAtClose.map((r) => r.metric_id).join(", ")}`);
  assert.equal(rows.filter((r) => r.source_artifact !== "").length, 30);

  // Plan U17, and the whole reason days sales outstanding is single-method
  // here: the subledger stands above FIN-05's own control account, and the note
  // states the difference rather than hiding it. Recomputed, never quoted.
  const gap = cents(toCents(summary.subledger_total) - toCents(tb.get("1100").ending_debit));
  assert.equal(gap, "17446.72");
  const note = at("ar_subledger_balance", CLOSE_PERIOD_END).computation_note;
  assert.ok(note.includes(gap), `the note does not state the ${gap} subledger difference`);
  assert.ok(note.includes("1100"), "the note does not name the control account it stands against");
});

test("FIN-31 T-S2: the headcount series is CORE-04's own rule at all 24 dates", () => {
  const roster = shippedCsv("core/people-roster", "people-roster.csv");
  assert.ok(!roster.cols.includes("termination_date"), "CORE-04 gained a termination date, so the exclusion stops being forced");
  const active = roster.rows.filter((r) => r.employment_status === "active");
  const departed = roster.rows.filter((r) => r.employment_status === "departed");
  assert.equal(departed.length, 18);

  const emitted = kpiRows().filter((r) => r.metric_id === "headcount");
  let previous = 0;
  for (const row of emitted) {
    const byRule = active.filter((r) => r.start_date <= row.period_end).length;
    assert.equal(row.value, String(byRule), `headcount at ${row.period_end}`);
    assert.ok(byRule >= previous, `the series falls at ${row.period_end}, which the rule cannot produce`);
    previous = byRule;

    // The mutation this file exists to catch: counting the departed rows moves
    // every month at once, so assert the wrong rule gives a different answer.
    const withDeparted = roster.rows.filter((r) => r.start_date <= row.period_end).length;
    assert.notEqual(String(withDeparted), row.value, `including the departed rows changes nothing at ${row.period_end}`);
  }
  assert.equal(emitted[0].value, "413", "the series no longer opens at the roster's own 2024-04-30 count");
  assert.equal(emitted[emitted.length - 1].value, String(active.length));
  assert.equal(new Set(emitted.map((r) => r.source_artifact)).size, 1);
  assert.equal(emitted[0].source_artifact, "CORE-04");
});

test("FIN-31: every source_artifact names a shipped id, and every source_reference resolves in it", () => {
  const rows = kpiRows();
  const sourced = rows.filter((r) => r.source_artifact !== "");
  const emittedFiles = new Map();
  for (const row of sourced) {
    const spec = specs.byId.get(row.source_artifact);
    assert.ok(spec, `${row.metric_id} at ${row.period_end} cites ${row.source_artifact}, which is not in the catalog`);
    assert.notEqual(row.source_reference, "", `${row.metric_id} at ${row.period_end} cites an artifact and no field in it`);
    if (!emittedFiles.has(row.source_artifact)) {
      emittedFiles.set(row.source_artifact, new Set(generateArtifact(spec, canon).map((f) => f.path)));
    }
    const file = row.source_reference.split(" ")[0];
    assert.ok(
      emittedFiles.get(row.source_artifact).has(file),
      `${row.source_artifact} emits no file called "${file}"`
    );
  }
  // A row with no source states so in both columns rather than in one.
  for (const row of rows.filter((r) => r.source_artifact === "")) {
    assert.equal(row.source_reference, "", `${row.metric_id} at ${row.period_end} cites a field with no artifact`);
  }
  // The two recurring-revenue inputs are the ones no frozen file carries at any
  // date, which is what the split between the three FP&A files leaves over.
  const unsourcedMetrics = [...new Set(rows.filter((r) => r.source_artifact === "").map((r) => r.metric_id))];
  assert.deepEqual(
    unsourcedMetrics.filter((m) => rows.filter((r) => r.metric_id === m).every((r) => r.source_artifact === "")).sort(),
    ["churned_arr", "new_arr"]
  );
});

test("FIN-32: 96 rows, and every book balance tied to FIN-05 at both ends of the close", { todo: WAVE }, () => {
  const rows = bankRows();
  assert.equal(rows.length, 96);
  const tb = new Map(cashAccounts().map((a) => [a.account_code, a]));
  for (const row of rows.filter((r) => r.period_end === "2026-02-28")) {
    assert.equal(row.book_balance, tb.get(row.account_code).beginning_balance, `${row.account_code} at 2026-02-28`);
  }
  for (const row of rows.filter((r) => r.period_end === "2026-03-31")) {
    assert.equal(row.book_balance, tb.get(row.account_code).ending_balance, `${row.account_code} at 2026-03-31`);
  }
});

test("FIN-32 T-S5: reconciling_difference is the subtraction its own columns state, on all 96 rows", { todo: WAVE }, () => {
  for (const row of bankRows()) {
    assert.equal(
      row.reconciling_difference,
      cents(toCents(row.bank_balance) - toCents(row.book_balance)),
      `${row.account_code} at ${row.period_end}`
    );
    if (row.account_code !== RECONCILED_CASH_ACCOUNT) {
      assert.equal(row.reconciling_difference, "0.00", `${row.account_code} has no bank feed, so it cannot carry a difference`);
    }
  }
  const march1010 = bankRows().find((r) => r.account_code === RECONCILED_CASH_ACCOUNT && r.period_end === "2026-03-31");
  assert.equal(march1010.bank_balance, "2806284.46");
  assert.equal(march1010.reconciling_difference, "65925.37");
});

test("FIN-31 and FIN-32 T-S6 and V19: no emitted file names the absent metric", { todo: WAVE }, () => {
  const emitted = [
    ...generateArtifact(specs.byId.get("FIN-31"), canon),
    ...generateArtifact(specs.byId.get("FIN-32"), canon),
  ];
  for (const file of emitted) {
    assert.ok(
      !new RegExp(ABSENT_BY_DESIGN, "i").test(file.content),
      `${file.path} names the metric the pack deliberately does not declare`
    );
  }
  // The scope is the emitted datasets and never the repository: FIN-31's own
  // spec planted_features carry the word, and so does FIN-34's.
});
