// FIN-17 close-checklist: the March 2026 close of co-002, in flight at D+4.
//
// Two things this file exists to catch. First, drift between FIN-17 and the
// FIN-36 template it is an instance of: the spine is compared against
// buildCloseChecklistTemplate() rather than against a copy of its values, so a
// template edit that FIN-17 does not follow fails here rather than shipping two
// checklists that disagree. Second, a reroll that quietly destroys a planted
// feature: every plant is re-derived from the generated bytes by its own rule,
// with its cardinality asserted, and never by naming the row or the person that
// carries it (answer-key rule, datagen/README.md).
import { test } from "node:test";
import assert from "node:assert/strict";
import { join } from "node:path";
import { loadSpecs } from "../../datagen/src/specLoader.js";
import { loadCanonCompanies } from "../../datagen/src/canon.js";
import { generateArtifact } from "../../datagen/src/engine.js";
import { csvTable, fileByPath } from "../helpers/csv-table.js";
import { buildCloseChecklistTemplate } from "../../datagen/src/generators/fin-36-close-checklist-template.js";
import { buildChartOfAccounts, OPERATING_CASH_ACCOUNT } from "../../datagen/src/generators/fin-22-chart-of-accounts.js";
import { buildTrialBalance } from "../../datagen/src/generators/fin-05-gl-trial-balance.js";
import { financeRoster } from "../../datagen/src/generators/finance-roles.js";
import {
  PREPARER_EMPLOYEE_ID, REVIEWER_EMPLOYEE_ID,
} from "../../datagen/src/generators/fin-01-cash-recon.js";
import { AS_OF, SPINE_COLUMNS, STATUSES } from "../../datagen/src/generators/fin-17-close-checklist.js";
import { addBusinessDays, closeDayDate, isWeekend, toEpochDay } from "../../datagen/src/dates.js";

const REPO_ROOT = join(import.meta.dirname, "..", "..");
const specs = loadSpecs(join(REPO_ROOT, "specs", "artifact-specs.yaml"));
const canon = loadCanonCompanies(join(REPO_ROOT, "canon", "companies.md"));
const spec = specs.byId.get("FIN-17");
const OUTPUT_FILE = "close-checklist.csv";

const roster = financeRoster();
const chart = new Map(buildChartOfAccounts().map((a) => [a.account_code, a]));
const trialBalance = new Map(buildTrialBalance().rows.map((r) => [r.account_code, r]));

function checklist() {
  assert.ok(spec, "FIN-17 not found in specs/artifact-specs.yaml");
  const files = generateArtifact(spec, canon);
  const table = csvTable(fileByPath(files, OUTPUT_FILE).content);
  assert.deepEqual(table.cols, spec.columns, "FIN-17: header does not match spec.columns");
  return table.rows;
}

const before = (aIso, bIso) => toEpochDay(aIso) < toEpochDay(bIso);
const employee = (employeeId) => roster.find((r) => r.employee_id === employeeId);

/** Every (task, controls task that depends on it) edge the checklist contains. */
function controlEdges(rows) {
  const byId = new Map(rows.map((r) => [r.task_id, r]));
  return rows
    .filter((r) => r.category === "controls" && r.depends_on !== "")
    .map((child) => ({ child, parent: byId.get(child.depends_on) }));
}

// ------------------------------------------------------------------ the spine

test("FIN-17: 24 rows whose spine is the FIN-36 template row for row, not a retyped copy", () => {
  const rows = checklist();
  const template = buildCloseChecklistTemplate();
  assert.equal(rows.length, 24, "the close checklist carries one row per template task");
  assert.equal(rows.length, template.length, "FIN-17 and FIN-36 hold a different number of tasks");
  assert.equal(new Set(rows.map((r) => r.task_id)).size, rows.length, "task ids must be unique");
  const project = (row) => SPINE_COLUMNS.map((col) => row[col]);
  assert.deepEqual(
    rows.map(project),
    template.map(project),
    "FIN-17's spine has drifted from buildCloseChecklistTemplate(); regenerate FIN-17 after any FIN-36 edit"
  );
});

test("FIN-17: notes ships empty on every row", () => {
  for (const row of checklist()) {
    assert.equal(row.notes, "", `${row.task_id} carries a note, which is where an answer key hides`);
  }
});

// -------------------------------------------------------------- the due dates

test("FIN-17: due_date is closeDayDate(close_day) on every row, and no due date lands on a weekend", () => {
  const rows = checklist();
  let lastDue = 0;
  for (const row of rows) {
    assert.equal(
      row.due_date, closeDayDate(row.close_day),
      `${row.task_id} dates ${row.close_day} as ${row.due_date}, which is not the business-day rule`
    );
    assert.equal(isWeekend(row.due_date), false, `${row.task_id} is due on a weekend`);
    assert.ok(toEpochDay(row.due_date) >= lastDue, `${row.task_id} is due before the task above it`);
    lastDue = toEpochDay(row.due_date);
  }
  assert.equal(AS_OF, closeDayDate("D+4"), "the as-of is the close's own D+4, not a calendar guess");
  assert.equal(isWeekend(AS_OF), false, "the as-of falls on a weekend");
  assert.ok(
    rows.some((r) => before(r.due_date, AS_OF)) &&
    rows.some((r) => r.due_date === AS_OF) &&
    rows.some((r) => before(AS_OF, r.due_date)),
    "a close in flight needs tasks behind, on and ahead of the as-of"
  );
});

// ------------------------------------------------------- status and sign off

test("FIN-17: status is complete, in_progress or not_started, all three occur, and nothing due after the as-of has started", () => {
  const rows = checklist();
  for (const row of rows) {
    assert.ok(STATUSES.includes(row.status), `${row.task_id} has status "${row.status}"`);
    if (before(AS_OF, row.due_date)) {
      assert.equal(row.status, "not_started", `${row.task_id} is not due yet but is already under way`);
    }
  }
  for (const status of STATUSES) {
    assert.ok(rows.some((r) => r.status === status), `no task is "${status}", so the close is not in flight`);
  }
});

test("FIN-17: completed_date is populated exactly on the complete rows, never early, never after the as-of", () => {
  const rows = checklist();
  const byId = new Map(rows.map((r) => [r.task_id, r]));
  for (const row of rows) {
    if (row.status !== "complete") {
      assert.equal(row.completed_date, "", `${row.task_id} is not complete but carries a completed_date`);
      continue;
    }
    assert.notEqual(row.completed_date, "", `${row.task_id} is complete with no completed_date`);
    assert.equal(isWeekend(row.completed_date), false, `${row.task_id} was signed off on a weekend`);
    assert.ok(
      !before(row.completed_date, row.due_date),
      `${row.task_id} was signed off before it was due`
    );
    assert.ok(
      !before(AS_OF, row.completed_date),
      `${row.task_id} was signed off after the as-of, which has not happened yet`
    );
    assert.ok(
      !before(addBusinessDays(row.due_date, 1), row.completed_date),
      `${row.task_id} slipped more than one business day past its due date`
    );
    if (row.depends_on === "") continue;
    const parent = byId.get(row.depends_on);
    assert.ok(
      !before(row.completed_date, parent.completed_date),
      `${row.task_id} was signed off before the task it depends on`
    );
  }
});

test("FIN-17: no task is complete while a task it depends on is not", () => {
  const rows = checklist();
  const byId = new Map(rows.map((r) => [r.task_id, r]));
  for (const row of rows) {
    if (row.depends_on === "") continue;
    const parent = byId.get(row.depends_on);
    assert.ok(parent, `${row.task_id} depends on ${row.depends_on}, which is not a task`);
    if (row.status !== "complete") continue;
    assert.equal(
      parent.status, "complete",
      `${row.task_id} is complete while ${parent.task_id}, which it depends on, is not`
    );
  }
});

// ------------------------------------------------------------- the roster tie

test("FIN-17: owner and reviewer are different active Finance employees, each holding that row's own role", () => {
  for (const row of checklist()) {
    for (const [idColumn, roleColumn] of [
      ["owner_employee_id", "owner_role"], ["reviewer_employee_id", "reviewer_role"],
    ]) {
      const person = employee(row[idColumn]);
      assert.ok(person, `${row.task_id}: ${row[idColumn]} is not on the CORE-04 roster`);
      assert.equal(person.employment_status, "active", `${row.task_id}: ${row[idColumn]} is not active`);
      assert.equal(person.department, "Finance", `${row.task_id}: ${row[idColumn]} is not in Finance`);
      assert.equal(
        person.role_title, row[roleColumn],
        `${row.task_id}: ${row[idColumn]} does not hold "${row[roleColumn]}"`
      );
    }
    assert.notEqual(
      row.owner_employee_id, row.reviewer_employee_id,
      `${row.task_id} is owned and reviewed by the same person`
    );
  }
});

test("FIN-17: the close journal batch names the same preparer and reviewer as the FIN-09 batch it produces", () => {
  const rows = checklist();
  const edges = controlEdges(rows);
  assert.ok(edges.length > 0, "the checklist has no controls task that depends on another task");
  const batch = edges[0].parent;
  assert.equal(
    batch.owner_employee_id, PREPARER_EMPLOYEE_ID,
    "the checklist and the journal batch disagree about who prepared the close batch"
  );
  assert.equal(
    batch.reviewer_employee_id, REVIEWER_EMPLOYEE_ID,
    "the checklist and the journal batch disagree about who reviewed the close batch"
  );
});

// ---------------------------------------------------------- the account codes

test("FIN-17: account_code is populated on the four reconciliation tasks only, and every code is an active FIN-22 account", () => {
  const rows = checklist();
  const coded = rows.filter((r) => r.account_code !== "");
  assert.equal(coded.length, 4, "the close reconciles four balances, no more and no fewer");
  assert.equal(new Set(coded.map((r) => r.account_code)).size, coded.length, "two tasks reconcile one account");
  for (const row of coded) {
    const account = chart.get(row.account_code);
    assert.ok(account, `${row.task_id} cites account ${row.account_code}, which is not on the FIN-22 chart`);
    assert.equal(account.active, "true", `${row.task_id} cites an inactive account`);
    assert.match(
      row.task, /^Reconcile\b|\bcontrol account\b/,
      `${row.task_id} carries an account code but does not reconcile or tie out a balance`
    );
  }
  for (const row of rows.filter((r) => r.account_code === "")) {
    assert.doesNotMatch(
      row.task, /^Reconcile\b|\bcontrol account\b/,
      `${row.task_id} reconciles a balance but names no account`
    );
  }
  const cash = coded.find((r) => r.category === "cash");
  assert.ok(cash, "no cash reconciliation on the checklist");
  assert.equal(
    cash.account_code, OPERATING_CASH_ACCOUNT.code,
    "the cash reconciliation does not tie to the operating account FIN-01 and FIN-02 post against"
  );
});

// ---------------------------------------------------------------- the plants

test("FIN-17: exactly one task is overdue at the as-of and carries no account code", () => {
  const overdue = checklist().filter(
    (r) => r.status !== "complete" && before(r.due_date, AS_OF) && r.account_code === ""
  );
  assert.equal(overdue.length, 1, `${overdue.length} tasks are overdue with no account code, expected 1`);
});

test("FIN-17: exactly one account is unreconciled past its close deadline, and it carries a real balance", () => {
  const open = checklist().filter(
    (r) => r.status !== "complete" && before(r.due_date, AS_OF) && r.account_code !== ""
  );
  assert.equal(open.length, 1, `${open.length} reconciliations are open past the deadline, expected 1`);
  const account = chart.get(open[0].account_code);
  assert.ok(account, "the unreconciled account is not on the FIN-22 chart");
  assert.equal(account.active, "true", "the unreconciled account is inactive, so nothing is at stake");
  const balance = trialBalance.get(open[0].account_code);
  assert.ok(balance, "the unreconciled account carries no FIN-05 trial-balance row");
  assert.notEqual(
    Math.round(Number(balance.ending_balance) * 100), 0,
    "the unreconciled account ends the period at zero, so the open item costs nothing"
  );
});

test("FIN-17: exactly one reviewer signs off both a task and the controls task that tests it", () => {
  const rows = checklist();
  const edges = controlEdges(rows);
  assert.ok(
    edges.length >= 2,
    "one candidate edge would make the double booking structural rather than a planted choice"
  );
  const doubleBooked = new Set(
    edges
      .filter(({ child, parent }) => child.reviewer_employee_id === parent.reviewer_employee_id)
      .map(({ child }) => child.reviewer_employee_id)
  );
  assert.equal(doubleBooked.size, 1, `${doubleBooked.size} reviewers are double booked, expected 1`);
  const [conflicted] = [...doubleBooked];
  const person = employee(conflicted);
  assert.ok(person, "the double-booked reviewer is not on the CORE-04 roster");
  assert.equal(person.employment_status, "active");
  assert.equal(person.department, "Finance");
  const carrying = rows.filter((r) => r.reviewer_employee_id === conflicted);
  assert.ok(
    carrying.every((r) => r.owner_employee_id !== conflicted),
    "the double-booked reviewer also owns one of the tasks, which is a second conflict"
  );
});

// ---------------------------------------------------------------- determinism

test("FIN-17: two runs of the generator produce identical bytes", () => {
  const runA = generateArtifact(spec, canon);
  const runB = generateArtifact(spec, canon);
  assert.deepEqual(runA.map((f) => f.path), runB.map((f) => f.path));
  for (let i = 0; i < runA.length; i += 1) {
    assert.equal(runA[i].content, runB[i].content, `${runA[i].path} differs between runs`);
  }
});
