// FIN-15 customer-credit-notes: the credit notes behind co-002's March 2026
// receivable, and the six FIN-04 credit memos they explain.
//
// The file exists to catch two things. First, drift between FIN-15 and the
// frozen FIN-04 aging: the six shipped memos are re-read from buildArAging()
// rather than from a copy of their values, so a reroll that moves a memo fails
// here rather than shipping two files that describe different receivables.
// Second, a reroll that quietly destroys a plant: every planted feature is
// re-derived from the generated bytes by its own rule, with its cardinality
// asserted, and never by naming the row or the person that carries it
// (answer-key rule, datagen/README.md).
import { test } from "node:test";
import assert from "node:assert/strict";
import { join } from "node:path";
import { loadSpecs } from "../../datagen/src/specLoader.js";
import { loadCanonCompanies } from "../../datagen/src/canon.js";
import { generateArtifact } from "../../datagen/src/engine.js";
import { csvTable, fileByPath } from "../helpers/csv-table.js";
import { buildArAging } from "../../datagen/src/generators/fin-04-ar-aging.js";
import { buildDecisionAuthorityMatrix } from "../../datagen/src/generators/fin-39-decision-authority-matrix.js";
import { financeRoster } from "../../datagen/src/generators/finance-roles.js";
import { SOD_CONFLICT_ROLE } from "../../datagen/src/generators/fin-01-cash-recon.js";
import {
  CREDIT_NOTE_PERIOD, REASON_CODES, SPINE_NOTE_COUNT, APPLIED_NOTE_COUNT,
  REQUESTED_NOTE_COUNT, WRITE_OFF_AUTHORITY,
} from "../../datagen/src/generators/fin-15-collections.js";

const REPO_ROOT = join(import.meta.dirname, "..", "..");
const specs = loadSpecs(join(REPO_ROOT, "specs", "artifact-specs.yaml"));
const canon = loadCanonCompanies(join(REPO_ROOT, "canon", "companies.md"));
const spec = specs.byId.get("FIN-15");
const OUTPUT_FILE = "customer-credit-notes.csv";

const roster = financeRoster();
const employee = (employeeId) => roster.find((r) => r.employee_id === employeeId);
const cents = (money) => Math.round(Number(money) * 100);

const { aging } = buildArAging();
const agingByNumber = new Map(aging.map((r) => [r.document_number, r]));
const agingMemos = aging.filter((r) => r.document_type === "credit_memo");
const authority = buildDecisionAuthorityMatrix();

function notes() {
  assert.ok(spec, "FIN-15 not found in specs/artifact-specs.yaml");
  const files = generateArtifact(spec, canon);
  const table = csvTable(fileByPath(files, OUTPUT_FILE).content);
  assert.deepEqual(table.cols, spec.columns, "FIN-15: header does not match spec.columns");
  return table.rows;
}

// ------------------------------------------------------------------ the shape

test("FIN-15: sixteen notes, uniquely numbered from CN-2026-0101 upward and textually disjoint from the FIN-04 memo block", () => {
  const rows = notes();
  assert.equal(
    rows.length, SPINE_NOTE_COUNT + APPLIED_NOTE_COUNT + REQUESTED_NOTE_COUNT,
    "the credit-note file does not carry the spine, the applied notes and the open requests"
  );
  assert.equal(new Set(rows.map((r) => r.credit_note_id)).size, rows.length, "credit_note_id repeats");
  const agingNumbers = new Set(aging.map((r) => r.document_number));
  for (const row of rows) {
    assert.match(row.credit_note_id, /^CN-2026-0\d{3}$/, `${row.credit_note_id} is not in the CN-2026-0NNN series`);
    assert.equal(
      agingNumbers.has(row.credit_note_id), false,
      `${row.credit_note_id} also names a FIN-04 document, so a join between the files resolves by accident`
    );
    assert.equal(row.currency, "USD");
    assert.ok(REASON_CODES.includes(row.reason_code), `${row.credit_note_id} carries reason_code "${row.reason_code}"`);
    assert.ok(cents(row.amount) > 0, `${row.credit_note_id} is not a positive credit`);
    assert.ok(
      row.requested_date <= CREDIT_NOTE_PERIOD.end,
      `${row.credit_note_id} was requested on ${row.requested_date}, after the period closed`
    );
  }
  // The spine's dates belong to FIN-04, and FIN-04 ships one memo dated before
  // this period opens, so only the notes this file dates itself are bounded by
  // the period's start.
  const spineArDocuments = new Set(agingMemos.map((m) => m.document_number));
  for (const row of rows.filter((r) => !spineArDocuments.has(r.ar_document_number))) {
    assert.ok(
      row.requested_date >= CREDIT_NOTE_PERIOD.start,
      `${row.credit_note_id} was requested on ${row.requested_date}, before the period opened`
    );
  }
  assert.equal(
    new Set(rows.map((r) => r.reason_code)).size, REASON_CODES.length,
    "not every reason code occurs, so a rule keyed to one of them has nothing to find"
  );
});

test("FIN-15: every customer is a FIN-04 customer and carries the aging's own name for it", () => {
  const names = new Map(aging.map((r) => [r.customer_canon_id, r.customer_name]));
  for (const row of notes()) {
    assert.ok(names.has(row.customer_canon_id), `${row.credit_note_id} names ${row.customer_canon_id}, which is not in the aging`);
    assert.equal(
      row.customer_name, names.get(row.customer_canon_id),
      `${row.credit_note_id} calls ${row.customer_canon_id} something the aging does not`
    );
  }
});

// ------------------------------------------------------------------ the spine

test("FIN-15: the six FIN-04 credit memos are the spine, matched on customer, applied_to_document and amount to the cent", () => {
  const rows = notes();
  assert.equal(agingMemos.length, SPINE_NOTE_COUNT, "FIN-04 no longer ships six credit memos");
  const byArDocument = new Map(rows.map((r) => [r.ar_document_number, r]));
  for (const memo of agingMemos) {
    const note = byArDocument.get(memo.document_number);
    assert.ok(note, `FIN-04 memo ${memo.document_number} has no credit note behind it`);
    assert.equal(note.status, "issued", `the note behind ${memo.document_number} is not issued`);
    assert.equal(note.customer_canon_id, memo.customer_canon_id, `the note behind ${memo.document_number} sits on another customer`);
    assert.equal(
      note.applied_to_document, memo.applied_to_document,
      `the note behind ${memo.document_number} applies somewhere the aging does not`
    );
    assert.equal(
      cents(note.amount), Math.abs(cents(memo.open_balance)),
      `the note behind ${memo.document_number} disagrees with the aging about the amount`
    );
    assert.equal(
      note.issued_date, memo.document_date,
      `the note behind ${memo.document_number} was issued on a day the aging does not carry it`
    );
    assert.equal(note.customer_name, memo.customer_name, `the note behind ${memo.document_number} names the customer differently`);
  }
  const spine = rows.filter((r) => agingByNumber.has(r.ar_document_number));
  assert.equal(spine.length, SPINE_NOTE_COUNT, `${spine.length} notes resolve into the aging, expected ${SPINE_NOTE_COUNT}`);
});

test("FIN-15: eight issued notes were applied before the period end and appear nowhere in the aging", () => {
  const rows = notes();
  const applied = rows.filter((r) => r.status === "issued" && !agingByNumber.has(r.ar_document_number));
  assert.equal(applied.length, APPLIED_NOTE_COUNT, `${applied.length} notes are issued and settled, expected ${APPLIED_NOTE_COUNT}`);
  for (const row of applied) {
    assert.notEqual(row.ar_document_number, "", `${row.credit_note_id} is issued with no AR document behind it`);
    assert.notEqual(row.applied_to_document, "", `${row.credit_note_id} was fully applied against nothing`);
    assert.equal(
      agingByNumber.has(row.applied_to_document), false,
      `${row.credit_note_id} was fully applied, so the invoice it cleared cannot still be open in the aging`
    );
    assert.ok(row.issued_date <= "2026-02-28", `${row.credit_note_id} was issued on ${row.issued_date}, too late to be settled in the period`);
  }
});

test("FIN-15: exactly two notes are still requested, with no issue date, no AR document and no approver", () => {
  const rows = notes();
  const requested = rows.filter((r) => r.status === "requested");
  assert.equal(requested.length, REQUESTED_NOTE_COUNT, `${requested.length} notes are still requested, expected ${REQUESTED_NOTE_COUNT}`);
  for (const row of requested) {
    assert.equal(row.issued_date, "", `${row.credit_note_id} is requested and carries an issue date`);
    assert.equal(row.ar_document_number, "", `${row.credit_note_id} is requested and is already in AR`);
    assert.equal(row.approved_by_employee_id, "", `${row.credit_note_id} is requested and is already approved`);
    const invoice = agingByNumber.get(row.applied_to_document);
    assert.ok(invoice, `${row.credit_note_id} asks for credit against a document the aging does not carry`);
    assert.equal(invoice.document_type, "invoice", `${row.credit_note_id} asks for credit against a credit memo`);
    assert.equal(invoice.customer_canon_id, row.customer_canon_id, `${row.credit_note_id} asks for credit on another customer's invoice`);
  }
  assert.equal(new Set(requested.map((r) => r.customer_canon_id)).size, requested.length, "both open requests sit on one customer");
});

test("FIN-15: ar_document_number is empty exactly while a note is requested, and status is only issued or requested", () => {
  for (const row of notes()) {
    assert.ok(["issued", "requested"].includes(row.status), `${row.credit_note_id} has status "${row.status}"`);
    assert.equal(
      row.ar_document_number === "", row.status === "requested",
      `${row.credit_note_id} disagrees with its own status about whether it reached AR`
    );
    assert.equal(
      row.issued_date === "", row.status === "requested",
      `${row.credit_note_id} disagrees with its own status about whether it was issued`
    );
    if (row.issued_date !== "") {
      assert.ok(row.issued_date >= row.requested_date, `${row.credit_note_id} was issued before it was asked for`);
    }
  }
});

// ------------------------------------------------------------- the roster tie

test("FIN-15: the requester is the aging's own owner for that customer, and every issued note names a different approver", () => {
  const owners = new Map(aging.map((r) => [r.customer_canon_id, r.ar_owner_employee_id]));
  for (const row of notes()) {
    assert.equal(
      row.requested_by_employee_id, owners.get(row.customer_canon_id),
      `${row.credit_note_id} was raised by someone other than the clerk who owns the account in FIN-04`
    );
    const requester = employee(row.requested_by_employee_id);
    assert.ok(requester, `${row.credit_note_id}: the requester is not on the CORE-04 roster`);
    assert.equal(requester.employment_status, "active");
    assert.equal(requester.department, "Finance");
    assert.notEqual(requester.finance_system_role, SOD_CONFLICT_ROLE, "a credit note was raised by the roster's SoD conflict");
    if (row.status !== "issued") continue;
    const approver = employee(row.approved_by_employee_id);
    assert.ok(approver, `${row.credit_note_id}: the approver is not on the CORE-04 roster`);
    assert.equal(approver.employment_status, "active");
    assert.equal(approver.department, "Finance");
    assert.notEqual(approver.finance_system_role, SOD_CONFLICT_ROLE, "a credit note was approved by the roster's SoD conflict");
    assert.notEqual(
      row.approved_by_employee_id, row.requested_by_employee_id,
      `${row.credit_note_id} was raised and approved by the same person`
    );
  }
});

test("FIN-15: the approver's role is the FIN-39 write-off authority for that amount, recomputed from the shipped matrix", () => {
  const bands = WRITE_OFF_AUTHORITY.map((controlId) => {
    const row = authority.find((r) => r.control_id === controlId);
    assert.ok(row, `${controlId} is not a control_id in the shipped FIN-39 matrix`);
    return row;
  });
  assert.equal(new Set(bands.map((b) => b.decision)).size, 1, "the two write-off rows decide different things");
  for (const row of notes().filter((r) => r.status === "issued")) {
    const dollars = Number(row.amount);
    const band = bands.find((b) => (
      dollars >= Number(b.amount_min_usd) &&
      (b.amount_max_usd === "" || dollars <= Number(b.amount_max_usd))
    ));
    assert.ok(band, `${row.credit_note_id} at ${row.amount} falls in no FIN-39 write-off band`);
    assert.equal(
      employee(row.approved_by_employee_id).role_title, band.approver_role,
      `${row.credit_note_id} was approved below the authority ${band.control_id} requires`
    );
  }
});

// ---------------------------------------------------------------- determinism

test("FIN-15: two runs of the generator produce identical bytes", () => {
  const runA = generateArtifact(spec, canon);
  const runB = generateArtifact(spec, canon);
  assert.deepEqual(runA.map((f) => f.path), runB.map((f) => f.path));
  for (let i = 0; i < runA.length; i += 1) {
    assert.equal(runA[i].content, runB[i].content, `${runA[i].path} differs between runs`);
  }
});
