// HR-11 goals-self-assessment-records: the guard over the growth record set,
// over the total join that makes it a dataset rather than a dump, and over the
// one place a self-assessment sits two levels below its own goal.
//
// Four disciplines run through every check.
//
//   * No test names the employee whose self-assessment sits two levels below
//     their goal, and no test names a goal id or a self-assessment id that
//     carries it. The conflict is found by rule over the whole set and asserted
//     by cardinality, so a reroll that moves it stays green and a reroll that
//     destroys it fails.
//   * The population, the cycle and the approvers are read off the committed
//     datasets/hr/review-cycle-roster/ CSVs here, never through the shared
//     builder the generator uses, because the claim under test is that the two
//     artifacts agree rather than that two calls of one function agree. The
//     competency names come from the committed HR-01 register the same way.
//   * The scale, the role map, the note sentences and the three key orders are
//     restated literally below and the generator's exported copies are asserted
//     equal to them, the HR-18 discipline, so a vocabulary edit changes one side
//     and the test says so.
//   * HR-C5-T15 is a regression guard over the frozen HR-09 pair rather than a
//     check on anything this cluster writes. It lives here because it reads the
//     same closed lists the X13 sweep reads, and this cluster moves no HR-09
//     byte.
//
// The markdown parse the HR-09 census needs is a paragraph split and a sentence
// split, a handful of lines of local code that does not earn a helper. Nothing
// under tests/helpers/ is edited.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { loadSpecs } from "../../datagen/src/specLoader.js";
import { loadCanonCompanies } from "../../datagen/src/canon.js";
import { generateArtifact } from "../../datagen/src/engine.js";
import { csvTable, fileByPath } from "../helpers/csv-table.js";
import { moneyMatches } from "../helpers/money-shape.js";
import { addDays, isWeekend } from "../../datagen/src/dates.js";
import { createRng } from "../../datagen/src/seed.js";
import { buildRoster } from "../../datagen/src/generators/core-04-people-roster.js";
import {
  KEY_ORDERS,
  NOTE_BY_LEVEL,
  PROFICIENCY_SCALE,
  ROLE_COMPETENCY_MAP,
} from "../../datagen/src/generators/hr-11-growth-records.js";

const REPO_ROOT = join(import.meta.dirname, "..", "..");
const specs = loadSpecs(join(REPO_ROOT, "specs", "artifact-specs.yaml"));
const canon = loadCanonCompanies(join(REPO_ROOT, "canon", "companies.md"));
const spec = specs.byId.get("HR-11");
const roster = buildRoster(createRng("CORE-04", "roster"));
const rosterById = new Map(roster.map((row) => [row.employee_id, row]));

// The bytes under test are the committed ones, so an edit to a shipped record
// fails the arm that owns the rule it breaks rather than only the byte-diff.
// The regenerated bytes are asserted equal to them below, so a generator edit
// fails here too.
const generated = generateArtifact(spec, canon);
const shipped = (file) =>
  readFileSync(join(REPO_ROOT, "datasets", "hr", "goals-self-assessment-records", file), "utf8");
const grammar = JSON.parse(shipped("growth-grammar.json"));
const goalSet = JSON.parse(shipped("goal-records.json"));
const selfSet = JSON.parse(shipped("self-assessments.json"));
const goals = goalSet.goals;
const assessments = selfSet.self_assessments;

/** The committed review cycle, read off disk rather than through the builder. */
const committed = (file) =>
  csvTable(readFileSync(join(REPO_ROOT, "datasets", "hr", "review-cycle-roster", file), "utf8")).rows;
const cycleRows = committed("review-cycle.csv");
const assignmentRows = committed("review-assignments.csv");

/** The committed HR-01 register, read here rather than through the generator. */
const register = JSON.parse(
  readFileSync(join(REPO_ROOT, "artifacts", "HR-01", "role-requisition-register.json"), "utf8")
);
const library = register.competency_library;
const libraryNameById = new Map(library.map((entry) => [entry.competency_id, entry.name]));

/** The two frozen HR-09 documents, read here for their header lines and for T15. */
const hr09Text = (file) => readFileSync(join(REPO_ROOT, "artifacts", "HR-09", file), "utf8");
const hr09Log = hr09Text("one-to-one-log.md");
const hr09Draft = hr09Text("performance-review-draft.md");

const AS_OF = "2026-04-03";
const GOAL_SETTING_WINDOW = { start: "2025-10-06", end: "2025-10-17" };
const SELF_ASSESSMENT_WINDOW = { start: "2026-03-23", end: "2026-04-02" };
const REVIEW_SCOPE = new Set(["People", "IT & Security"]);
const EMPLOYEE_COUNT = 55;
const GOAL_COUNT = 165;

// The published scale, restated. The stored value is the name; the position
// lives in the scale block and nowhere else.
const PUBLISHED_SCALE = [
  {
    position: 1,
    name: "learning",
    definition: "does this with someone alongside who has done it before, and is still building the habit",
  },
  {
    position: 2,
    name: "applying",
    definition: "does this on their own work without being asked",
  },
  {
    position: 3,
    name: "extending",
    definition: "does this where the work crosses into another team, and can say why they chose what they chose",
  },
  {
    position: 4,
    name: "teaching",
    definition: "is the person another team asks, and the way they do it is the way the team does it",
  },
];
const POSITION_BY_NAME = new Map(PUBLISHED_SCALE.map((level) => [level.name, level.position]));

// The published role map, restated, one row per distinct reviewee role title.
const PUBLISHED_ROLE_MAP = [
  { role_title: "People Operations Specialist", department: "People", competency_ids: ["CMP-04", "CMP-07", "CMP-12"] },
  { role_title: "HR Business Partner", department: "People", competency_ids: ["CMP-04", "CMP-05", "CMP-09"] },
  { role_title: "People Manager", department: "People", competency_ids: ["CMP-05", "CMP-09", "CMP-10"] },
  { role_title: "Recruiter", department: "People", competency_ids: ["CMP-04", "CMP-05", "CMP-06"] },
  { role_title: "Director, People", department: "People", competency_ids: ["CMP-01", "CMP-08", "CMP-10"] },
  { role_title: "Security Engineer", department: "IT & Security", competency_ids: ["CMP-02", "CMP-03", "CMP-12"] },
  { role_title: "IT Administrator", department: "IT & Security", competency_ids: ["CMP-02", "CMP-07", "CMP-12"] },
  { role_title: "IT & Security Manager", department: "IT & Security", competency_ids: ["CMP-01", "CMP-09", "CMP-10"] },
  { role_title: "Director, IT & Security", department: "IT & Security", competency_ids: ["CMP-08", "CMP-09", "CMP-10"] },
];

// The four first-person notes, restated, chosen by self_level alone.
const PUBLISHED_NOTES = {
  learning: "I have done this with someone alongside me and I am still building the habit.",
  applying: "I do this on my own work without being asked.",
  extending: "I do this where the work crosses into another team and I can say why I chose what I chose.",
  teaching: "Other teams ask me how this is done here.",
};

// The three key orders, restated from the spec entry's own sentence.
const PUBLISHED_KEY_ORDERS = {
  grammar: [
    "grammar_id", "as_of", "goal_period_start", "goal_period_end", "review_cycle_id",
    "source_artifacts", "competency_source", "proficiency_scale", "role_competency_map",
    "goal_setting_window", "self_assessment_window", "record_counts", "not_a_rating",
  ],
  goalSet: ["record_set_id", "as_of", "goal_period_start", "goal_period_end", "review_cycle_id", "goals"],
  goal: [
    "goal_id", "employee_id", "full_name", "department", "role_title",
    "competency_id", "competency_name", "goal_statement", "target_level",
    "approved_by_employee_id", "approved_by_full_name", "approved_date",
  ],
  selfAssessmentSet: [
    "record_set_id", "as_of", "goal_period_start", "goal_period_end", "review_cycle_id", "self_assessments",
  ],
  selfAssessment: [
    "self_assessment_id", "employee_id", "full_name", "department", "role_title", "submitted_date", "entries",
  ],
  entry: ["competency_id", "goal_id", "self_level", "note"],
};

// ------------------------------------------------------------- local helpers

const fullName = (row) => `${row.first_name} ${row.last_name}`;

const businessDays = (startIso, endIso) => {
  const out = [];
  for (let day = startIso; day <= endIso; day = addDays(day, 1)) if (!isWeekend(day)) out.push(day);
  return out;
};

/** Every string value anywhere in a JSON-shaped value, keys included. */
const walkStrings = (value, out = []) => {
  if (typeof value === "string") out.push(value);
  else if (Array.isArray(value)) for (const item of value) walkStrings(item, out);
  else if (value && typeof value === "object") {
    for (const [key, item] of Object.entries(value)) {
      out.push(key);
      walkStrings(item, out);
    }
  }
  return out;
};
const everyEmittedString = walkStrings([grammar, goalSet, selfSet]);

/**
 * Token matching with letter boundaries, which is the only reading the frozen
 * lists support: a bare substring sweep makes "template" a deadline lexeme and
 * a surname a frequency adverb.
 */
const carriesToken = (text, token) =>
  new RegExp(`(?<![A-Za-z])${token.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}(?![A-Za-z])`, "i").test(text);

/** HR-09's four closed lists, read out of its own spec entry rather than retyped. */
const closedLists = (() => {
  const entry = specs.byId.get("HR-09").planted_features.find((f) => f.includes("frequency_adverbs is"));
  assert.ok(entry, "the HR-09 spec entry no longer publishes its four closed lists");
  const read = (pattern) => {
    const match = pattern.exec(entry);
    assert.ok(match, `the HR-09 spec entry no longer matches ${pattern}`);
    return match[1].split(", ").map((token) => token.trim());
  };
  const lists = {
    frequency_adverbs: read(/frequency_adverbs is ([^.]+)\./),
    deadline_lexemes: read(/deadline_lexemes is ([^.]+)\./),
    character_claim_phrases: read(/character_claim_phrases is ([^.]+)\./),
    log_deliverables: read(/log_deliverables is the twelve named pieces of work the log discusses: (.+)$/),
  };
  assert.equal(lists.frequency_adverbs.length, 6);
  assert.equal(lists.deadline_lexemes.length, 8);
  assert.equal(lists.character_claim_phrases.length, 5);
  assert.equal(lists.log_deliverables.length, 12);
  return lists;
})();

/** The cycle's own rows, recomputed here. */
const [committedCycle] = cycleRows;
const revieweeIds = [...new Set(assignmentRows.map((row) => row.reviewee_employee_id))].sort();
const assignmentByReviewee = new Map(assignmentRows.map((row) => [row.reviewee_employee_id, row]));

/** Every employee's three position deltas, target minus self, keyed by employee. */
const targetPositionByGoal = new Map(goals.map((goal) => [goal.goal_id, POSITION_BY_NAME.get(goal.target_level)]));
const deltasByEmployee = new Map(
  assessments.map((record) => [
    record.employee_id,
    record.entries.map(
      (entry) => targetPositionByGoal.get(entry.goal_id) - POSITION_BY_NAME.get(entry.self_level)
    ),
  ])
);

// --------------------------------------------------------------------- tests

test("HR-C5-T1: the population is the cycle's reviewee set and the join is total in both directions", () => {
  assert.equal(generated.length, 3, "the generator emits three files");
  for (const file of ["growth-grammar.json", "goal-records.json", "self-assessments.json"]) {
    assert.equal(fileByPath(generated, file).content, shipped(file), `${file} is not what the generator emits`);
  }

  const emitted = [...new Set(goals.map((goal) => goal.employee_id))].sort();
  assert.equal(revieweeIds.length, EMPLOYEE_COUNT);
  assert.equal(emitted.length, EMPLOYEE_COUNT);
  assert.deepEqual(emitted, revieweeIds);
  assert.deepEqual(
    assessments.map((record) => record.employee_id).sort(),
    revieweeIds,
    "a reviewee holds no self-assessment, or a self-assessment names a non-reviewee"
  );

  const goalsByEmployee = new Map();
  for (const goal of goals) {
    if (!goalsByEmployee.has(goal.employee_id)) goalsByEmployee.set(goal.employee_id, []);
    goalsByEmployee.get(goal.employee_id).push(goal);
  }
  for (const employeeId of revieweeIds) {
    assert.equal(goalsByEmployee.get(employeeId).length, 3, `${employeeId} does not hold exactly 3 goals`);
    const held = assessments.filter((record) => record.employee_id === employeeId);
    assert.equal(held.length, 1, `${employeeId} does not hold exactly 1 self-assessment`);
    assert.equal(held[0].entries.length, 3, `${employeeId} does not hold exactly 3 entries`);
  }
  assert.equal(goals.length, GOAL_COUNT);
  assert.equal(assessments.reduce((sum, record) => sum + record.entries.length, 0), GOAL_COUNT);
  assert.deepEqual(grammar.record_counts, {
    employees: EMPLOYEE_COUNT,
    goal_records: GOAL_COUNT,
    self_assessments: EMPLOYEE_COUNT,
    self_assessment_entries: GOAL_COUNT,
  });
});

test("HR-C5-T2: every person resolves to an active roster row, byte-equal on name, department and title", () => {
  const check = (record, what) => {
    const row = rosterById.get(record.employee_id);
    assert.ok(row, `${what} names ${record.employee_id}, which is not a roster row`);
    assert.equal(row.employment_status, "active", `${what} names a departed person`);
    assert.equal(record.full_name, fullName(row), `${what} full name does not match the roster`);
    assert.equal(record.department, row.department, `${what} department does not match the roster`);
    assert.equal(record.role_title, row.role_title, `${what} role title does not match the roster`);
    assert.ok(REVIEW_SCOPE.has(row.department), `${what} sits outside the departments in scope`);
    assert.notEqual(record.employee_id, "EMP-0601", `${what} names the minted lifecycle id`);
    assert.ok(row.start_date <= grammar.goal_period_end, `${what} started after the goal period closed`);
  };
  for (const goal of goals) check(goal, `goal ${goal.goal_id}`);
  for (const record of assessments) check(record, `self-assessment ${record.self_assessment_id}`);
});

test("HR-C5-T3: the role map is nine rows over the frozen library, and every goal set follows its own row", () => {
  assert.deepEqual(grammar.role_competency_map, PUBLISHED_ROLE_MAP);
  assert.deepEqual(ROLE_COMPETENCY_MAP, PUBLISHED_ROLE_MAP, "the generator's exported role map has moved");
  assert.equal(grammar.role_competency_map.length, 9);

  const distinctTitles = [...new Set(assignmentRows.map((row) => row.reviewee_role_title))].sort();
  assert.deepEqual(
    grammar.role_competency_map.map((row) => row.role_title).sort(),
    distinctTitles,
    "the role map key set is not the distinct reviewee role titles"
  );

  const known = new Set(library.map((entry) => entry.competency_id));
  for (const row of grammar.role_competency_map) {
    assert.equal(row.competency_ids.length, 3, `${row.role_title} does not carry 3 ids`);
    assert.equal(new Set(row.competency_ids).size, 3, `${row.role_title} repeats an id`);
    assert.deepEqual([...row.competency_ids].sort(), row.competency_ids, `${row.role_title} is not ascending`);
    for (const competencyId of row.competency_ids) {
      assert.ok(known.has(competencyId), `${row.role_title} names ${competencyId}, absent from the frozen library`);
    }
    const department = grammar.role_competency_map.find((r) => r.role_title === row.role_title).department;
    assert.ok(
      assignmentRows.some((r) => r.reviewee_role_title === row.role_title && r.reviewee_department === department),
      `${row.role_title} is mapped to a department no reviewee holds it in`
    );
  }

  const mapped = new Map(grammar.role_competency_map.map((row) => [row.role_title, row.competency_ids]));
  const byEmployee = new Map();
  for (const goal of goals) {
    if (!byEmployee.has(goal.employee_id)) byEmployee.set(goal.employee_id, []);
    byEmployee.get(goal.employee_id).push(goal);
  }
  for (const [employeeId, held] of byEmployee) {
    const expected = mapped.get(held[0].role_title);
    assert.deepEqual(held.map((goal) => goal.competency_id), expected, `${employeeId} is off its own role row`);
  }
  for (const goal of goals) {
    assert.equal(
      goal.competency_name,
      libraryNameById.get(goal.competency_id),
      `${goal.goal_id} names a competency the frozen library spells differently`
    );
  }
  for (const text of everyEmittedString) {
    assert.ok(!text.includes("CMP-11"), "commercial judgment reaches a growth record");
  }
});

test("HR-C5-T4: every approver is that employee's own reviewer in the cycle, and is active", () => {
  for (const goal of goals) {
    const assignment = assignmentByReviewee.get(goal.employee_id);
    assert.ok(assignment, `${goal.employee_id} holds no assignment in the committed cycle`);
    assert.equal(
      goal.approved_by_employee_id,
      assignment.reviewer_employee_id,
      `${goal.goal_id} is approved by somebody other than its own reviewer`
    );
    const approver = rosterById.get(goal.approved_by_employee_id);
    assert.ok(approver, `${goal.goal_id} names an approver who is not a roster row`);
    assert.equal(approver.employment_status, "active", `${goal.goal_id} names a departed approver`);
    assert.equal(goal.approved_by_full_name, fullName(approver), `${goal.goal_id} approver name is off the roster`);
    assert.equal(goal.approved_by_full_name, assignment.reviewer_full_name);
  }
});

test("HR-C5-T5: the goal period, the cycle reference and the as-of agree with the cycle and the frozen pair", () => {
  assert.equal(grammar.goal_period_start, committedCycle.period_start);
  assert.equal(grammar.goal_period_end, committedCycle.period_end);
  assert.equal(grammar.review_cycle_id, committedCycle.cycle_id);
  const periodLine = `- Period: ${grammar.goal_period_start} to ${grammar.goal_period_end}`;
  assert.ok(hr09Log.includes(periodLine), "the frozen log states another period");
  assert.ok(hr09Draft.includes(periodLine), "the frozen draft states another period");
  for (const [file, body] of [["growth-grammar.json", grammar], ["goal-records.json", goalSet], ["self-assessments.json", selfSet]]) {
    assert.equal(body.as_of, AS_OF, `${file} is as of something else`);
    assert.equal(body.goal_period_start, grammar.goal_period_start, `${file} states another period start`);
    assert.equal(body.goal_period_end, grammar.goal_period_end, `${file} states another period end`);
    assert.equal(body.review_cycle_id, committedCycle.cycle_id, `${file} references another cycle`);
  }
  assert.deepEqual(grammar.goal_setting_window, GOAL_SETTING_WINDOW);
  assert.deepEqual(grammar.self_assessment_window, SELF_ASSESSMENT_WINDOW);
  assert.equal(grammar.self_assessment_window.start, committedCycle.cycle_open_date);
  assert.equal(grammar.competency_source, "role-requisition-register.json");
});

test("HR-C5-T6: every date is a business day inside its own window, and nothing is dated after the as-of", () => {
  const approvalDays = new Set(businessDays(GOAL_SETTING_WINDOW.start, GOAL_SETTING_WINDOW.end));
  const submissionDays = new Set(businessDays(SELF_ASSESSMENT_WINDOW.start, SELF_ASSESSMENT_WINDOW.end));
  assert.equal(approvalDays.size, 10);
  assert.equal(submissionDays.size, 9);

  const approvedByEmployee = new Map();
  for (const goal of goals) {
    assert.ok(approvalDays.has(goal.approved_date), `${goal.goal_id} is approved on ${goal.approved_date}`);
    if (!approvedByEmployee.has(goal.employee_id)) approvedByEmployee.set(goal.employee_id, new Set());
    approvedByEmployee.get(goal.employee_id).add(goal.approved_date);
  }
  for (const [employeeId, dates] of approvedByEmployee) {
    assert.equal(dates.size, 1, `${employeeId} holds goals approved on more than one date`);
  }
  for (const record of assessments) {
    assert.ok(
      submissionDays.has(record.submitted_date),
      `${record.self_assessment_id} is submitted on ${record.submitted_date}`
    );
  }
  assert.equal(assessments.filter((record) => record.submitted_date !== "").length, EMPLOYEE_COUNT);
  for (const text of everyEmittedString) {
    for (const date of text.match(/\d{4}-\d{2}-\d{2}/g) ?? []) {
      assert.ok(date <= AS_OF, `an emitted date ${date} sits after the as-of`);
    }
  }
});

test("HR-C5-T7: every level is a published name, the scale carries four positions, and no figure sits beside a name", () => {
  assert.deepEqual(grammar.proficiency_scale, PUBLISHED_SCALE);
  assert.deepEqual(PROFICIENCY_SCALE, PUBLISHED_SCALE, "the generator's exported scale has moved");
  assert.deepEqual(grammar.proficiency_scale.map((level) => level.position), [1, 2, 3, 4]);
  for (const level of grammar.proficiency_scale) {
    assert.equal(typeof level.definition, "string");
    assert.ok(level.definition.length > 0, `${level.name} carries no definition`);
  }
  const names = new Set(PUBLISHED_SCALE.map((level) => level.name));
  for (const goal of goals) {
    assert.ok(names.has(goal.target_level), `${goal.goal_id} aims at "${goal.target_level}"`);
    assert.equal(typeof goal.target_level, "string");
  }
  for (const record of assessments) {
    for (const entry of record.entries) {
      assert.ok(names.has(entry.self_level), `${entry.goal_id} places a person at "${entry.self_level}"`);
      assert.equal(typeof entry.self_level, "string");
    }
  }
  const noNumbers = (value, path) => {
    if (typeof value === "number") assert.fail(`${path} carries the bare figure ${value}`);
    else if (Array.isArray(value)) value.forEach((item, index) => noNumbers(item, `${path}[${index}]`));
    else if (value && typeof value === "object") {
      for (const [key, item] of Object.entries(value)) noNumbers(item, `${path}.${key}`);
    }
  };
  noNumbers(goalSet, "goal-records.json");
  noNumbers(selfSet, "self-assessments.json");
});

test("HR-C5-T8: one two-level delta, and every other census the record set is built to", () => {
  const entryCensus = { "2": 0, "1": 0, "0": 0, "-1": 0 };
  let twoLevelEntries = 0;
  for (const deltas of deltasByEmployee.values()) {
    for (const delta of deltas) {
      assert.ok(delta in entryCensus, `an entry sits at a delta of ${delta}`);
      entryCensus[delta] += 1;
      if (delta >= 2) twoLevelEntries += 1;
    }
  }
  assert.deepEqual(entryCensus, { "2": 1, "1": 44, "0": 100, "-1": 20 });
  assert.equal(twoLevelEntries, 1, "the two-level delta is not a single entry");

  const census = (predicate) => [...deltasByEmployee.values()].filter(predicate).length;
  assert.equal(census((deltas) => deltas.some((delta) => delta >= 2)), 1);
  assert.equal(census((deltas) => deltas.some((delta) => Math.abs(delta) >= 2)), 1, "the absolute census differs");
  assert.equal(census((deltas) => deltas.reduce((sum, delta) => sum + delta, 0) >= 2), 11);
  assert.equal(census((deltas) => deltas.some((delta) => delta > 0)), 31);
  assert.equal(census((deltas) => deltas.some((delta) => delta < 0)), 20);
  assert.equal(census((deltas) => deltas.every((delta) => delta === 0)), 8);

  const carriers = [...deltasByEmployee.entries()].filter(([, deltas]) => deltas.some((delta) => delta >= 2));
  assert.equal(carriers.length, 1);
  for (const [employeeId, deltas] of deltasByEmployee) {
    if (employeeId === carriers[0][0]) continue;
    for (const delta of deltas) {
      assert.ok(Math.abs(delta) <= 1, `a second employee sits ${delta} levels from one of their own goals`);
    }
  }
  assert.ok(
    !carriers[0][1].every((delta) => delta === 0),
    "the conflict carrier cannot also be one of the employees in agreement on all three"
  );
});

test("HR-C5-T9: the conflict carrier satisfies all six clauses, each recomputed from the committed cycle", () => {
  const [carrierId] = [...deltasByEmployee.entries()].find(([, deltas]) => deltas.some((delta) => delta >= 2));

  // clause 3 and clause 4: the single assignment outstanding and past its due date
  const pastDue = assignmentRows.filter((row) => row.submitted_date === "" && row.due_date < AS_OF);
  assert.equal(pastDue.length, 1, "the cycle no longer holds exactly one outstanding past-due assignment");

  // clause 5: the frozen pair, read off the two documents' own header lines
  const headerName = (text, label) => {
    const match = new RegExp(`^- ${label}: (.+?) \\((.+?)\\)$`, "m").exec(text);
    assert.ok(match, `the frozen HR-09 document carries no "- ${label}:" line`);
    return match[1];
  };
  const pairIds = [headerName(hr09Draft, "Manager"), headerName(hr09Draft, "Report")].map((name) => {
    const rows = roster.filter((row) => fullName(row) === name && row.employment_status === "active");
    assert.equal(rows.length, 1, `the frozen HR-09 name "${name}" does not resolve to one active row`);
    return rows[0].employee_id;
  });

  const satisfies = (employeeId) => {
    const row = rosterById.get(employeeId);
    const assignment = assignmentByReviewee.get(employeeId);
    return (
      Boolean(assignment)
      && row.level === "IC"
      && employeeId !== pastDue[0].reviewer_employee_id
      && employeeId !== pastDue[0].reviewee_employee_id
      && !pairIds.includes(employeeId)
      && rosterById.get(assignment.reviewer_employee_id).employment_status === "active"
    );
  };
  const candidates = revieweeIds.filter(satisfies);
  assert.ok(candidates.length > 0, "no reviewee satisfies the six clauses, so the conflict cannot be drawn by rule");
  assert.ok(satisfies(carrierId), "the conflict carrier fails one of the six clauses");
});

test("HR-C5-T10: X13, no emitted string carries a token from any of the four frozen lists", () => {
  for (const text of everyEmittedString) {
    for (const [listName, tokens] of Object.entries(closedLists)) {
      for (const token of tokens) {
        assert.ok(
          !carriesToken(text, token),
          `an emitted string carries "${token}" from the frozen ${listName} list`
        );
      }
    }
  }
  for (const record of assessments) {
    for (const entry of record.entries) {
      assert.equal(entry.note, PUBLISHED_NOTES[entry.self_level], "a note is not the published sentence");
    }
  }
  assert.deepEqual(NOTE_BY_LEVEL, PUBLISHED_NOTES, "the generator's exported notes have moved");
  for (const goal of goals) {
    assert.equal(
      goal.goal_statement,
      `Reach ${goal.target_level} on ${goal.competency_name} by ${grammar.goal_period_end}.`,
      `${goal.goal_id} does not match the published template`
    );
  }
});

test("HR-C5-T11: the key orders, the id blocks, and the absences the house rules require", () => {
  assert.deepEqual(Object.keys(grammar), PUBLISHED_KEY_ORDERS.grammar);
  assert.deepEqual(Object.keys(goalSet), PUBLISHED_KEY_ORDERS.goalSet);
  assert.deepEqual(Object.keys(selfSet), PUBLISHED_KEY_ORDERS.selfAssessmentSet);
  for (const goal of goals) assert.deepEqual(Object.keys(goal), PUBLISHED_KEY_ORDERS.goal);
  for (const record of assessments) {
    assert.deepEqual(Object.keys(record), PUBLISHED_KEY_ORDERS.selfAssessment);
    for (const entry of record.entries) assert.deepEqual(Object.keys(entry), PUBLISHED_KEY_ORDERS.entry);
  }
  assert.deepEqual(KEY_ORDERS, PUBLISHED_KEY_ORDERS, "the generator's exported key orders have moved");

  const goalIds = goals.map((goal) => goal.goal_id);
  assert.equal(new Set(goalIds).size, goalIds.length, "a goal id appears twice");
  goalIds.forEach((goalId, index) => {
    assert.equal(goalId, `GOL-2026-${String(index + 1).padStart(4, "0")}`, "the goal ids are not dense");
  });
  const sortedGoals = [...goals].sort(
    (a, b) => a.employee_id.localeCompare(b.employee_id) || a.competency_id.localeCompare(b.competency_id)
  );
  assert.deepEqual(sortedGoals.map((goal) => goal.goal_id), goalIds, "the goal ids are out of their stated order");
  const assessmentIds = assessments.map((record) => record.self_assessment_id);
  assert.equal(new Set(assessmentIds).size, assessmentIds.length, "a self-assessment id appears twice");
  assessmentIds.forEach((assessmentId, index) => {
    assert.equal(assessmentId, `GSA-2026-${String(index + 1).padStart(4, "0")}`);
  });
  assert.deepEqual(
    [...assessments].sort((a, b) => a.employee_id.localeCompare(b.employee_id)).map((r) => r.self_assessment_id),
    assessmentIds,
    "the self-assessment ids are out of employee_id order"
  );

  const knownGoalIds = new Set(goalIds);
  const knownAssessmentIds = new Set(assessmentIds);
  const forbidden = ["salary", "pay_band", "rating", "score", "date_of_birth", "home_city", "EMP-0601", "ca-", "HRC-", "RQN-"];
  // The one exemption, and it is a field name rather than a value: the grammar
  // publishes its classification argument under `not_a_rating`, which is the
  // artifact saying it carries no rating. Every other string is swept whole, so
  // a field called `performance_rating` or a value carrying a score is caught.
  const publishedKeyExemptions = new Set(["not_a_rating"]);
  for (const text of everyEmittedString) {
    if (text.includes("GOL-")) assert.ok(knownGoalIds.has(text), `"GOL-" reaches the string "${text}"`);
    if (text.includes("GSA-")) assert.ok(knownAssessmentIds.has(text), `"GSA-" reaches the string "${text}"`);
    assert.ok(!text.includes("—") && !text.includes("–"), `an emitted string carries a long dash`);
    assert.ok(!text.includes("$") && !text.includes("%"), `an emitted string carries a money or percentage mark`);
    assert.deepEqual(moneyMatches(text), [], `an emitted string carries a money-shaped figure`);
    assert.ok(!/\d{2}:\d{2}/.test(text), "an emitted string carries a time of day");
    if (publishedKeyExemptions.has(text)) continue;
    for (const token of forbidden) {
      assert.ok(!text.includes(token), `an emitted string carries the token "${token}"`);
    }
  }
});

test("HR-C5-T15: the frozen HR-09 census still reads as the module it feeds was built against", () => {
  const sentences = hr09Draft
    .split("\n")
    .filter((line) => line.trim() !== "" && !line.startsWith("#") && !line.startsWith("- "))
    .flatMap((paragraph) => paragraph.split(/(?<=\.)\s+/))
    .map((sentence) => sentence.trim())
    .filter(Boolean);
  assert.ok(sentences.length >= 14 && sentences.length <= 18, `the draft carries ${sentences.length} sentences`);

  const anyOf = (text, tokens) => tokens.some((token) => carriesToken(text, token));
  const carriesDate = (text) =>
    /\b\d{1,2} (January|February|March|April|May|June|July|August|September|October|November|December) \d{4}\b/i
      .test(text);

  const deadlineSentences = sentences.filter((s) => anyOf(s, closedLists.deadline_lexemes));
  const characterSentences = sentences.filter((s) => anyOf(s, closedLists.character_claim_phrases));
  assert.equal(deadlineSentences.length, 3, "the deadline-lexeme population has moved");
  assert.equal(characterSentences.length, 2, "the character-phrase population has moved");

  const logEntries = hr09Log.match(/^### (\d{4}-\d{2}-\d{2})$/gm) ?? [];
  assert.equal(logEntries.length, 12, "the frozen log no longer carries twelve sessions");
  const logMonths = new Set(logEntries.map((line) => line.slice(4, 11)));
  assert.deepEqual(
    [...logMonths].sort(),
    ["2025-10", "2025-11", "2025-12", "2026-01", "2026-02", "2026-03"],
    "a month of the review period carries no logged session"
  );
  assert.ok(
    !anyOf(hr09Log, closedLists.deadline_lexemes),
    "the frozen log now carries a deadline lexeme, so the unsupported frequency claim is no longer unsupported"
  );

  const unsupportedFrequency = deadlineSentences.filter((s) => anyOf(s, closedLists.frequency_adverbs));
  assert.equal(unsupportedFrequency.length, 1, "the unsupported frequency claim census has moved");
  const unsupportedCharacter = characterSentences.filter(
    (s) => !carriesDate(s) && !anyOf(s, closedLists.log_deliverables)
  );
  assert.equal(unsupportedCharacter.length, 1, "the unsupported character claim census has moved");
  assert.notEqual(
    unsupportedFrequency[0],
    unsupportedCharacter[0],
    "the two plants are different sentences of different classes"
  );
});
