// HR-12 compensation-band-dataset: the guard over the band library, over the
// join between the general ledger and what this company pays, and over the two
// places the file carries a finding a reader has to compute rather than read.
//
// Four disciplines run through every check.
//
//   * No test names the employee paid above their own band, the group whose two
//     cohort means sit apart, or the band either of them belongs to. Both are
//     found by rule over the emitted bytes and asserted by cardinality, so a
//     reroll that moves one stays green and a reroll that destroys one fails.
//   * The population, the ledger, the review cycle, the mixed sensitivity
//     record set and the artifacts/ name sweep are read off disk here, never
//     through the shared builder the generator uses, because the claim under
//     test is that this artifact agrees with the committed pack rather than
//     that two calls of one function agree.
//   * The column lists come out of spec.files rather than being restated, so a
//     dropped column is a red gate.
//   * The published vocabularies and the three multiplier tables are restated
//     literally below, parsed back out of the shipped grammar row and asserted
//     equal to the generator's exported copies, the HR-18 discipline, so a
//     vocabulary edit changes one side and the test says so.
//
// The header parse the frozen one-to-one pair needs is two regular expressions
// over two markdown lines, a handful of lines of local code that does not earn
// a helper. tests/helpers/csv-table.js reads the seven CSVs and
// tests/helpers/money-shape.js runs the money screen; nothing under
// tests/helpers/ is edited.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { loadSpecs } from "../../datagen/src/specLoader.js";
import { loadCanonCompanies } from "../../datagen/src/canon.js";
import { generateArtifact } from "../../datagen/src/engine.js";
import { csvTable, fileByPath } from "../helpers/csv-table.js";
import { moneyMatches } from "../helpers/money-shape.js";
import { isWeekend } from "../../datagen/src/dates.js";
import { createRng } from "../../datagen/src/seed.js";
import {
  BAND_TIERS,
  BAND_TIERS_VOCABULARY,
  COHORTS,
  DEPARTMENT_INDEX,
  LEVEL_MULTIPLIERS,
  LOCATION_COMPA_RANGES,
  TIER_CENSUS,
  TIER_MULTIPLIERS,
  WORK_LOCATIONS,
  monthsBetween,
} from "../../datagen/src/generators/hr-12-compensation-bands.js";

const REPO_ROOT = join(import.meta.dirname, "..", "..");
const specs = loadSpecs(join(REPO_ROOT, "specs", "artifact-specs.yaml"));
const canon = loadCanonCompanies(join(REPO_ROOT, "canon", "companies.md"));
const spec = specs.byId.get("HR-12");

// The bytes under test are the committed ones, so an edit to a shipped row
// fails the arm that owns the rule it breaks rather than only the byte diff.
// The regenerated bytes are asserted equal to them below, so a generator edit
// fails here too.
const generated = generateArtifact(spec, canon);
const shipped = (file) =>
  readFileSync(join(REPO_ROOT, "datasets", "hr", "compensation-band-dataset", file), "utf8");
const grammarTable = csvTable(shipped("compensation-grammar.csv"));
const bandTable = csvTable(shipped("compensation-bands.csv"));
const employeeTable = csvTable(shipped("employee-compensation.csv"));
const grammar = grammarTable.rows[0];
const bands = bandTable.rows;
const employees = employeeTable.rows;
const bandById = new Map(bands.map((row) => [row.band_id, row]));
const shippedFiles = [
  ["compensation-grammar.csv", grammarTable],
  ["compensation-bands.csv", bandTable],
  ["employee-compensation.csv", employeeTable],
];
const allText = ["compensation-grammar.csv", "compensation-bands.csv", "employee-compensation.csv"]
  .map(shipped).join("\n");

/** The committed roster, read off disk rather than through the shared builder. */
const rosterRows = csvTable(readFileSync(join(REPO_ROOT, "datasets", "core", "people-roster", "people-roster.csv"), "utf8")).rows;
const activeRoster = rosterRows.filter((row) => row.employment_status === "active");
const rosterById = new Map(rosterRows.map((row) => [row.employee_id, row]));

/** The committed review cycle and the committed offboarding set, read the same way. */
const assignments = csvTable(readFileSync(join(REPO_ROOT, "datasets", "hr", "review-cycle-roster", "review-assignments.csv"), "utf8")).rows;
const exitRecord = csvTable(readFileSync(join(REPO_ROOT, "datasets", "hr", "offboarding-checklist-access-inventory", "exit-record.csv"), "utf8")).rows;
const sensitivityRows = csvTable(readFileSync(join(REPO_ROOT, "datasets", "hr", "mixed-sensitivity-employee-dataset", "mixed-sensitivity-employee-dataset.csv"), "utf8")).rows;

/** The committed general ledger and the committed driver pack. */
const actuals = csvTable(readFileSync(join(REPO_ROOT, "datasets", "finance", "actuals-24mo", "actuals-24mo.csv"), "utf8")).rows;
const driversText = readFileSync(join(REPO_ROOT, "datasets", "finance", "drivers", "drivers.yaml"), "utf8");

const AS_OF = "2026-04-03";
const KEY = (roleTitle, level) => `${roleTitle}::${level}`;
const num = (value) => Number(value);
const round2 = (n) => Math.round(n * 100) / 100;
const round4 = (n) => Math.round(n * 10000) / 10000;
const mean = (values) => values.reduce((sum, value) => sum + value, 0) / values.length;
const median = (values) => {
  const sorted = values.slice().sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 === 1 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
};

// ------------------------------------------ the published tables, restated

const PUBLISHED_LEVEL_MULTIPLIERS = {
  IC: 1.00, Manager: 1.55, Director: 2.15, VP: 3.10, Executive: 4.60,
};
const PUBLISHED_DEPARTMENT_INDEX = {
  Engineering: 1.22, Product: 1.16, "IT & Security": 1.12, Legal: 1.10, Finance: 1.04,
  Sales: 1.02, Marketing: 0.98, People: 0.96, Operations: 0.94, "Customer Success": 0.90,
  Executive: 1.00,
};
const PUBLISHED_TIER_MULTIPLIERS = { entry: 0.82, core: 1.00, senior: 1.18, principal: 1.38 };
const PUBLISHED_TIERS = ["entry", "core", "senior", "principal"];
const PUBLISHED_TIER_CENSUS = { entry: 7, core: 51, senior: 4, principal: 1 };
const PUBLISHED_WORK_LOCATIONS = ["remote", "headquarters", "satellite_office"];
const PUBLISHED_LOCATION_RANGES = {
  remote: { low: 0.815, high: 0.955 },
  satellite_office: { low: 0.865, high: 1.005 },
  headquarters: { low: 0.915, high: 1.055 },
};
const PUBLISHED_COHORTS = ["cohort_a", "cohort_b"];
const PUBLISHED_SPREAD = 20;
const PUBLISHED_MINIMUM_GROUP_SIZE = 5;
const PUBLISHED_COMPA_FLOOR = 0.800;
const PUBLISHED_COMPA_CEILING = 1.200;
const PUBLISHED_GAP_THRESHOLD = 5.00;
const PUBLISHED_REMEDIATION_MONTHS = 6;
const PUBLISHED_TENURE_TOLERANCE = 18;
const PUBLISHED_LOCATION_TOLERANCE = 25.0;
const PUBLISHED_COVERAGE_FLOOR = 0.9390;
const PUBLISHED_COVERAGE_CEILING = 0.9410;

// ------------------------------------- the constructed censuses, restated
// Design targets rather than byte facts of the roster. Each one is recomputed
// from the shipped bytes below, and each one is a census rather than a row: no
// figure here says which employee, which group or which band it lands on.

const BAND_ROWS = 63;
const EMPLOYEE_ROWS = 582;
const EVALUABLE_GROUPS = 24;
const EVALUABLE_COVERAGE = 442;
const ABOVE_BAND_CENSUS = 1;
const BELOW_BAND_CENSUS = 0;
const BOUNDARY_EXACT_CENSUS = 4;
const OPEN_INTERVAL_CENSUS = 5;
const TOP_TAIL_CENSUS = 3;
const BOTTOM_TAIL_CENSUS = 6;
const CANDIDATE_SET_CENSUS = 371;
const PLANT_GAP_LOW = 6.50;
const PLANT_GAP_HIGH = 8.50;
const NON_PLANT_GAP_LIMIT = 1.80;
const ALL_GROUPS_OVER_THRESHOLD_CENSUS = 13;
const EVALUABLE_AT_TWO_PERCENT_CENSUS = 1;
const COHORT_A_LEADS_CENSUS = 13;
const STALE_BAND_CENSUS = 44;
const BOTH_LIMBS_CENSUS = 1;

// ------------------------------------------------------- derived structures

const groups = new Map();
for (const row of employees) {
  if (!groups.has(row.band_id)) {
    groups.set(row.band_id, { band: bandById.get(row.band_id), cohort_a: [], cohort_b: [] });
  }
  groups.get(row.band_id)[row.synthetic_equity_cohort].push(row);
}
const groupList = [...groups.values()];
const memberCount = (group) => group.cohort_a.length + group.cohort_b.length;
const isEvaluable = (group) =>
  group.cohort_a.length >= PUBLISHED_MINIMUM_GROUP_SIZE && group.cohort_b.length >= PUBLISHED_MINIMUM_GROUP_SIZE;
const evaluableGroups = groupList.filter(isEvaluable);
const gapOf = (group) => {
  const meanA = mean(group.cohort_a.map((row) => num(row.base_pay_amount)));
  const meanB = mean(group.cohort_b.map((row) => num(row.base_pay_amount)));
  return round2((100 * (meanA - meanB)) / meanA);
};
const tenureMonths = (employeeId) => monthsBetween(rosterById.get(employeeId).start_date, AS_OF);

/** The one group whose two cohort means sit at or beyond the published threshold. */
const breachingGroups = evaluableGroups.filter((group) => Math.abs(gapOf(group)) >= PUBLISHED_GAP_THRESHOLD);

/** The one employee paid above their own band maximum. */
const aboveBand = employees.filter((row) => num(row.base_pay_amount) > num(bandById.get(row.band_id).band_max));

function parseTable(cell, parse = Number) {
  return Object.fromEntries(cell.split(";").map((pair) => {
    const at = pair.indexOf("=");
    return [pair.slice(0, at), parse(pair.slice(at + 1))];
  }));
}

// -------------------------------------------------------------------- tests

test("HR-C6-T1: the band library is one row per active role title and level pair, keyed and ordered by it", () => {
  assert.deepEqual(bandTable.cols, spec.files["compensation-bands.csv"]);
  assert.equal(bands.length, BAND_ROWS);
  assert.equal(num(grammar.band_count), BAND_ROWS);

  const rosterPairs = new Map();
  for (const row of activeRoster) {
    const key = KEY(row.role_title, row.level);
    if (!rosterPairs.has(key)) rosterPairs.set(key, new Set());
    rosterPairs.get(key).add(row.department);
  }
  assert.equal(rosterPairs.size, BAND_ROWS, "the committed roster no longer forms the pair set the band table is built over");
  assert.deepEqual(
    bands.map((row) => KEY(row.role_title, row.level)).sort(),
    [...rosterPairs.keys()].sort(),
    "the band table's pair set and the roster's do not agree"
  );
  for (const row of bands) {
    const departments = rosterPairs.get(KEY(row.role_title, row.level));
    assert.equal(departments.size, 1, `${row.role_title} at ${row.level} spans more than one department`);
    assert.equal(row.department, [...departments][0], `${row.band_id} carries a department the pair does not resolve to`);
    assert.equal(
      num(row.headcount_in_band),
      activeRoster.filter((p) => KEY(p.role_title, p.level) === KEY(row.role_title, row.level)).length,
      `${row.band_id} carries a headcount the roster does not recompute`
    );
  }

  const ascending = bands.map((row) => KEY(row.role_title, row.level));
  assert.deepEqual(ascending, [...ascending].sort(), "the band rows are not in role title and level ascending order");
  bands.forEach((row, index) => {
    assert.equal(row.band_id, `BND-${String(index + 1).padStart(2, "0")}`, "the band id block is not dense in the stated order");
  });
  assert.equal(new Set(bands.map((row) => row.band_id)).size, BAND_ROWS);
  const tokens = new Set(allText.match(/BND-[0-9]+/g) ?? []);
  for (const token of tokens) {
    assert.ok(bandById.has(token), `${token} is not one of this artifact's band ids`);
  }
});

test("HR-C6-T2: one pay row per active employee, and no employee keyed row restates a roster column", () => {
  assert.deepEqual(employeeTable.cols, spec.files["employee-compensation.csv"]);
  assert.equal(employees.length, EMPLOYEE_ROWS);
  assert.equal(num(grammar.employee_count), EMPLOYEE_ROWS);

  const shippedIds = employees.map((row) => row.employee_id);
  assert.equal(new Set(shippedIds).size, EMPLOYEE_ROWS, "an employee holds more than one pay row");
  assert.deepEqual(
    shippedIds.slice().sort(),
    activeRoster.map((row) => row.employee_id).sort(),
    "the pay file and the roster's active population do not agree, in one direction or the other"
  );
  assert.deepEqual(shippedIds, [...shippedIds].sort(), "the pay rows are not in employee id order");
  for (const row of employees) {
    assert.ok(bandById.has(row.band_id), `${row.employee_id} carries a band id the library does not hold`);
    const rosterRow = rosterById.get(row.employee_id);
    assert.equal(row.band_id, bands.find((b) => KEY(b.role_title, b.level) === KEY(rosterRow.role_title, rosterRow.level)).band_id);
  }

  const forbidden = ["first_name", "last_name", "full_name", "name", "email", "work_email",
    "department", "role_title", "level", "manager_employee_id", "manager", "start_date", "hire_date",
    "compa_ratio", "gap_pct", "flag"];
  for (const column of forbidden) {
    assert.ok(!employeeTable.cols.includes(column), `the pay file carries a ${column} column`);
  }
  const names = new Set(rosterRows.map((row) => `${row.first_name} ${row.last_name}`));
  const employeeText = shipped("employee-compensation.csv");
  for (const name of names) {
    assert.ok(!employeeText.includes(name), "the pay file carries a roster full name");
  }
  assert.ok(!/@co002\.example/.test(allText), "a C6 byte carries a work email address");
});

test("HR-C6-T3: every band figure recomputes from the published unit and the three published tables", () => {
  assert.deepEqual(grammarTable.cols, spec.files["compensation-grammar.csv"]);
  assert.equal(grammarTable.rows.length, 1);

  // The tables come back out of the grammar row, are asserted equal to the
  // copies restated at the top of this file, and those copies are asserted
  // equal to the generator's exported ones. An edit moves one of the three.
  const levels = parseTable(grammar.level_multipliers);
  const departments = parseTable(grammar.department_index);
  const tiers = parseTable(grammar.tier_multipliers);
  assert.deepEqual(levels, PUBLISHED_LEVEL_MULTIPLIERS);
  assert.deepEqual(departments, PUBLISHED_DEPARTMENT_INDEX);
  assert.deepEqual(tiers, PUBLISHED_TIER_MULTIPLIERS);
  assert.deepEqual(LEVEL_MULTIPLIERS, PUBLISHED_LEVEL_MULTIPLIERS);
  assert.deepEqual(DEPARTMENT_INDEX, PUBLISHED_DEPARTMENT_INDEX);
  assert.deepEqual(TIER_MULTIPLIERS, PUBLISHED_TIER_MULTIPLIERS);
  assert.deepEqual(BAND_TIERS_VOCABULARY, PUBLISHED_TIERS);
  assert.deepEqual(TIER_CENSUS, PUBLISHED_TIER_CENSUS);
  assert.deepEqual(WORK_LOCATIONS, PUBLISHED_WORK_LOCATIONS);
  assert.deepEqual(COHORTS, PUBLISHED_COHORTS);
  assert.deepEqual(LOCATION_COMPA_RANGES, PUBLISHED_LOCATION_RANGES);
  assert.equal(num(grammar.band_spread_below_pct), PUBLISHED_SPREAD);
  assert.equal(num(grammar.band_spread_above_pct), PUBLISHED_SPREAD);

  // The shipped tier column against the generator's exported design map.
  const exported = new Map(BAND_TIERS.map((entry) => [KEY(entry.role_title, entry.level), entry.band_tier]));
  const census = { entry: 0, core: 0, senior: 0, principal: 0 };
  for (const row of bands) {
    assert.ok(PUBLISHED_TIERS.includes(row.band_tier), `${row.band_id} carries a tier that is not published`);
    assert.equal(row.band_tier, exported.get(KEY(row.role_title, row.level)), `${row.band_id} ships a tier the generator's table does not carry`);
    census[row.band_tier] += 1;
  }
  assert.deepEqual(census, PUBLISHED_TIER_CENSUS);

  const unit = num(grammar.band_unit_amount);
  assert.match(grammar.band_unit_amount, /^\d+\.\d{2}$/);
  for (const row of bands) {
    const mid = round2(unit * levels[row.level] * departments[row.department] * tiers[row.band_tier]);
    assert.equal(num(row.band_mid), mid, `${row.band_id} mid does not recompute from the unit and the three tables`);
    assert.equal(num(row.band_min), round2(mid * (1 - PUBLISHED_SPREAD / 100)), `${row.band_id} minimum is not the mid less the published spread`);
    assert.equal(num(row.band_max), round2(mid * (1 + PUBLISHED_SPREAD / 100)), `${row.band_id} maximum is not the mid plus the published spread`);
  }
});

test("HR-C6-T4: the emitted total ties to the general ledger at the published coverage ratio", () => {
  const total = round2(employees.reduce((sum, row) => sum + num(row.base_pay_amount), 0));
  assert.equal(total, num(grammar.annual_base_pay_total), "the pay rows do not sum to the published total");

  assert.equal(grammar.finance_source_period, "2026-03");
  const accounts = grammar.finance_source_accounts.split(";");
  assert.deepEqual(accounts, ["6000", "5020"]);
  const marchRows = actuals.filter((row) => row.period === grammar.finance_source_period && accounts.includes(row.account_code));
  assert.equal(marchRows.length, accounts.length, "the committed actuals do not carry exactly one row per named account for the named period");
  const marchTotal = round2(marchRows.reduce((sum, row) => sum + num(row.actual_amount), 0));
  assert.ok(marchTotal > 0);

  const ratio = round4(total / (12 * marchTotal));
  assert.equal(ratio, num(grammar.finance_coverage_ratio), "the published coverage ratio is not the one the bytes recompute");
  assert.ok(ratio >= PUBLISHED_COVERAGE_FLOOR && ratio <= PUBLISHED_COVERAGE_CEILING, `the coverage ratio ${ratio} sits outside the guarded band`);

  // The driver pack's own fully loaded figure, recomputed here, is what the
  // remainder in the coverage ratio is: base pay is a subset of people cost.
  const perHead = /value_usd: "([0-9.]+)"/.exec(driversText);
  const headcount = /headcount: (\d+)/.exec(driversText);
  assert.ok(perHead && headcount, "the committed driver pack no longer publishes a fully loaded cost per head");
  assert.equal(num(headcount[1]), EMPLOYEE_ROWS);
  const loadedAnnual = num(perHead[1]) * num(headcount[1]) * 12;
  const fourAccountRows = actuals.filter((row) => row.period === "2026-03" && ["6000", "6010", "6020", "5020"].includes(row.account_code));
  assert.equal(fourAccountRows.length, 4);
  const fourAccountAnnual = 12 * fourAccountRows.reduce((sum, row) => sum + num(row.actual_amount), 0);
  assert.ok(Math.abs(loadedAnnual - fourAccountAnnual) <= 12 * 0.01 * EMPLOYEE_ROWS, "the driver pack's cost per head no longer recomputes from the four accounts it names");
  assert.ok(total < fourAccountAnnual, "the emitted base pay total is not a subset of the fully loaded people cost");
});

test("HR-C6-T5: every amount is a 2dp string in a band, and no money hides in a column that is not one", () => {
  const moneyColumns = {
    "compensation-grammar.csv": ["band_unit_amount", "annual_base_pay_total"],
    "compensation-bands.csv": ["band_min", "band_mid", "band_max"],
    "employee-compensation.csv": ["base_pay_amount"],
  };
  // The grammar's parameter columns carry published multipliers, thresholds and
  // ratios whose exact values T3 and T11 assert against restated literals, so a
  // money shape inside them is already pinned by name. Every other cell is
  // screened, which is where an unsourced figure would actually hide.
  const parameterColumns = [
    "level_multipliers", "department_index", "tier_multipliers", "location_compa_ranges",
    "unadjusted_gap_threshold_pct", "tenure_increment_per_year", "tenure_increment_cap",
    "location_mix_tolerance_pct", "finance_coverage_ratio", "band_spread_below_pct",
    "band_spread_above_pct", "median_tenure_tolerance_months", "minimum_group_size",
    "remediation_window_months",
  ];

  for (const row of bands) {
    for (const column of moneyColumns["compensation-bands.csv"]) {
      assert.match(row[column], /^\d+\.\d{2}$/, `${row.band_id} ${column} is not a 2dp string`);
    }
    assert.equal(row.currency, "USD");
  }
  for (const row of employees) {
    assert.match(row.base_pay_amount, /^\d+\.\d{2}$/, `${row.employee_id} base pay is not a 2dp string`);
    assert.equal(row.currency, "USD");
    assert.equal(row.pay_basis, grammar.pay_basis);
  }
  assert.equal(grammar.currency, "USD");
  assert.ok(!allText.includes("$"), "a C6 cell carries a currency symbol");
  assert.ok(!/\d,\d{3}/.test(bands.concat(employees).flatMap((row) => Object.values(row)).join("\n")), "a C6 cell carries a thousands separator");

  for (const [path, table] of shippedFiles) {
    const money = moneyColumns[path];
    for (const row of table.rows) {
      for (const [column, value] of Object.entries(row)) {
        if (money.includes(column)) continue;
        if (path === "compensation-grammar.csv" && parameterColumns.includes(column)) continue;
        assert.deepEqual(moneyMatches(String(value)), [], `${path} carries a money shape in ${column}`);
      }
    }
  }

  // Every pay row is inside its own band and every ratio is inside the
  // published one, and the single exception is the finding. The ratio is
  // compared at four decimals because a band end is the mid times the spread
  // rounded to the cent, so a row held exactly on an end recomputes to the end
  // plus or minus a fraction of a cent.
  let outsideBand = 0;
  let outsideRatio = 0;
  for (const row of employees) {
    const band = bandById.get(row.band_id);
    const pay = num(row.base_pay_amount);
    if (pay < num(band.band_min) || pay > num(band.band_max)) outsideBand += 1;
    const ratio = round4(pay / num(band.band_mid));
    if (ratio < PUBLISHED_COMPA_FLOOR || ratio > PUBLISHED_COMPA_CEILING) outsideRatio += 1;
  }
  assert.equal(outsideBand, ABOVE_BAND_CENSUS, "the count of pay rows outside their own band has moved");
  assert.equal(outsideRatio, ABOVE_BAND_CENSUS, "the count of pay rows outside the published ratio band has moved");
});

test("HR-C6-T6: exactly one employee is paid above their own band, and every clause of the draw holds", () => {
  let above = 0;
  let below = 0;
  let onBoundary = 0;
  let topTail = 0;
  let bottomTail = 0;
  for (const row of employees) {
    const band = bandById.get(row.band_id);
    const pay = num(row.base_pay_amount);
    const low = num(band.band_min);
    const high = num(band.band_max);
    if (pay > high) above += 1;
    else if (pay < low) below += 1;
    else if (pay === high || pay === low) onBoundary += 1;
    const span = high - low;
    if (pay >= high - 0.05 * span) topTail += 1;
    if (pay <= low + 0.05 * span) bottomTail += 1;
  }
  assert.equal(above, ABOVE_BAND_CENSUS);
  assert.equal(below, BELOW_BAND_CENSUS, "a pay row sits below its own band minimum, and this artifact plants none");
  assert.equal(onBoundary, BOUNDARY_EXACT_CENSUS);
  assert.equal(above + below + onBoundary, OPEN_INTERVAL_CENSUS, "reading the band as an open interval no longer returns the published census");
  assert.equal(topTail, TOP_TAIL_CENSUS);
  assert.equal(bottomTail, BOTTOM_TAIL_CENSUS);
  assert.ok(topTail > 0 && bottomTail > 0, "one of the two five percent tails is empty");

  // The clause set, recomputed here from the committed pack rather than read
  // out of the generator. The carrier is reached by rule and never named.
  assert.equal(aboveBand.length, 1);
  const carrier = aboveBand[0];
  const carrierRoster = rosterById.get(carrier.employee_id);
  assert.equal(carrierRoster.employment_status, "active");
  assert.equal(carrierRoster.level, "IC");

  const breachingIds = new Set(breachingGroups.flatMap((group) => [...group.cohort_a, ...group.cohort_b]).map((row) => row.employee_id));
  assert.ok(!breachingIds.has(carrier.employee_id), "the row paid above its band sits inside the group that carries the other finding");

  const frozenPair = readFrozenPair();
  assert.ok(!frozenPair.includes(carrier.employee_id), "the row paid above its band is one of the frozen one to one pair");

  const overdue = assignments.filter((row) => row.submitted_date === "" && row.due_date < AS_OF);
  assert.equal(overdue.length, 1, "the committed review cycle no longer holds exactly one assignment that is outstanding and past its due date");
  assert.ok(![overdue[0].reviewer_employee_id, overdue[0].reviewee_employee_id].includes(carrier.employee_id));

  assert.equal(exitRecord.length, 1);
  assert.notEqual(carrier.employee_id, exitRecord[0].employee_id);
  assert.ok(!allText.includes("EMP-0601"), "a C6 byte names an id the roster does not carry");

  const named = namedInArtifacts();
  assert.ok(!named.has(carrier.employee_id), "the row paid above its band is named by full name in a frozen artifact");
  const sensitivitySubjects = new Set(sensitivityRows.map((row) => row.employee_id));
  assert.ok(!sensitivitySubjects.has(carrier.employee_id));
  const reviewPopulation = new Set(assignments.flatMap((row) => [row.reviewer_employee_id, row.reviewee_employee_id]));
  assert.ok(!reviewPopulation.has(carrier.employee_id));

  const candidates = activeRoster
    .filter((row) => row.level === "IC")
    .filter((row) => !frozenPair.includes(row.employee_id))
    .filter((row) => ![overdue[0].reviewer_employee_id, overdue[0].reviewee_employee_id].includes(row.employee_id))
    .filter((row) => row.employee_id !== exitRecord[0].employee_id && row.employee_id !== "EMP-0601")
    .filter((row) => !named.has(row.employee_id))
    .filter((row) => !sensitivitySubjects.has(row.employee_id))
    .filter((row) => !reviewPopulation.has(row.employee_id));
  assert.equal(candidates.length, CANDIDATE_SET_CENSUS, "the candidate set the clauses define before the group clause has moved");
});

test("HR-C6-T7: every group splits evenly, and evaluability is a function of size", () => {
  assert.equal(groupList.length, BAND_ROWS);
  for (const group of groupList) {
    const size = memberCount(group);
    assert.equal(size, num(group.band.headcount_in_band), `${group.band.band_id} membership does not agree with its own headcount column`);
    assert.ok(Math.abs(group.cohort_a.length - group.cohort_b.length) <= 1, `${group.band.band_id} cohorts differ by more than one member`);
    assert.deepEqual(
      [group.cohort_a.length, group.cohort_b.length].sort((a, b) => a - b),
      [Math.floor(size / 2), Math.ceil(size / 2)],
      `${group.band.band_id} is not split as evenly as its size allows`
    );
    assert.equal(isEvaluable(group), Math.floor(size / 2) >= PUBLISHED_MINIMUM_GROUP_SIZE, "evaluability is not a function of group size alone");
  }
  assert.equal(num(grammar.minimum_group_size), PUBLISHED_MINIMUM_GROUP_SIZE);
  assert.equal(evaluableGroups.length, EVALUABLE_GROUPS);
  assert.equal(num(grammar.evaluable_group_count), EVALUABLE_GROUPS);
  assert.equal(evaluableGroups.reduce((sum, group) => sum + memberCount(group), 0), EVALUABLE_COVERAGE);
  for (const group of evaluableGroups) {
    assert.ok(!["Executive", "VP", "Director"].includes(group.band.level), "an executive, vice president or director group is evaluable");
  }
  for (const row of employees) {
    assert.ok(PUBLISHED_COHORTS.includes(row.synthetic_equity_cohort), "a row carries a cohort value that is not published");
  }
  assert.deepEqual(grammar.synthetic_equity_cohort_vocabulary.split(";"), PUBLISHED_COHORTS);
});

test("HR-C6-T8: the cohort is a function of group membership and a seed, and of nothing else in the pack", () => {
  // The structural claim, in three parts. First: the split is balanced inside
  // every group, so a group's evaluability cannot be a property of the draw.
  for (const group of groupList) {
    assert.ok(Math.abs(group.cohort_a.length - group.cohort_b.length) <= 1);
  }

  // Second: no attribute in the pack determines the cohort. For every value of
  // every attribute a reader could reach for, with at least two people in it,
  // both cohorts appear, so knowing the attribute tells a reader nothing.
  const tenures = employees.map((row) => tenureMonths(row.employee_id)).sort((a, b) => a - b);
  const decileOf = (months) => Math.min(9, Math.floor((10 * tenures.filter((t) => t < months).length) / tenures.length));
  const attributes = {
    work_location: (row) => row.work_location,
    department: (row) => rosterById.get(row.employee_id).department,
    level: (row) => rosterById.get(row.employee_id).level,
    tenure_decile: (row) => String(decileOf(tenureMonths(row.employee_id))),
    surname_initial: (row) => rosterById.get(row.employee_id).last_name[0],
  };
  for (const [name, read] of Object.entries(attributes)) {
    const classes = new Map();
    for (const row of employees) {
      const value = read(row);
      if (!classes.has(value)) classes.set(value, new Set());
      classes.get(value).add(row.synthetic_equity_cohort);
    }
    for (const [value, seen] of classes) {
      const size = employees.filter((row) => read(row) === value).length;
      if (size < 2) continue;
      assert.equal(seen.size, 2, `knowing ${name} is ${value} would tell a reader the cohort`);
    }
  }

  // Third: the split moves when the seed moves and nothing else does. A shuffle
  // of the same members under a different stream name lands on a different
  // partition in all but a handful of groups, which is what "a function of the
  // group and the seed alone" means when it is checked rather than asserted.
  const alternative = createRng("HR-12", "equity-cohort-alternative");
  let moved = 0;
  for (const group of evaluableGroups) {
    const members = [...group.cohort_a, ...group.cohort_b]
      .map((row) => row.employee_id).sort();
    const shuffled = alternative.shuffle(members);
    const drawn = new Set(shuffled.slice(0, Math.ceil(members.length / 2)));
    const shippedA = new Set(group.cohort_a.map((row) => row.employee_id));
    const same = drawn.size === shippedA.size && [...drawn].every((employeeId) => shippedA.has(employeeId));
    if (!same) moved += 1;
  }
  assert.ok(moved >= EVALUABLE_GROUPS - 4, `only ${moved} of ${EVALUABLE_GROUPS} evaluable groups split differently under a different stream`);

  // And the pay file carries nothing a cohort could have been derived from.
  for (const column of ["first_name", "last_name", "email", "gender", "ethnicity", "age", "date_of_birth"]) {
    assert.ok(!employeeTable.cols.includes(column));
  }
});

test("HR-C6-T9: exactly one evaluable group carries a gap over the published threshold", () => {
  assert.equal(num(grammar.unadjusted_gap_threshold_pct), PUBLISHED_GAP_THRESHOLD);
  assert.equal(breachingGroups.length, 1, "the count of evaluable groups over the published threshold has moved");
  const plantGap = Math.abs(gapOf(breachingGroups[0]));
  assert.ok(
    plantGap >= PLANT_GAP_LOW && plantGap <= PLANT_GAP_HIGH,
    `the breaching group's gap recomputes to ${plantGap}, outside the constructed band`
  );
  for (const group of evaluableGroups) {
    if (group === breachingGroups[0]) continue;
    assert.ok(
      Math.abs(gapOf(group)) <= NON_PLANT_GAP_LIMIT,
      `an evaluable group of ${memberCount(group)} recomputes to ${gapOf(group)}, outside the limit every other group is constructed inside`
    );
  }

  // The three qualifier-dropped censuses, each recomputed rather than read.
  const allGroups = groupList.filter((group) => group.cohort_a.length > 0 && group.cohort_b.length > 0);
  assert.equal(
    allGroups.filter((group) => Math.abs(gapOf(group)) >= PUBLISHED_GAP_THRESHOLD).length,
    ALL_GROUPS_OVER_THRESHOLD_CENSUS,
    "testing every group rather than the evaluable ones no longer returns the published census"
  );
  assert.ok(ALL_GROUPS_OVER_THRESHOLD_CENSUS > breachingGroups.length, "the evaluable qualifier no longer differentiates");
  assert.equal(evaluableGroups.filter((group) => Math.abs(gapOf(group)) >= 2.00).length, EVALUABLE_AT_TWO_PERCENT_CENSUS);
  assert.equal(evaluableGroups.filter((group) => gapOf(group) > 0).length, COHORT_A_LEADS_CENSUS);
  assert.ok(
    COHORT_A_LEADS_CENSUS > 0 && COHORT_A_LEADS_CENSUS < EVALUABLE_GROUPS,
    "one cohort leads every evaluable group, which would make the sign of the gap a property of the file"
  );
});

test("HR-C6-T10: both published controls hold on every evaluable group, not only on the one that breaches", () => {
  assert.equal(num(grammar.median_tenure_tolerance_months), PUBLISHED_TENURE_TOLERANCE);
  assert.equal(num(grammar.location_mix_tolerance_pct), PUBLISHED_LOCATION_TOLERANCE);
  assert.equal(num(grammar.tenure_increment_per_year), 0.012);
  assert.equal(num(grammar.tenure_increment_cap), 0.120);
  assert.deepEqual(grammar.work_location_vocabulary.split(";"), PUBLISHED_WORK_LOCATIONS);
  const ranges = Object.fromEntries(grammar.location_compa_ranges.split(";").map((pair) => {
    const [name, span] = pair.split("=");
    const [low, high] = span.split(" to ").map(Number);
    return [name, { low, high }];
  }));
  assert.deepEqual(ranges, PUBLISHED_LOCATION_RANGES);
  for (const row of employees) {
    assert.ok(PUBLISHED_WORK_LOCATIONS.includes(row.work_location), "a row carries a work location that is not published");
  }

  for (const group of evaluableGroups) {
    const tenureA = median(group.cohort_a.map((row) => tenureMonths(row.employee_id)));
    const tenureB = median(group.cohort_b.map((row) => tenureMonths(row.employee_id)));
    assert.ok(
      Math.abs(tenureA - tenureB) <= PUBLISHED_TENURE_TOLERANCE,
      `a group of ${memberCount(group)} carries a median tenure difference of ${Math.abs(tenureA - tenureB)} months`
    );
    for (const location of PUBLISHED_WORK_LOCATIONS) {
      const shareA = (100 * group.cohort_a.filter((row) => row.work_location === location).length) / group.cohort_a.length;
      const shareB = (100 * group.cohort_b.filter((row) => row.work_location === location).length) / group.cohort_b.length;
      assert.ok(
        Math.abs(shareA - shareB) <= PUBLISHED_LOCATION_TOLERANCE,
        `a group of ${memberCount(group)} carries a ${location} share difference outside the published tolerance`
      );
    }
  }
});

test("HR-C6-T11: the trigger is a two limb computation and neither column is a flag", () => {
  assert.equal(num(grammar.remediation_window_months), PUBLISHED_REMEDIATION_MONTHS);
  assert.equal(grammar.gap_parameter_source, "people-hr implementation plan v2 section 3.6");

  const stale = (band) => monthsBetween(band.last_pay_review_date, AS_OF) >= PUBLISHED_REMEDIATION_MONTHS;
  const staleCount = bands.filter(stale).length;
  assert.equal(staleCount, STALE_BAND_CENSUS, "the count of bands carrying a pay review older than the published window has moved");
  assert.ok(staleCount > 1, "only one band carries a stale pay review, which would make that column a flag");
  assert.ok(staleCount < BAND_ROWS, "every band carries a stale pay review, so the second limb would never differentiate");
  for (const band of bands) {
    assert.match(band.last_pay_review_date, /^\d{4}-\d{2}-\d{2}$/);
    assert.ok(band.last_pay_review_date <= AS_OF, `${band.band_id} carries a pay review date after the as-of`);
  }

  const bothLimbs = evaluableGroups.filter(
    (group) => Math.abs(gapOf(group)) >= PUBLISHED_GAP_THRESHOLD && stale(group.band)
  );
  assert.equal(bothLimbs.length, BOTH_LIMBS_CENSUS, "the count of evaluable groups satisfying both limbs has moved");

  // No statute, citation, article number or directive text, anywhere.
  for (const pattern of [/directive/i, /\barticle\s*\d/i, /\bregulation\b/i, /\b\d{4}\/\d{2,4}\b/, /\bEU\b/, /\bgdpr\b/i]) {
    assert.ok(!pattern.test(allText), `a C6 byte matches ${pattern}, and this artifact names no law`);
  }
});

test("HR-C6-T12: no C6 cell carries a percentage, a rating, a score, a place name or a date after the as-of", () => {
  assert.ok(!allText.includes("%"), "a C6 cell carries a percentage");
  assert.ok(!/\d{2}:\d{2}/.test(allText), "a C6 cell carries a time of day");
  const EN_DASH = String.fromCharCode(0x2013);
  const EM_DASH = String.fromCharCode(0x2014);
  assert.ok(!allText.includes(EN_DASH) && !allText.includes(EM_DASH), "a C6 byte carries a dash this pack does not write");

  const forbiddenColumns = ["risk_score", "risk", "score", "rating", "probability", "likelihood",
    "propensity", "rank", "forecast", "prediction", "recommendation", "reason", "rehire_eligible",
    "date_of_birth", "home_city", "health_accommodation_note", "gender", "ethnicity"];
  for (const [, table] of shippedFiles) {
    for (const column of forbiddenColumns) {
      assert.ok(!table.cols.includes(column), `a C6 file carries a ${column} column`);
    }
  }

  const HOME_CITIES = ["Alder Creek", "Braddock Hollow", "Coldwater Ridge", "Granite Bend",
    "Halstead Springs", "Lakemont Park", "Mapleton Heights", "New Haverbrook", "Port Wexley",
    "Quarry Hills", "Ridgemont Falls", "Silverbrook", "Stonebury", "Tallgrass Junction", "Wilder Bend"];
  for (const city of HOME_CITIES) {
    assert.ok(!allText.includes(city), `a C6 byte carries ${city}, which is a restricted home city elsewhere in the pack`);
  }

  for (const prefix of ["EXT", "RQN", "HRC", "RVA", "RVC", "GOL", "GSA", "RHS", "MSD"]) {
    assert.ok(!new RegExp(`(^|[^A-Z])${prefix}-[0-9]`).test(allText), `a C6 byte carries a ${prefix}- token`);
  }
  for (const prefix of ["ca", "pe"]) {
    assert.ok(!new RegExp(`(^|[^a-z])${prefix}-[0-9]`).test(allText), `a C6 byte carries a ${prefix}- token`);
  }

  const dateCells = [];
  for (const [, table] of shippedFiles) {
    for (const row of table.rows) {
      for (const value of Object.values(row)) {
        if (/^\d{4}-\d{2}-\d{2}$/.test(value)) dateCells.push(value);
      }
    }
  }
  assert.ok(dateCells.length > 0);
  for (const value of dateCells) {
    assert.ok(value <= AS_OF, `a C6 cell carries ${value}, which is after the as-of`);
  }
  assert.equal(grammar.as_of, AS_OF);
  assert.equal(grammar.band_effective_date, bands[0].band_effective_date);
  for (const band of bands) assert.equal(band.band_effective_date, grammar.band_effective_date);
  for (const row of employees) {
    assert.ok(!isWeekend(row.compensation_effective_date), `${row.employee_id} carries a compensation effective date on a weekend`);
    assert.ok(!isWeekend(row.last_adjustment_date), `${row.employee_id} carries a last adjustment date on a weekend`);
    assert.ok(row.last_adjustment_date <= row.compensation_effective_date);
    assert.ok(row.compensation_effective_date >= rosterById.get(row.employee_id).start_date);
    assert.ok(row.last_adjustment_date >= rosterById.get(row.employee_id).start_date);
  }

  // The regenerated bytes are the committed ones, so a generator edit fails
  // here rather than only in the byte diff the CLI runs.
  for (const [path] of shippedFiles) {
    assert.equal(fileByPath(generated, path).content, shipped(path), `${path} no longer regenerates to the committed bytes`);
  }
  assert.equal(generated.length, shippedFiles.length);
});

// ------------------------------------------------------------ local readers

/** The frozen one to one pair, read off its own two documents and resolved against the roster. */
function readFrozenPair() {
  const text = readFileSync(join(REPO_ROOT, "artifacts", "HR-09", "one-to-one-log.md"), "utf8");
  return ["Manager", "Report"].map((label) => {
    const match = new RegExp(`^- ${label}: (.+?) \\((.+?)\\)$`, "m").exec(text);
    assert.ok(match, `the frozen one to one log carries no "- ${label}:" line`);
    const rows = activeRoster.filter(
      (row) => `${row.first_name} ${row.last_name}` === match[1].trim() && row.role_title === match[2].trim()
    );
    assert.equal(rows.length, 1, `the frozen one to one ${label} resolves to ${rows.length} active roster rows`);
    return rows[0].employee_id;
  });
}

/** Every active employee named by full name somewhere under artifacts/. */
function namedInArtifacts() {
  const root = join(REPO_ROOT, "artifacts");
  const corpus = readdirSync(root, { recursive: true })
    .map(String)
    .filter((name) => name.endsWith(".md") || name.endsWith(".json"))
    .map((name) => readFileSync(join(root, name), "utf8"))
    .join("\n");
  const named = new Set();
  for (const row of activeRoster) {
    if (corpus.includes(`${row.first_name} ${row.last_name}`)) named.add(row.employee_id);
  }
  return named;
}
