// The real-name screen shared by the drafted-document screens: what a document
// is allowed to capitalize.
//
// A drafted artifact is where a new person or company name slips into the
// universe unnoticed, because no generator is there to refuse it. A screen keyed
// on the CORE-04 roster cannot see the one name that matters, the invented one,
// so the rule is inverted: every capitalized phrase and every capitalized word
// in mid-sentence has to be something the pack already accounts for. Anything
// else fails and the author either fixes the document or says in the furniture
// list why the phrase belongs there.
//
// tests/drafted/fin-40-mnpi-screen.test.js is the precedent and keeps its own
// inline copy of the older, stricter phrase rule; this module generalizes the
// approach for the D5 documents, which carry tables, document-control blocks
// and role titles at the end of sentences. Two differences, both about where a
// sentence begins rather than about what a name is:
//
//   * a candidate is screened as written first, and only then with its first
//     word dropped, and only when the match itself began a sentence AND that
//     first word is itself accounted for. A capitalized word that opens a
//     sentence, a table cell, a heading or a bullet is ordinary English, which
//     is the same reason the word screen skips it. Without the drop, "The
//     Controller raises it" reports the phrase "The Controller"; without the
//     condition on the dropped word, the first token of any table cell is
//     unscreened and "| Harriet Bank |" walks straight through. So the article
//     has to be listed furniture for the drop to happen at all, and an
//     unaccounted opener fails as the whole phrase it was written as.
//   * a candidate that runs across a sentence boundary is split at it, so
//     "Atticus Dundee Inc. It" is screened as the protagonist and a dropped
//     one-word remainder rather than as an unknown phrase.
//
// Trailing full stops are stripped on both sides before comparing, so a role
// title that ends a sentence ("approved by the VP, Finance.") screens as the
// title it is.

/** Two or more capitalized words in a row, the FIN-40 shape. */
const PHRASE = /\b[A-Z][a-zA-Z]+(?:[ ,]+[A-Z][a-zA-Z.]+)+/g;

/** Single capitalized tokens, including a trailing stop or possessive. */
const WORD = /[A-Za-z][A-Za-z.'-]*/g;

/**
 * Characters that put the next capital at the start of something: a sentence, a
 * heading, a table cell, a list bullet, a parenthetical.
 */
const OPENERS = "\n.!?:|#->*(";

const bare = (text) => text.replace(/\.+$/, "");
const isPhrase = (text) => /[ ,]/.test(text.trim());

/** Does the character before `index` open a sentence, cell, heading or bullet? */
function startsSentence(doc, index) {
  let i = index - 1;
  while (i >= 0 && (doc[i] === " " || doc[i] === "*" || doc[i] === '"')) i -= 1;
  return i < 0 || OPENERS.includes(doc[i]);
}

/**
 * The allowed sets, built from whatever the pack already ships plus the typed
 * furniture list. Phrases are screened whole; words are screened one by one, so
 * both are derived from the same sources.
 *
 * @param {object} sources
 * @param {string[]} sources.derived  protagonist, role titles, account names:
 *   strings read out of canon or out of generated bytes, never typed.
 * @param {string[]} sources.furniturePhrases  document furniture, two words up.
 * @param {string[]} sources.furnitureWords    document furniture, single words.
 */
export function allowedFrom({ derived, furniturePhrases = [], furnitureWords = [] }) {
  const phrases = new Set();
  const words = new Set();
  for (const source of derived) {
    phrases.add(source);
    phrases.add(bare(source));
    for (const match of source.match(PHRASE) ?? []) {
      phrases.add(match);
      phrases.add(bare(match));
    }
    for (const word of source.split(/[^A-Za-z.'-]+/)) {
      if (/^[A-Z]/.test(word)) words.add(bare(word));
    }
  }
  for (const phrase of furniturePhrases) {
    phrases.add(phrase);
    phrases.add(bare(phrase));
  }
  for (const word of furnitureWords) words.add(bare(word));
  return { phrases, words };
}

/** Every capitalized phrase in `doc` that `allowed` does not account for. */
export function unscreenedPhrases(doc, allowed) {
  const ok = (text) => allowed.phrases.has(text) || allowed.phrases.has(bare(text));
  const found = new Set();
  for (const match of doc.matchAll(PHRASE)) {
    for (const raw of match[0].split(/(?<=\.)\s+/)) {
      const part = raw.trim();
      if (!isPhrase(part) || ok(part)) continue;
      // The opener concession, and its limit. A candidate that begins a
      // sentence, cell, heading or bullet may shed its first word, because that
      // word is ordinary English rather than part of a name. It may shed it
      // only when the word is itself accounted for: a first token nobody has
      // listed is exactly where an invented name hides, and dropping it
      // unconditionally would let every table cell open with one.
      const first = part.match(/^[A-Z][a-zA-Z]*/)[0];
      const shed = startsSentence(doc, match.index) && allowed.words.has(bare(first));
      if (!shed) { found.add(part); continue; }
      const dropped = part.replace(/^[A-Z][a-zA-Z]*[ ,]+/, "");
      // A one-word remainder is the word screen's business, not this one's.
      if (!isPhrase(dropped) || ok(dropped)) continue;
      found.add(dropped);
    }
  }
  return [...found];
}

/**
 * Every mid-sentence capitalized word `allowed` does not account for. A two-word
 * screen on its own lets a one-word name through ("Northwind", "Okafor"), which
 * is why this runs beside it.
 */
export function unscreenedWords(doc, allowed) {
  const found = new Set();
  for (const match of doc.matchAll(WORD)) {
    const word = bare(match[0]);
    if (!/^[A-Z]/.test(word)) continue;
    if (startsSentence(doc, match.index)) continue;
    if (allowed.words.has(word)) continue;
    found.add(word);
  }
  return [...found];
}
